### ISSUE TITLE
0001 - Two Sum

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#1]
Given an array of integers, return **indices** of the two numbers such that they add up to a specific target.

You may assume that each input would have **_exactly_** one solution, and you may not use the same element twice.

**Example:**
```
Given nums = [2, 7, 11, 15], target = 9,

Because nums[0] + nums[1] = 2 + 7 = 9,
return [0, 1].
```

[Two Sum at LeetCode](https://leetcode.com/problems/two-sum/)

**Comment by VaibhaveS** [comment]
Hey can you assign me this issue?
I have good experience with competitive programming as well [ rated 1900+ on codechef ]
