### ISSUE TITLE
0015 - 3Sum

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#10]
Given an array `nums `of n integers, are there elements _a, b, c_ in `nums `such that _a + b + c = 0_? Find all unique triplets in the array which gives the sum of zero.

**Note:**
The solution set must not contain duplicate triplets.

**Example:**
```
Given array nums = [-1, 0, 1, 2, -1, -4],

A solution set is:
[
  [-1, 0, 1],
  [-1, -1, 2]
]
```

[3Sum at LeetCode](https://leetcode.com/problems/3sum/)

**Comment by VaibhaveS** [comment]
Hey can you assign me this issue?
I have good experience with competitive programming as well [ rated 1900+ on codechef ]

**Comment by vJechsmayr** [comment]
Problem solved
