### ISSUE TITLE
0459 - Repeated Substring Pattern

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#107]
## Description of the Problem
Given a non-empty string check if it can be constructed by taking a substring of it and appending multiple copies of the substring together. You may assume the given string consists of lowercase English letters only and its length will not exceed 10000.

**Example 1:**
```
Input: "abab"
Output: True
Explanation: It's the substring "ab" twice.
```

**Example 2:**
```
Input: "aba"
Output: False
```

**Example 3:**
```
Input: "abcabcabcabc"
Output: True
Explanation: It's the substring "abc" four times. (And the substring "abcabc" twice.)
```

## Code
```
class Solution:
    def repeatedSubstringPattern(self, s: str) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/repeated-substring-pattern/)

**Comment by borakrc** [comment]
@vJechsmayr I would like to work on this

**Comment by Palaash05** [comment]
I would like to work on this issue.
