### ISSUE TITLE
0763 - Partition Labels

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#108]
## Description of the Problem
A string `S` of lowercase English letters is given. We want to partition this string into as many parts as possible so that each letter appears in at most one part, and return a list of integers representing the size of these parts.

**Example 1:**
```
Input: S = "ababcbacadefegdehijhklij"
Output: [9,7,8]
Explanation:
The partition is "ababcbaca", "defegde", "hijhklij".
This is a partition so that each letter appears in at most one part.
A partition like "ababcbacadefegde", "hijhklij" is incorrect, because it splits S into less parts.
```

**Note:**
- `S` will have length in range `[1, 500]`.
- `S` will consist of lowercase English letters (`'a'` to `'z'`) only.

## Code
```
class Solution:
    def partitionLabels(self, S: str) -> List[int]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/partition-labels/)

**Comment by bhavidhingra** [comment]
It seems like an interesting problem. Please assign it to me.

**Comment by bhavidhingra** [comment]
which language do you want the solution in?
