### ISSUE TITLE
0044 - Wildcard Matching

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#109]
## Description of the Problem
Given an input string (`s`) and a pattern (`p`), implement wildcard pattern matching with support for `'?'` and `'*'`.

```
'?' Matches any single character.
'*' Matches any sequence of characters (including the empty sequence).
```

The matching should cover the **entire** input string (not partial).

**Note:**
- `s` could be empty and contains only lowercase letters `a-z`.
- `p` could be empty and contains only lowercase letters `a-z`, and characters like `?` or `*`.

**Example 1:**
```
Input:
s = "aa"
p = "a"
Output: false
Explanation: "a" does not match the entire string "aa".
```

**Example 2:**
```
Input:
s = "aa"
p = "*"
Output: true
Explanation: '*' matches any sequence.
```

**Example 3:**
```
Input:
s = "cb"
p = "?a"
Output: false
Explanation: '?' matches 'c', but the second letter is 'a', which does not match 'b'.
```

**Example 4:**
```
Input:
s = "adceb"
p = "*a*b"
Output: true
Explanation: The first '*' matches the empty sequence, while the second '*' matches the substring "dce".
```

**Example 5:**
```
Input:
s = "acdcb"
p = "a*c?b"
Output: false
```

## Code
```
class Solution:
    def isMatch(self, s: str, p: str) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/wildcard-matching/)

**Comment by PushpikaWan** [comment]
Can I work on this? please assign to me

**Comment by PushpikaWan** [comment]
can I try this one? Please assign to me

**Comment by CuriousMonkey7** [comment]
I want to try this one. I can do this in java and python. Please assign to me.
