### ISSUE TITLE
0045 - Jump Game II

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#110]
## Description of the Problem
Given an array of non-negative integers, you are initially positioned at the first index of the array.

Each element in the array represents your maximum jump length at that position.

Your goal is to reach the last index in the minimum number of jumps.

**Example:**
```
Input: [2,3,1,1,4]
Output: 2
Explanation: The minimum number of jumps to reach the last index is 2.
    Jump 1 step from index 0 to 1, then 3 steps to the last index.
```

**Note:**
You can assume that you can always reach the last index.

## Code
```
class Solution:
    def jump(self, nums: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/jump-game-ii/)

**Comment by liudj2008** [comment]
@vJechsmayr Can I work on this problem? Thanks!
