### ISSUE TITLE
0049 - Group Anagrams

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#111]
## Description of the Problem
Given an array of strings `strs`, group **the anagrams** together. You can return the answer in **any order**.

An **Anagram** is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

**Example 1:**
```
Input: strs = ["eat","tea","tan","ate","nat","bat"]
Output: [["bat"],["nat","tan"],["ate","eat","tea"]]
```

**Example 2:**
```
Input: strs = [""]
Output: [[""]]
```

**Example 3:**
```
Input: strs = ["a"]
Output: [["a"]]
```
 
**Constraints:**

- `1 <= strs.length <= 104`
- `0 <= strs[i].length <= 100`
- `strs[i]` consists of lower-case English letters.

## Code
```
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/group-anagrams/)

**Comment by krish7777** [comment]
@vJechsmayr I would like to work on this

**Comment by geoffgeorgein** [comment]
I shall work on this in python. Could you assign me this.I love solving problems
