### ISSUE TITLE
0278 - First Bad Version

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#112]
## Description of the Problem
You are a product manager and currently leading a team to develop a new product. Unfortunately, the latest version of your product fails the quality check. Since each version is developed based on the previous version, all the versions after a bad version are also bad.

Suppose you have n versions `[1, 2, ..., n]` and you want to find out the first bad one, which causes all the following ones to be bad.

You are given an API `bool isBadVersion(version)` which will return whether `version `is bad. Implement a function to find the first bad version. You should minimize the number of calls to the API.

**Example:**
```
Given n = 5, and version = 4 is the first bad version.

call isBadVersion(3) -> false
call isBadVersion(5) -> true
call isBadVersion(4) -> true

Then 4 is the first bad version.
```

## Code
```
# The isBadVersion API is already defined for you.
# @param version, an integer
# @return an integer
# def isBadVersion(version):

class Solution:
    def firstBadVersion(self, n):
        """
        :type n: int
        :rtype: int
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/first-bad-version/)

**Comment by leonardoAnjos16** [comment]
I'd like to solve it! Could you assign it to me?
