### ISSUE TITLE
0374 - Guess Number Higher or Lower

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#113]
## Description of the Problem
We are playing the Guess Game. The game is as follows:

I pick a number from `1` to `n`. You have to guess which number I picked.

Every time you guess wrong, I will tell you whether the number I picked is higher or lower than your guess.

You call a pre-defined API `int guess(int num)`, which returns 3 possible results:
- `-1`: The number I picked is lower than your guess (i.e. `pick > num`).
- `1`: The number I picked is higher than your guess (i.e. `pick < num`).
- `0`: The number I picked is equal to your guess (i.e.` pick == num`).

Return _the number that I picked_.

 

**Example 1:**
```
Input: n = 10, pick = 6
Output: 6
```

**Example 2:**
```
Input: n = 1, pick = 1
Output: 1
```

**Example 3:**
```
Input: n = 2, pick = 1
Output: 1
```

**Example 4:**
```
Input: n = 2, pick = 2
Output: 2
```
 

**Constraints:**
- `1 <= n <= 231 - 1`
- `1 <= pick <= n`

## Code
```
# The guess API is already defined for you.
# @param num, your guess
# @return -1 if my number is lower, 1 if my number is higher, otherwise return 0
# def guess(num: int) -> int:

class Solution:
    def guessNumber(self, n: int) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/guess-number-higher-or-lower/)

**Comment by yunusbulutt** [comment]
I would like to solve this! Can you please assign ?

**Comment by rahulsunil2** [comment]
I've great experience in writing [clean and readable code](https://github.com/rahulsunil2/CProgramming/blob/master/GraphTheory/layCables.c), so I would like to work on this issue.
Can you please assign it to me?

**Comment by LeonardoCBoar** [comment]
Hi, i would like to help you and solve this problem, i have a good experience with programming logic especially for game algorithms.

**Comment by geoffgeorgein** [comment]
I shall work on python. Could you assign me this. I love solving coding problems.

**Comment by satyamasthanaa** [comment]
I would like to contribute to this, please assign me this task. Thankyou.
