### ISSUE TITLE
0053 - Maximum Subarray

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#114]
## Description of the Problem
Given an integer array `nums`, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.

**Follow up:** If you have figured out the `O(n)` solution, try coding another solution using the **divide and conquer** approach, which is more subtle.

**Example 1:**
```
Input: nums = [-2,1,-3,4,-1,2,1,-5,4]
Output: 6
Explanation: [4,-1,2,1] has the largest sum = 6.
```

**Example 2:**
```
Input: nums = [1]
Output: 1
```

**Example 3:**
```
Input: nums = [0]
Output: 0
```

**Example 4:**
```
Input: nums = [-1]
Output: -1
```

**Example 5:**
```
Input: nums = [-2147483647]
Output: -2147483647
```
 
**Constraints:**
- `1 <= nums.length <= 2 * 104`
- `-231 <= nums[i] <= 231 - 1`

## Code
```
class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/maximum-subarray/)

**Comment by yunusbulutt** [comment]
I would like to solve this! Can you please assign ?

**Comment by Mayank662** [comment]
Sir @vJechsmayr  Please assign me this issue.

**Comment by satyamasthanaa** [comment]
I would like to contribute to this, please assign me this task. Thankyou.
