### ISSUE TITLE
0829 - Consecutive Numbers Sum

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#122]
## Description of the Problem
Given a positive integer N, how many ways can we write it as a sum of consecutive positive integers?

**Example 1:**
```
Input: 5
Output: 2
Explanation: 5 = 5 = 2 + 3
```

**Example 2:**
```
Input: 9
Output: 3
Explanation: 9 = 9 = 4 + 5 = 2 + 3 + 4
```

**Example 3:**
```
Input: 15
Output: 4
Explanation: 15 = 15 = 8 + 7 = 4 + 5 + 6 = 1 + 2 + 3 + 4 + 5
```

**Note:** `1 <= N <= 10 ^ 9.`

## Code
```
class Solution:
    def consecutiveNumbersSum(self, N: int) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/consecutive-numbers-sum/)

**Comment by DeepakR-28** [comment]
I would like to help you Senor

**Comment by VishnuThokala** [comment]
Hi, 
Can I work on this?
