### ISSUE TITLE
0056 - Merge Intervals

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#126]
## Description of the Problem
Given a collection of intervals, merge all overlapping intervals.

**Example 1:**
```
Input: intervals = [[1,3],[2,6],[8,10],[15,18]]
Output: [[1,6],[8,10],[15,18]]
Explanation: Since intervals [1,3] and [2,6] overlaps, merge them into [1,6].
```

**Example 2:**
```
Input: intervals = [[1,4],[4,5]]
Output: [[1,5]]
Explanation: Intervals [1,4] and [4,5] are considered overlapping.
```

**NOTE:** input types have been changed on April 15, 2019. Please reset to default code definition to get new method signature.

**Constraints:**
- `intervals[i][0] <= intervals[i][1]`

## Code
```
class Solution:
    def merge(self, intervals: List[List[int]]) -> List[List[int]]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/merge-intervals/)

**Comment by visheshruparelia** [comment]
Hi @vJechsmayr , Can I work on this?

**Comment by Himith** [comment]
I want to work on this
