### ISSUE TITLE
0055 - Jump Game

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#127]
## Description of the Problem
Given an array of non-negative integers, you are initially positioned at the first index of the array.

Each element in the array represents your maximum jump length at that position.

Determine if you are able to reach the last index.

**Example 1:**
```
Input: nums = [2,3,1,1,4]
Output: true
Explanation: Jump 1 step from index 0 to 1, then 3 steps to the last index.
```

**Example 2:**
```
Input: nums = [3,2,1,0,4]
Output: false
Explanation: You will always arrive at index 3 no matter what. Its maximum jump length is 0, which makes it impossible to reach the last index.
```

**Constraints:**
- `1 <= nums.length <= 3 * 10^4`
- `0 <= nums[i][j] <= 10^5`

## Code
```
class Solution:
    def canJump(self, nums: List[int]) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/jump-game/)

**Comment by shanirub** [comment]
Hi there, can i work on this issue?

**Comment by Dilpreet047** [comment]
I want to work on this problem.

**Comment by shanirub** [comment]
Hi @vJechsmayr ,

I submitted my solution to LeetCode and got "Time Limit Exceeded". That's weird, because the problem description said nothing about time constraints. May I PR my solution anyway? Or should I work on my solution and get it to work faster?

Thanks,
Shani

**Comment by vJechsmayr** [comment]
@shanirub Please try make it faster to the Solution passes the Test and we avoid the "Time Limit Exceeded"
