### ISSUE TITLE
0174- Dungeon Game

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#129]
## Description of the Problem
The demons had captured the princess (**P**) and imprisoned her in the bottom-right corner of a dungeon. The dungeon consists of M x N rooms laid out in a 2D grid. Our valiant knight (**K**) was initially positioned in the top-left room and must fight his way through the dungeon to rescue the princess.

The knight has an initial health point represented by a positive integer. If at any point his health point drops to 0 or below, he dies immediately.

Some of the rooms are guarded by demons, so the knight loses health (_negative_ integers) upon entering these rooms; other rooms are either empty (_0's_) or contain magic orbs that increase the knight's health (_positive_ integers).

In order to reach the princess as quickly as possible, the knight decides to move only rightward or downward in each step.

**Write a function to determine the knight's minimum initial health so that he is able to rescue the princess.**

For example, given the dungeon below, the initial health of the knight must be at least **7** if he follows the optimal path `RIGHT-> RIGHT -> DOWN -> DOWN.`

![image](https://user-images.githubusercontent.com/6342890/94906061-23fc1900-049e-11eb-9930-5899e6fe3a2b.png)

**Note:**
- The knight's health has no upper bound.
- Any room can contain threats or power-ups, even the first room the knight enters and the bottom-right room where the princess is imprisoned.

## Code
```
class Solution:
    def calculateMinimumHP(self, dungeon: List[List[int]]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/dungeon-game/)

**Comment by Runanka** [comment]
I would like to work on this
