### ISSUE TITLE
0289 - Game of Life

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#131]
## Description of the Problem
According to the [Wikipedia's article](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life): "The **Game of Life**, also known simply as **Life**, is a cellular automaton devised by the British mathematician John Horton Conway in 1970."

Given a _board_ with _m_ by _n_ cells, each cell has an initial state _live_ (1) or _dead_ (0). Each cell interacts with its eight neighbors (horizontal, vertical, diagonal) using the following four rules (taken from the above Wikipedia article):

1. Any live cell with fewer than two live neighbors dies, as if caused by under-population.
2. Any live cell with two or three live neighbors lives on to the next generation.
3. Any live cell with more than three live neighbors dies, as if by over-population..
4. Any dead cell with exactly three live neighbors becomes a live cell, as if by reproduction.

Write a function to compute the next state (after one update) of the board given its current state. The next state is created by applying the above rules simultaneously to every cell in the current state, where births and deaths occur simultaneously.

**Example:**
```
Input: 
[
  [0,1,0],
  [0,0,1],
  [1,1,1],
  [0,0,0]
]
Output: 
[
  [0,0,0],
  [1,0,1],
  [0,1,1],
  [0,1,0]
]
```

**Follow up:**
1. Could you solve it in-place? Remember that the board needs to be updated at the same time: You cannot update some cells first and then use their updated values to update other cells.
2. In this question, we represent the board using a 2D array. In principle, the board is infinite, which would cause problems when the active area encroaches the border of the array. How would you address these problems?

## Code
```
class Solution:
    def gameOfLife(self, board: List[List[int]]) -> None:
        """
        Do not return anything, modify board in-place instead.
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/game-of-life/)

**Comment by js899** [comment]
Can I take this ? plz assign it to me

**Comment by Achyut-sudo** [comment]
@vJechsmayr  please assign me to this question

**Comment by vJechsmayr** [comment]
@Achyut-sudo Sorry it's already assigned to @js899 - if there is no PR within the next 6 days I will unassign him and you get assigned to this Issue 😸

**Comment by Achyut-sudo** [comment]
@vJechsmayr ok

**Comment by js899** [comment]
@vJechsmayr @Achyut-sudo I'm really sorry to respond so late, I'm quite busy with college exams, you can unassign me. Thanks for the opportunity though.

**Comment by Achyut-sudo** [comment]
@js899 no problem! 
hey, @vJechsmayr  now can I start working on it ???? 😄 

>

**Comment by Achyut-sudo** [comment]
hey,@vJechsmayr I have solved the problem assign me and 
![Uploading gol_leetcode.jpg…]()
I will create the pull request

**Comment by Achyut-sudo** [comment]
hey, @vJechsmayr  i have solved the problem just assign me and I will create the pull request
![gol_leetcode](https://user-images.githubusercontent.com/71660666/95672450-8780f780-0bbe-11eb-9c6f-2374a9acaa5c.jpg)

**Comment by vJechsmayr** [comment]
@Achyut-sudo Do you want to commit the PR?

**Comment by Achyut-sudo** [comment]
@vJechsmayr  yes please assign me fast, I have already solved it 
(just assign me and I will create the pr as I have a standing solution)

**Comment by Achyut-sudo** [comment]
hey @vJechsmayr, this one also failed, I am very sorry to say but I am kinda annoyed right because even though i am fulfilling all your guidelines and my codes are passing all leetCode tests still it is failing, please help
