### ISSUE TITLE
0292 - Nim Game

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#132]
## Description of the Problem
You are playing the following Nim Game with your friend: There is a heap of stones on the table, each time one of you take turns to remove 1 to 3 stones. The one who removes the last stone will be the winner. You will take the first turn to remove the stones.

Both of you are very clever and have optimal strategies for the game. Write a function to determine whether you can win the game given the number of stones in the heap.

**Example 1:**
```
Input: n = 4
Output: false
Explanation: If there are 4 stones in the heap, then you will never win the game;
No matter 1, 2, or 3 stones you remove, the last stone will always be removed by your friend.
```

**Example 2:**
```
Input: n = 1
Output: true
```

**Example 3:**
```
Input: n = 2
Output: true
```

**Constraints:**
- `1 <= n <= 231 - 1`

## Code
```
class Solution:
    def canWinNim(self, n: int) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/nim-game/)

**Comment by visheshruparelia** [comment]
Hi @vJechsmayr , can I work on this?

**Comment by VishnuThokala** [comment]
Can I work on this?

**Comment by sarthak55k** [comment]
May i do this i will do it in python
