### ISSUE TITLE
0064 - Minimum Path Sum

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#140]
## Description of the Problem
Given a `m x n` grid filled with non-negative numbers, find a path from top left to bottom right which minimizes the sum of all numbers along its path.

**Note:** You can only move either down or right at any point in time.

**Example:**
```
Input:
[
  [1,3,1],
  [1,5,1],
  [4,2,1]
]
Output: 7
Explanation: Because the path 1→3→1→1→1 minimizes the sum.
```

## Code
```
class Solution:
    def minPathSum(self, grid: List[List[int]]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/minimum-path-sum/)

**Comment by yunusbulutt** [comment]
I would like to solve this! Can you please assign ?

**Comment by Hinal-Srivastava** [comment]
Hi!
Can I work on this too?
