### ISSUE TITLE
0777 - Swap Adjacent in LR String

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#143]
## Description of the Problem
In a string composed of `'L'`, `'R'`, and `'X'` characters, like `"RXXLRXRXL"`, a move consists of either replacing one occurrence of `"XL"` with `"LX"`, or replacing one occurrence of `"RX"` with `"XR"`. Given the starting string `start `and the ending string `end`, return True if and only if there exists a sequence of moves to transform one string to the other.

**Example 1:**
```
Input: start = "X", end = "L"
Output: false
Explanation:
We can transform start to end following these steps:
RXXLRXRXL ->
XRXLRXRXL ->
XRLXRXRXL ->
XRLXXRRXL ->
XRLXXRRLX
```

**Example 2:**
```
Input: start = "LLR", end = "RRL"
Output: false
```

**Example 3:**
```
Input: start = "XLLR", end = "LXLX"
Output: false
```
 
**Constraints:**
- `1 <= start.length <= 104`
- `start.length == end.length`
- Both `start `and `end `will only consist of characters in `'L', 'R'`, and` 'X'`.

## Code
```
class Solution:
    def canTransform(self, start: str, end: str) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/swap-adjacent-in-lr-string/)

**Comment by TanayKulkarni** [comment]
Please assign it to me, I would love to do it

**Comment by Hinal-Srivastava** [comment]
Hi!
This seems interesting. Can I try it as well?

**Comment by TanayKulkarni** [comment]
#154
