### ISSUE TITLE
0111 - Minimum Depth of Binary Tree

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#149]
## Description of the Problem
Given a binary tree, find its minimum depth.

The minimum depth is the number of nodes along the shortest path from the root node down to the nearest leaf node.

**Note:** A leaf is a node with no children.

**Example:**
Given binary tree `[3,9,20,null,null,15,7],`

```
    3
   / \
  9  20
    /  \
   15   7
```
return its minimum depth = 2.

## Code
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def minDepth(self, root: TreeNode) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/minimum-depth-of-binary-tree/)

**Comment by TanayKulkarni** [comment]
That one is an easy one I can contribute!

**Comment by TanayKulkarni** [comment]
#154

**Comment by jyotiGambhir** [comment]
Can I add CPP solution to it?
