### ISSUE TITLE
0031 - Next Permutation

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#15]
## Description of the Problem
Implement **next permutation**, which rearranges numbers into the lexicographically next greater permutation of numbers.

If such arrangement is not possible, it must rearrange it as the lowest possible order (ie, sorted in ascending order).

The replacement must be in-place and use only constant extra memory.

Here are some examples. Inputs are in the left-hand column and its corresponding outputs are in the right-hand column.

```
1,2,3 → 1,3,2
3,2,1 → 1,2,3
1,1,5 → 1,5,1
```

##Code
```
class Solution:
    def nextPermutation(self, nums: List[int]) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/next-permutation/)

**Comment by prafgup** [comment]
@vJechsmayr  Please Assign this to me , I gave it a try already
