### ISSUE TITLE
0537 - Complex Number Multiplication

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#150]
## Description of the Problem
Given two strings representing two complex numbers.

You need to return a string representing their multiplication. Note i2 = -1 according to the definition.

**Example 1:**
```
Input: "1+1i", "1+1i"
Output: "0+2i"
Explanation: (1 + i) * (1 + i) = 1 + i2 + 2 * i = 2i, and you need convert it to the form of 0+2i.
```

**Example 2:**
```
Input: "1+-1i", "1+-1i"
Output: "0+-2i"
Explanation: (1 - i) * (1 - i) = 1 + i2 - 2 * i = -2i, and you need convert it to the form of 0+-2i.
```

**Note:**
1. The input strings will not have extra blank.
2. The input strings will be given in the form of **a+bi**, where the integer **a** and **b** will both belong to the range of [-100, 100]. And the **output should be also in this form**.

## Code
```
class Solution:
    def complexNumberMultiply(self, a: str, b: str) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/complex-number-multiplication/)

**Comment by sarthak55k** [comment]
May i do this?
I will do it in Python

**Comment by nl2412** [comment]
Hello. I can work on this. Can you assgin me this issue? Thanks ^^
