### ISSUE TITLE
0233 - Number of Digit One

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#151]
## Description of the Problem
Given an integer n, count the total number of digit 1 appearing in all non-negative integers less than or equal to n.

**Example:**
```
Input: 13
Output: 6 
Explanation: Digit 1 occurred in the following numbers: 1, 10, 11, 12, 13.
```

## Code
```
class Solution:
    def countDigitOne(self, n: int) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/number-of-digit-one/)

**Comment by sourabmaity** [comment]
i want to work in this issue
please assign me

**Comment by DhanushNehru** [comment]
Can I work this issue using Javascript ? If yes please assign this to me

**Comment by vJechsmayr** [comment]
@DHANUSHXENO no, this repo is Python only. You can contribute at my other [Repo](https://github.com/vJechsmayr/JavaScriptAlgorithms) and work it out at JavaScript if you like

**Comment by sourabmaity** [comment]
thank you

**Comment by DhanushNehru** [comment]
> @DHANUSHXENO no, this repo is Python only. You can contribute at my other [Repo](https://github.com/vJechsmayr/JavaScriptAlgorithms) and work it out at JavaScript if you like

Then fine. Can I do it in python ? If yes please assign it to me

**Comment by somkuwaryash** [comment]
Hey, I would like to work on this one. Please assign this to me.

**Comment by divyhshah** [comment]
Hey can you please assign this to me because i already done this just want need your permission to add pr

**Comment by vJechsmayr** [comment]
@DHANUSHXENO @divyhshah There is already @SOURAB-BAPPA  assigned to this issue. You may look for another one 😃

**Comment by DhanushNehru** [comment]
> @DHANUSHXENO @divyhshah There is already @SOURAB-BAPPA assigned to this issue. You may look for another one 😃

Ops, I solved it anyway. Thanks 😃

**Comment by sourabmaity** [comment]
closes #XXXX
