### ISSUE TITLE
0059 - Spiral Matrix II

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#163]
## Description of the Problem
Given a positive integer n, generate a square matrix filled with elements from 1 to n2 in spiral order.

**Example:**
```
Input: 3
Output:
[
 [ 1, 2, 3 ],
 [ 8, 9, 4 ],
 [ 7, 6, 5 ]
]
```

## Code
```
class Solution:
    def generateMatrix(self, n: int) -> List[List[int]]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/spiral-matrix-ii/)

**Comment by visheshruparelia** [comment]
@vJechsmayr  can I work on this?
