### ISSUE TITLE
0060 - Permutation Sequence

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#164]
## Description of the Problem
The set `[1,2,3,...,n]` contains a total of n! unique permutations.

By listing and labeling all of the permutations in order, we get the following sequence for n = 3:

1. `"123"`
2 `"132"`
3. `"213"`
4. `"231"`
5. `"312"`
6. `"321"`
Given _n_ and _k_, return the _k^th_ permutation sequence.

**Note:**
- Given _n_ will be between 1 and 9 inclusive.
- Given _k_ will be between 1 and _n_! inclusive.

**Example 1:**
```
Input: n = 3, k = 3
Output: "213"
```

**Example 2:**
```
Input: n = 4, k = 9
Output: "2314"
```

## Code
```
class Solution:
    def getPermutation(self, n: int, k: int) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/permutation-sequence/)

**Comment by sourabmaity** [comment]
i want to solve this

**Comment by sourabmaity** [comment]
program is done
