### ISSUE TITLE
0067 - Add Binary

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#167]
## Description of the Problem
Given two binary strings, return their sum (also a binary string).

The input strings are both **non-empty** and contains only characters `1` or` 0`.

**Example 1:**
```
Input: a = "11", b = "1"
Output: "100"
```

**Example 2:**
```
Input: a = "1010", b = "1011"
Output: "10101"
```

**Constraints:**
- Each string consists only of `'0'` or `'1'` characters.
- `1 <= a.length, b.length <= 10^4`
- Each string is either `"0"` or doesn't contain any leading zero.

## Code
```
class Solution:
    def addBinary(self, a: str, b: str) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/add-binary/)

**Comment by ashvinimore** [comment]
Can I work on this issue?
I know the algorithm.
Thank You

**Comment by ashvinimore** [comment]
Thank You Sir.

**Comment by vJechsmayr** [comment]
You are welcome, Milady 😹

**Comment by darshmgandhi** [comment]
@vJechsmayr Can you please assign this issue to me? I will give the python implementation to you.

**Comment by xooseph** [comment]
Hi @vJechsmayr! Can you assign me this issue please?

**Comment by Prajakta-collab** [comment]
Can you assign me this issue please ????
