### ISSUE TITLE
0069 - Sqrt(x)

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#168]
## Description of the Problem
Implement `int sqrt(int x)`.

Compute and return the square root of x, where x is guaranteed to be a non-negative integer.

Since the return type is an integer, the decimal digits are truncated and only the integer part of the result is returned.

**Example 1:**
```
Input: 4
Output: 2
```

**Example 2:**
```
Input: 8
Output: 2
Explanation: The square root of 8 is 2.82842..., and since 
             the decimal part is truncated, 2 is returned.
```

## Code
```
class Solution:
    def mySqrt(self, x: int) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/sqrtx/)

**Comment by pranjalkumar153** [comment]
Sir please assign this issue to me. I can cover it in C,C++, Python, Java and JavaScript.

**Comment by ashvinimore** [comment]
Can I work on this issue?
Thank You

**Comment by vJechsmayr** [comment]
@pranjalkumar153 Python only at this Repo please 😺

**Comment by pranjalkumar153** [comment]
Thank you Sir..

**Comment by vJechsmayr** [comment]
You're welcome, Milady 😹

**Comment by jcastle13** [comment]
Hello @vJechsmayr,

Was wondering if more than one person can be assigned an issue?  If so, I would like to work on this issue.  👍 

Regards,
Jason
