### ISSUE TITLE
0030 - Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#17]
## Substring with Concatenation of All Words
You are given a string `s` and an array of strings `words `of the **same length**. Return all starting indices of substring(s) in `s` that is a concatenation of each word in `words ` **exactly once, in any order,** and **without any intervening characters.**

You can return the answer in **any order**.

**Example 1:**
```
Input: s = "barfoothefoobarman", words = ["foo","bar"]
Output: [0,9]
Explanation: Substrings starting at index 0 and 9 are "barfoo" and "foobar" respectively.
The output order does not matter, returning [9,0] is fine too.
```

**Example 2:**
```
Input: s = "wordgoodgoodgoodbestword", words = ["word","good","best","word"]
Output: []
```

**Example 3:**
```
Input: s = "barfoofoobarthefoobarman", words = ["bar","foo","the"]
Output: [6,9,12]
```
 
**Constraints:**

- `1 <= s.length <= 104`
- `s` consists of lower-case English letters.
- `1 <= words.length <= 5000`
- `1 <= words[i].length <= 30`
- `words[i]` consists of lower-case English letters.

## Link To The LeetCode Problem
[LeetCode Problem 30](https://leetcode.com/problems/substring-with-concatenation-of-all-words/)

## Code
```
class Solution:
    def findSubstring(self, s: str, words: List[str]) -> List[int]:
        
```

**Comment by ExpressHermes** [comment]
@vJechsmayr  I would like to work on this issue

**Comment by ExpressHermes** [comment]
@vJechsmayr is it okay if I start this after October 1 so that it counts in my hacktoberfest PRs?

**Comment by vJechsmayr** [comment]
@ExpressHermes Sure. I also picked some for me for the Hacktoberfest 🤪 Happy Hacktoberfest

**Comment by ExpressHermes** [comment]
@vJechsmayr Thanks. Happy Hacktoberfest🎉🎈

**Comment by vJechsmayr** [comment]
@ExpressHermes Are you working on this? Otherwise I will unassign you

**Comment by ExpressHermes** [comment]
@vJechsmayr I am working on it. I will issue a PR ASAP.

**Comment by alvacat** [comment]
@vJechsmayr Can I work on this one?

**Comment by vJechsmayr** [comment]
> @vJechsmayr Can I work on this one?

@alvacat Go for it :)

**Comment by Achyut-sudo** [comment]
hey,@vJechsmayr  can you assign me ?? (only after @alvacat  ) 😄

**Comment by vJechsmayr** [comment]
@Achyut-sudo  if you still want to work on it - go ahead 😄

**Comment by Achyut-sudo** [comment]
hey , @vJechsmayr  thanks

**Comment by Achyut-sudo** [comment]
sorry, #791  failed somehow, I am working on its another version. was it due to longer execution time ???? ( i don't know .. earlier it got passed in leet code but now when I upload it onto leet code it failed there also due to the same, longer execution time.)

**Comment by Achyut-sudo** [comment]
hey @vJechsmayr I dunno 
![subsConcat](https://user-images.githubusercontent.com/71660666/97626310-a2bd8500-1a4f-11eb-8e3a-42f91cb7b193.jpg)
why my codes are failing (this the second iteration). even though my codes are passing through the leetCode tests with a runtime of  1424 ms, can you help me ?????

**Comment by Achyut-sudo** [comment]
do I need to make it more faster ????

**Comment by Achyut-sudo** [comment]
again it failed ! , dire need of help

**Comment by vJechsmayr** [comment]
> again it failed ! , dire need of help

@Achyut-sudo everything okay - Github Action broke 😄
