### ISSUE TITLE
0070 - Climbing Stairs

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#170]
## Description of the Problem
You are climbing a stair case. It takes _n_ steps to reach to the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

**Example 1:**
```
Input: 2
Output: 2
Explanation: There are two ways to climb to the top.
1. 1 step + 1 step
2. 2 steps
```

**Example 2:**
```
Input: 3
Output: 3
Explanation: There are three ways to climb to the top.
1. 1 step + 1 step + 1 step
2. 1 step + 2 steps
3. 2 steps + 1 step
```

**Constraints:**
- `1 <= n <= 45`

## Code
```
class Solution:
    def climbStairs(self, n: int) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/climbing-stairs/)

**Comment by TobyAsE** [comment]
I'd like to solve this problem

**Comment by shubhamnag14** [comment]
i would like to slove this proble..so can i

**Comment by jyotiGambhir** [comment]
Can you assign it to me? I would like to code in CPP
