### ISSUE TITLE
0074 - Search a 2D Matrix

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#173]
## Description of the Problem
Write an efficient algorithm that searches for a value in an _m x n_ matrix. This matrix has the following properties:

- Integers in each row are sorted from left to right.
- The first integer of each row is greater than the last integer of the previous row.

**Example 1:**
```
Input:
matrix = [
  [1,   3,  5,  7],
  [10, 11, 16, 20],
  [23, 30, 34, 50]
]
target = 3
Output: true
```

**Example 2:**
```
Input:
matrix = [
  [1,   3,  5,  7],
  [10, 11, 16, 20],
  [23, 30, 34, 50]
]
target = 13
Output: false
```

## Code
```
class Solution:
    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/search-a-2d-matrix/)

**Comment by ashvinimore** [comment]
Can You assign me the task?
Thank You

**Comment by DhawalKhapre** [comment]
I would like to contribute to this issue
Thank You

**Comment by ashvinimore** [comment]
Thank You Mam

**Comment by DhawalKhapre** [comment]
I would liketo solve this issue. Please assign this to me

**Comment by Curious-Ujjwal** [comment]
Can you assign me this task?
I would like to work on this.

**Comment by vJechsmayr** [comment]
@DhawalKhapre @Curious-Ujjwal If you want to work on it let me know
