### ISSUE TITLE
0076 - Minimum Window Substring

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#175]
## Description of the Problem
Given a string S and a string T, find the minimum window in S which will contain all the characters in T in complexity O(n).

**Example:**
```
Input: S = "ADOBECODEBANC", T = "ABC"
Output: "BANC"
```

**Note:**
- If there is no such window in S that covers all characters in T, return the empty string `""`.
- If there is such window, you are guaranteed that there will always be only one unique minimum window in S.

## Code
```
class Solution:
    def minWindow(self, s: str, t: str) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/minimum-window-substring/)

**Comment by capturemathan** [comment]
Can I solve this problem?

**Comment by suparna13** [comment]
@vJechsmayr  I would like to contribute on this. May i do this i will do it in python?
