### ISSUE TITLE
0077 - Combinations

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#176]
## Description of the Problem
Given two integers _n_ and _k_, return all possible combinations of _k_ numbers out of 1 ... _n_.

You may return the answer in **any order**.

**Example 1:**
```
Input: n = 4, k = 2
Output:
[
  [2,4],
  [3,4],
  [2,3],
  [1,2],
  [1,3],
  [1,4],
]
```

**Example 2:**
```
Input: n = 1, k = 1
Output: [[1]]
```

**Constraints:**
- `1 <= n <= 20`
- `1 <= k <= n`

## Code
```
class Solution:
    def combine(self, n: int, k: int) -> List[List[int]]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/combinations/)

**Comment by kamil200** [comment]
i would like to solve this problem . please assign me
