### ISSUE TITLE
0011 - Container With Most Water

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#178]
## Description of the Problem
Given _n_ non-negative integers _a1, a2, ..., an_ , where each represents a point at coordinate (_i, ai_). n vertical lines are drawn such that the two endpoints of line i is at (_i, ai_) and (_i, 0_). Find two lines, which together with x-axis forms a container, such that the container contains the most water.

**Note:** You may not slant the container and n is at least 2.

![image](https://user-images.githubusercontent.com/6342890/94929412-5a995a00-04c5-11eb-830f-35b9a239282f.png)
_The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49._

**Example:**
```
Input: [1,8,6,2,5,4,8,3,7]
Output: 49
```

## Code
```
class Solution:
    def maxArea(self, height: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/container-with-most-water/)

**Comment by sathiyajith** [comment]
I will work on it
