### ISSUE TITLE
0040 - Combination Sum II

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#18]
## Description of the Problem
Given a collection of candidate numbers (`candidates`) and a target number (`target`), find all unique combinations in `candidates `where the candidate numbers sums to `target`.

Each number in `candidates `may only be used **once** in the combination.

**Note:**
- All numbers (including `target`) will be positive integers.
- The solution set must not contain duplicate combinations.

**Example 1:**
```
Input: candidates = [10,1,2,7,6,1,5], target = 8,
A solution set is:
[
  [1, 7],
  [1, 2, 5],
  [2, 6],
  [1, 1, 6]
]
```

**Example 2:**
```
Input: candidates = [2,5,2,1,2], target = 5,
A solution set is:
[
  [1,2,2],
  [5]
]
```

## Link To The LeetCode Problem
[LeetCode problem 40](https://leetcode.com/problems/combination-sum-ii/)

**Comment by bislara** [comment]
@vJechsmayr  I would like to work on this. Can you please assign it to me?
