### ISSUE TITLE
0037 - Sudoku Solver

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#180]
## Description of the Problem
Write a program to solve a Sudoku puzzle by filling the empty cells.

A sudoku solution must satisfy **all of the following rules:**
1. Each of the digits `1-9` must occur exactly once in each row.
2. Each of the digits `1-9 `must occur exactly once in each column.
3. Each of the the digits `1-9` must occur exactly once in each of the 9 `3x3` sub-boxes of the grid.

Empty cells are indicated by the character `'.'`.

![image](https://user-images.githubusercontent.com/6342890/94929680-b532b600-04c5-11eb-9b00-8d6be6ed995b.png)

**Note:**
- The given board contain only digits `1-9` and the character` '.'`.
- You may assume that the given Sudoku puzzle will have a single unique solution.
- The given board size is always `9x9`.

## Code
```
class Solution:
    def solveSudoku(self, board: List[List[str]]) -> None:
        """
        Do not return anything, modify board in-place instead.
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/sudoku-solver/)

**Comment by Mohitbalwani26** [comment]
I would like to work on this issue.
