### ISSUE TITLE
0043 - Multiply Strings

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#19]
## Description of the Problem
Given two non-negative integers `num1 `and `num2 `represented as strings, return the product of `num1 `and `num2`, also represented as a string.

**Example 1:**
```
Input: num1 = "2", num2 = "3"
Output: "6"
```

**Example 2:**
```
Input: num1 = "123", num2 = "456"
Output: "56088"
```

**Note:**

1. The length of both `num1 `and `num2 `is < 110.
2. Both `num1 `and `num2 `contain only digits `0-9.`
3. Both `num1 `and `num2` do not contain any leading zero, except the number 0 itself.
4. You **must not use any built-in BigInteger library** or **convert the inputs to integer** directly.

## Link To The LeetCode Problem
[LeetCode Problem 43](https://leetcode.com/problems/multiply-strings/)

**Comment by VaibhaveS** [comment]
Hey can you assign me this issue? 
I have good experience with competitive programming as well [ rated 1900+ on codechef ]
