### ISSUE TITLE
0050 - Pow(x, n)

### ISSUE THREAD

**Issue by xma8lu** [vJechsmayr/PythonAlgorithms#215]
## Description of the Problem
Implement pow(x, n), which calculates x raised to the power n (i.e. xn).

## Code
```
Example 1:

Input: x = 2.00000, n = 10
Output: 1024.00000
Example 2:

Input: x = 2.10000, n = 3
Output: 9.26100
Example 3:

Input: x = 2.00000, n = -2
Output: 0.25000
Explanation: 2-2 = 1/22 = 1/4 = 0.25
 

Constraints:

-100.0 < x < 100.0
-231 <= n <= 231-1
-104 <= xn <= 104
```

## Link To The LeetCode Problem
https://leetcode.com/problems/powx-n/

**Comment by Hinal-Srivastava** [comment]
Yea! I'll do it👍

**Comment by xma8lu** [comment]
I wanted to work on this

**Comment by rishab05** [comment]
I will do it assign this to me. I solve this problem in leetcode

**Comment by VaibhavDS19** [comment]
I can solve this, please assign to me.

**Comment by cscipher** [comment]
I will work on it! Kindly assign me!

**Comment by vJechsmayr** [comment]
Problem 50 is already solved - closed
@aditya-gite-04 Please do not open Issues without checking if problem is already solved.
