### ISSUE TITLE
0002 -  Add Two Numbers

### ISSUE THREAD

**Issue by Aviadonis** [vJechsmayr/PythonAlgorithms#216]
## Description of the Problem
You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.

![image](https://user-images.githubusercontent.com/43524047/94996757-0b861e80-05c4-11eb-8ccc-6681b64faf6a.png)

## Examples
```
Input: l1 = [2,4,3], l2 = [5,6,4]
Output: [7,0,8]
Explanation: 342 + 465 = 807.
```
```
Input: l1 = [0], l2 = [0]
Output: [0]
```
```
Input: l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]
Output: [8,9,9,9,0,0,0,1]
```
## Link To The LeetCode Problem
[LeetCode - Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)

**Comment by Aviadonis** [comment]
Please assign this to me. ✔

**Comment by Jayanth19524** [comment]
can I work on this

**Comment by verma-pulkit** [comment]
Please assign this to me.

**Comment by VaibhavDS19** [comment]
Assign to me please.

**Comment by vJechsmayr** [comment]
Closed - Problem already solved! 
@Aviadonis Please check of Problem is solved before creating an issue!

**Comment by Aviadonis** [comment]
I'm sorry I'll be careful @vJechsmayr
