### ISSUE TITLE
0051 - N-Queens

### ISSUE THREAD

**Issue by pikachu28** [vJechsmayr/PythonAlgorithms#218]
The n-queens puzzle is the problem of placing n queens on an n×n chessboard such that no two queens attack each other.
Given an integer n, return all distinct solutions to the n-queens puzzle.

Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space respectively.
<img width="720" alt="Screenshot 2020-10-04 at 1 23 42 AM" src="https://user-images.githubusercontent.com/62153950/95000643-4ac26880-05e0-11eb-8a14-5f02be1ed783.png">

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/n-queens/)

**Comment by pikachu28** [comment]
Pls Assign this issue to me : )

**Comment by saranshkotnala** [comment]
can u assign this to me pls
