### ISSUE TITLE
04 - Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Mitali-laroia** [vJechsmayr/PythonAlgorithms#221]
## Median of Two Sorted Arrays
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

Follow up: The overall run time complexity should be O(log (m+n)).

Input: nums1 = [1,2], nums2 = [3,4]
Output: 2.50000
Explanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.

## Link To The LeetCode Problem
https://leetcode.com/problems/median-of-two-sorted-arrays/

**Comment by Mitali-laroia** [comment]
@vJechsmayr  Pls assign this issue to me.

**Comment by sourabmaity** [comment]
i want to solve this issue in C and python

**Comment by Luv8436** [comment]
Hii @Mitali-laroia  please assign this issue to me.

**Comment by Roshanpaswan** [comment]
Please assign me i will definately work on this issue

**Comment by Arihant416** [comment]
I would love to contribute to this problem if it hasn't been assigned.

**Comment by meghna25** [comment]
hey @Mitali-laroia can I implement this in Java?

**Comment by Sakshi2106** [comment]
I would like to contribute to this problem . Please assign this issue to me

**Comment by wasimafser** [comment]
why was this issue closed ?

**Comment by Mitali-laroia** [comment]
@wasimafser it is already there in code base.

**Comment by wasimafser** [comment]
ok, thank you for the information
