### ISSUE TITLE
0728 - Self Dividing Numbers

### ISSUE THREAD

**Issue by YashNagare** [vJechsmayr/PythonAlgorithms#222]
## Description of the Problem
A self-dividing number is a number that is divisible by every digit it contains.

## Code
```
Input:
left = 1, right = 22
Output: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 15, 22]
```
Explanation: Convert the number into a string, and then convert back to integer to perform the modulo operation when checking n % d == 0.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/self-dividing-numbers/)

**Comment by YashNagare** [comment]
Pls assign this issue to me.

**Comment by sbmkrgit** [comment]
Please assign this issue to me.
I can solve it easily.

**Comment by Arihant416** [comment]
Hi, I'd like to contribute a solution. Are there any specific guidelines to contribute to this issue?

**Comment by vighneshdeepweb** [comment]
pls assign this issue to me @YashNagare

**Comment by vighneshdeepweb** [comment]
#226

**Comment by vighneshdeepweb** [comment]
do review my PR #226

**Comment by PratikshaGoyal** [comment]
I would like to work on the issue

**Comment by DiveshHariani** [comment]
Can you please assign this issue to me?

**Comment by HOD101s** [comment]
I would like to propose my solution.
Leetcode Stats:
Runtime: 40 ms, faster than 93.23% of Python3 online submissions for Self Dividing Numbers.

**Comment by HOD101s** [comment]
I would like to propose my solution.
Leetcode Stats:
Runtime: 40 ms, faster than 93.23% of Python3 online submissions for Self Dividing Numbers.
#229

**Comment by HOD101s** [comment]
I would like to contribute my solution. Do assign the issue to me.
Leetcode Stats:
Runtime: 40 ms, faster than 93.23% of Python3 online submissions for Self Dividing Numbers.
#229

**Comment by Arihant416** [comment]
Do review my Pull Request, #224 
Leetcode Stats: Runtime 36ms, faster than 97.55% of Python Submissions :)

**Comment by ghost** [comment]
Hey! I can help you with this. Please assign it to me.

**Comment by HOD101s** [comment]
Extremely Pythonic Solution
LeetCode Stats:
Runtime: **32 ms**, **faster than 99.25%** of Python3 online submissions for Self Dividing Numbers.
Kindly assign the issue to me.
#247

**Comment by HOD101s** [comment]
Extremely Pythonic Solution
LeetCode Stats:
Runtime: **24 ms**, **faster than 100%** of Python3 online submissions for Self Dividing Numbers.
Kindly assign the issue to me.
#250 

![Screenshot](https://user-images.githubusercontent.com/37273226/95021609-9da72900-068f-11eb-9e88-1c082c04635a.png)

**Comment by abhishakvarshney** [comment]
Hey! I can help you with this. Please assign it to me.

**Comment by ghost** [comment]
I'd like to contribute a solution of this problem??
