### ISSUE TITLE
0009 - Palindrome Number

### ISSUE THREAD

**Issue by Hiroshii8** [vJechsmayr/PythonAlgorithms#230]
## Description of Problem
Determine whether an integer is a palindrome. An integer is a palindrome when it reads the same backward as forward.

Follow up: Could you solve it without converting the integer to a string?

## Example 1:
> Input: x = 121
> Output: true

## Example 2:
> Input: x = -121
> Output: false
> Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.

## Example 3: 
> Input: x = 10
> Output: false
## Example 4:
> Input: x = -101
> Output: false

## Constraints:
> -231 <= x <= 231 - 1

link : [problem](https://leetcode.com/problems/palindrome-number/)

**Comment by Hiroshii8** [comment]
please assign me to this issue sir @vJechsmayr

**Comment by Kushagra2000** [comment]
Could this be assigned to me?

**Comment by EishaMazhar** [comment]
Please assign this to me @vJechsmayr

**Comment by itsvinayak** [comment]
i have submitted a PR #239

**Comment by vJechsmayr** [comment]
@Hiroshii8 Please make sure to submit a PR within 7 Days - otherwise I will assign another assigne 👍

**Comment by itsvinayak** [comment]
Hey @vJechsmayr I have already submitted a PR related to this issue
