### ISSUE TITLE
0062 - Unique Paths

### ISSUE THREAD

**Issue by tanmoyee04** [vJechsmayr/PythonAlgorithms#233]
## Description of the Problem
A robot is located at the top-left corner of a m x n grid (marked 'Start' in the diagram below).

The robot can only move either down or right at any point in time. The robot is trying to reach the bottom-right corner of the grid (marked 'Finish' in the diagram below).

How many possible unique paths are there?

### Example :
Input: m = 3, n = 2
Output: 3
Explanation:
From the top-left corner, there are a total of 3 ways to reach the bottom-right corner:
1. Right -> Down -> Down
2. Down -> Down -> Right
3. Down -> Right -> Down

## Code

class Solution:
    def uniquePaths(self, m: int, n: int) -> int:
        return math.factorial(n+m-2)//(math.factorial(m-1)*math.factorial(n-1))

## Link To The LeetCode Problem
https://leetcode.com/problems/unique-paths/

**Comment by BassCoder2808** [comment]
I would like to work on this problem.
Can you please assign this issue to me ?

**Comment by anusharp97** [comment]
I would like to contribute to this, as I already have a python solution for the same in my github repo. 
Can you please assign this to me?

**Comment by vJechsmayr** [comment]
@tanmoyee04 Did you just open the Issue or do you want to be assigned too? 
If not I will assign another 😄

**Comment by tanmoyee04** [comment]
You can assign it to anyone you like

**Comment by tanmoyee04** [comment]
I have uploaded the problem and solution also.

**Comment by tanmoyee04** [comment]
I have made the PR for that but it wasn't allowing to create PR
