### ISSUE TITLE
0083 - Remove Duplicates from Sorted List

### ISSUE THREAD

**Issue by tanmoyee04** [vJechsmayr/PythonAlgorithms#237]
## Description of the Problem
Given a sorted linked list, delete all duplicates such that each element appear only once.

#### Example-1:
Input: 1->1->2
Output: 1->2
#### Example-2:
Input: 1->1->2->3->3
Output: 1->2->3

## Code
class Solution:
    def deleteDuplicates(self, head: ListNode) -> ListNode:
        if head==None:
            return head
        current= head.next
        prev=head
        while current!=None:
            if current.val==prev.val:
                prev.next=current.next
                current=current.next
            else:
                current=current.next
                prev=prev.next
        return head

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/remove-duplicates-from-sorted-list/)

**Comment by Mikhaylov-yv** [comment]
I'm ready to deal with this problem

**Comment by EishaMazhar** [comment]
Can you assign this to me?

**Comment by stoicfeats** [comment]
Hey, I have the solution ready waiting for assign and commit?
