### ISSUE TITLE
0073 - Set Matrix Zeroes

### ISSUE THREAD

**Issue by stoicfeats** [vJechsmayr/PythonAlgorithms#248]
## Description of the Problem
Given an m x n matrix. If an element is 0, set its entire row and column to 0. Do it in-place.

Follow up:

A straight forward solution using O(mn) space is probably a bad idea.
A simple improvement uses O(m + n) space, but still not the best solution.
Could you devise a constant space solution?
 

## Link To The LeetCode Problem
https://leetcode.com/problems/set-matrix-zeroes/

**Comment by stoicfeats** [comment]
I have the solution ready, please assign this to me. @vJechsmayr 
No one has done this question before neither any issues are open related to this.
thankyou

**Comment by busybee23** [comment]
#249

**Comment by busybee23** [comment]
#249

**Comment by busybee23** [comment]
[https://github.com/vJechsmayr/PythonAlgorithms/pull/249](url)
#249

**Comment by stoicfeats** [comment]
I'm trying to figure this out so badly.
