### ISSUE TITLE
0073 - Set Matrix Zeroes

### ISSUE THREAD

**Issue by stoicfeats** [vJechsmayr/PythonAlgorithms#253]
## Description of the Problem
Given an m x n matrix. If an element is 0, set its entire row and column to 0. Do it in-place.

Follow up:

A straight forward solution using O(mn) space is probably a bad idea.
A simple improvement uses O(m + n) space, but still not the best solution.
Could you devise a constant space solution?
 

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/set-matrix-zeroes/)

**Comment by busybee23** [comment]
linked a pull request that will close https://github.com/vJechsmayr/PythonAlgorithms/pull/255#issue-497467740

**Comment by stoicfeats** [comment]
I've linked the complete solution in two ways to solve this, please tag this as hacktoberfest. 
Thank you.
