### ISSUE TITLE
0081 - Search in Rotated Sorted Array II

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#26]
## Description of the Problem
Suppose an array sorted in ascending order is rotated at some pivot unknown to you beforehand.

(i.e., `[0,0,1,2,2,5,6]` might become `[2,5,6,0,0,1,2]`).

You are given a target value to search. If found in the array return true, otherwise return `false`.

**Example 1:**
```
Input: nums = [2,5,6,0,0,1,2], target = 0
Output: true

```
**Example 2:**
```
Input: nums = [2,5,6,0,0,1,2], target = 3
Output: false
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/search-in-rotated-sorted-array-ii/)

## Code
```
class Solution:
    def search(self, nums: List[int], target: int) -> bool:
        
```

**Comment by VaibhaveS** [comment]
Hey can you assign me this issue?
I have good experience with competitive programming as well [ rated 1900+ on codechef ]
