### ISSUE TITLE
0532 - K-diff Pairs in an Array

### ISSUE THREAD

**Issue by anuranjanpandey** [vJechsmayr/PythonAlgorithms#263]
## Description of the Problem
Given an array of integers nums and an integer k, return the number of unique k-diff pairs in the array.

A k-diff pair is an integer pair (nums[i], nums[j]), where the following are true:

+ 0 <= i, j < nums.length
+ i != j
+ a <= b
+ b - a == k

## Code
```
from collections import Counter
class Solution:
    def findPairs(self, nums: List[int], k: int) -> int:
        ans = 0
        c = Counter(nums)
        if k == 0:
            for val in c.values():
                if val > 1:
                    ans += 1
            return ans
        for i in c.keys():
            if i + k in c.keys():
                ans += 1
        return ans
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/k-diff-pairs-in-an-array/)

**Comment by anuranjanpandey** [comment]
Please assign this to me.

**Comment by vishalarya01** [comment]
Can you assign this problem to me. I will try in python.

**Comment by Anmol2001** [comment]
can i try in c++?

**Comment by vJechsmayr** [comment]
@Anmol2001 NO! Read Contributing Guidelines. This Repo is **Python3 only** - and there is already someone assigned to this issue
