### ISSUE TITLE
0995 - Minimum Number of K Consecutive Bit Flips

### ISSUE THREAD

**Issue by s-sanyal** [vJechsmayr/PythonAlgorithms#266]
## Description of the Problem
In an array A containing only 0s and 1s, a K-bit flip consists of choosing a (contiguous) subarray of length K and simultaneously changing every 0 in the subarray to 1, and every 1 in the subarray to 0.

Return the minimum number of K-bit flips required so that there is no 0 in the array.  If it is not possible, return -1.

Example 1:

Input: A = [0,1,0], K = 1
Output: 2
Explanation: Flip A[0], then flip A[2].

Example 2:

Input: A = [1,1,0], K = 2
Output: -1
Explanation: No matter how we flip subarrays of size 2, we can't make the array become [1,1,1].

Example 3:

Input: A = [0,0,0,1,0,1,1,0], K = 3
Output: 3
Explanation:
Flip A[0],A[1],A[2]: A becomes [1,1,1,1,0,1,1,0]
Flip A[4],A[5],A[6]: A becomes [1,1,1,1,1,0,0,0]
Flip A[5],A[6],A[7]: A becomes [1,1,1,1,1,1,1,1] 

Note:

    1 <= A.length <= 30000
    1 <= K <= A.length

## Code
```
class Solution:
    def minKBitFlips(self, A: List[int], K: int) -> int:
        n = len(A)
        flips = [0]*(n+1); ans = 0
        for i in range(n):
            flips[i] += flips[i-1] if i > 0 else 0
            
            if not A[i] ^ (flips[i]%2):
                if i + K - 1 >= n :
                    print(i, K)
                    return -1
                ans += 1
                flips[i] += 1
                flips[i+K] -= 1
        return ans
```

## Link To The LeetCode Problem
[ Minimum Number of K Consecutive Bit Flips](https://leetcode.com/problems/minimum-number-of-k-consecutive-bit-flips/)

**Comment by kra-tosss** [comment]
please assign this issue to me

**Comment by s-sanyal** [comment]
Please assign this issue to me. I am the one who solved it
