### ISSUE TITLE
0087 - Scramble String

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#27]
## Description of the Problem
We can scramble a string s to get a string t using the following algorithm:

1. If the length of the string is 1, stop.
2. If the length of the string is > 1, do the following:
- Split the string into 2 non-empty substrings at a random index, i.e. if the string is `s`, divide it to `x `and `y `where `s = x + y`.
- **Randomly**, decide to swap the two substrings or to keep them in the same order. i.e. after this step, s may become `s = x + y or s = y + x`.
- Apply step 1 recursively on each of the two substrings `x `and `y`.

Given two strings `s1 `and `s2 `of **the same length**, return `true `if `s2 `is a scrambled string of `s1`, otherwise, return `false`.

**Example 1:**
```
Input: s1 = "great", s2 = "rgeat"
Output: true
Explanation: One possible scenario applied on s1 is:
"great" --> "gr/eat" // divide at random index.
"gr/eat" --> "gr/eat" // random decision is not to swap the two substrings and keep them in order.
"gr/eat" --> "g/r / e/at" // apply the same algorith recursively on both substrings. divide at ranom index each of them.
"g/r / e/at" --> "r/g / e/at" // random decision was to swap the first substing and to keep the second substring in the same order.
"r/g / e/at" --> "r/g / e/ a/t" // again apply the algorithm recursively, divide "at" to "a/t".
"r/g / e/ a/t" --> "r/g / e/ a/t" // random decision is to keep both substings in the same order.
The algorithm stops now and the result string is "rgeat" which is s2.
As there is one possible scenario that led s1 to be scrambled to s2, we return true.
```

**Example 2:**
```
Input: s1 = "abcde", s2 = "caebd"
Output: false
```

**Example 3:**
```
Input: s1 = "a", s2 = "a"
Output: true
```
 
**Constraints:**
- `s1.length == s2.length`
- `1 <= s1.length <= 30`
- `s1 `and `s2` consist of lower-case English letters.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/scramble-string/)

## Code
```
class Solution:
    def isScramble(self, s1: str, s2: str) -> bool:
        
```

**Comment by officialpm** [comment]
##### @vJechsmayr I would like to work on this issue!!

**Comment by officialpm** [comment]
@vJechsmayr 
#### PR #50  
Added Solution for 0087- Scramble String 🤘🏻
Approach : Recursion + Memoization
Runtime: 32 ms
Memory Usage: 14.1 MB
