### ISSUE TITLE
0089 - Gray Code

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#28]
## Description of the Problem
The gray code is a binary numeral system where two successive values differ in only one bit.

Given a non-negative integer n representing the total number of bits in the code, print the sequence of gray code. A gray code sequence must begin with 0.

**Example 1:**
```
Input: 2
Output: [0,1,3,2]
Explanation:
00 - 0
01 - 1
11 - 3
10 - 2

For a given n, a gray code sequence may not be uniquely defined.
For example, [0,2,3,1] is also a valid gray code sequence.

00 - 0
10 - 2
11 - 3
01 - 1
```

**Example 2:**

```
Input: 0
Output: [0]
Explanation: We define the gray code sequence to begin with 0.
             A gray code sequence of n has size = 2n, which for n = 0 the size is 20 = 1.
             Therefore, for n = 0 the gray code sequence is [0].
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/gray-code/)

## Code
```
class Solution:
    def grayCode(self, n: int) -> List[int]:
        
```

**Comment by 27Anurag** [comment]
I've added a pr, please look into it. 
Regards.

**Comment by vJechsmayr** [comment]
@27Anurag there is no PR on this

**Comment by 27Anurag** [comment]
I committed only in my forked repo, now sent a PR, Please check again.

**Comment by yubarajsingh** [comment]
i would like to solve this problem
