### ISSUE TITLE
09- Palindrome Number

### ISSUE THREAD

**Issue by Curiouspaul1** [vJechsmayr/PythonAlgorithms#286]
## Description of the Problem
Determine whether an integer is a palindrome. An integer is a palindrome when it reads the same backward as forward.
## Code
```
class Solution:
    def isPalindrome(self, x: int) -> bool:
        """
        Checks to see if argument is a palindrome
        :param : int
        :returns : Bool
        """
        x = str(x)
        if x[::-1] == x:
            return True
        else:
            return False


main = Solution()

if __name__ == "__main__":
    print(main.isPalindrome(-101))
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/palindrome-number/)

**Comment by jmannina** [comment]
Hi, may I work on this?

**Comment by Curiouspaul1** [comment]
Hey i think the repo owner has to assign it to you specifically, I just need him to accept this as a valid issue for my hacktoberfest profile,

**Comment by ryanvarghese** [comment]
hey @Curiouspaul1 i would love to work on this . Can you please assign this to me ?

**Comment by vJechsmayr** [comment]
Closed - Problem already solved! Make Sure to **read Contribution Guideline** before creating an Issue!

**Comment by Curiouspaul1** [comment]
I'm confused when you say check to see if the problem hasn't been implemented do you mean to check whether abosolutely no one has written and submitted a soultion to the problem on leetcode?
