### ISSUE TITLE
0058 - Length of Last Word

### ISSUE THREAD

**Issue by wjyeap123** [vJechsmayr/PythonAlgorithms#289]
## Description of the Problem
Given a string s consists of upper/lower-case alphabets and empty space characters ' ', return the length of last word (last word means the last appearing word if we loop from left to right) in the string.

If the last word does not exist, return 0.

Note: A word is defined as a maximal substring consisting of non-space characters only.

## Code
```
class Solution:
    def lengthOfLastWord(self, s: str) -> int:
        s = s.strip()
        if not " " in s:
            if len(s) == 0:    
                return 0
            else: 
                return len(s)
        return len(s)-1-s.rindex(" ")
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/length-of-last-word/)

**Comment by wjyeap123** [comment]
Hi, this is my first contribution. Can you assign this issue to me?

**Comment by sayan1999** [comment]
I also want to work on this issue.

**Comment by mayankgoyal-13** [comment]
I would also like to work on the issue and do we have to create a code ?

**Comment by HariKrishnaShivs** [comment]
Hi,I want to work on this issue

**Comment by nbhanu1311** [comment]
class Solution {
public:
    int lengthOfLastWord(string s) {
        int len = s.length();
        int i = len - 1, j = 0;
        while(s[i] == ' '){
            i--;
        }
        while(i >=0 && ((s[i] >= 'a' && s[i] <= 'z') || (s[i] >= 'A' && s[i] <= 'Z'))){
            i--;
            j++;
        }
        return j;
    }
};

what about this solution..?
