### ISSUE TITLE
0134 - Gas Station

### ISSUE THREAD

**Issue by tejasbirsingh** [vJechsmayr/PythonAlgorithms#294]
## Description of the Problem
There are N gas stations along a circular route, where the amount of gas at station i is gas[i].

You have a car with an unlimited gas tank and it costs cost[i] of gas to travel from station i to its next station (i+1). You begin the journey with an empty tank at one of the gas stations.

Return the starting gas station's index if you can travel around the circuit once in the clockwise direction, otherwise return -1.

Note:

If there exists a solution, it is guaranteed to be unique.
Both input arrays are non-empty and have the same length.
Each element in the input arrays is a non-negative integer.

## Code
```
def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:
        n = len(gas)
        curr = 0
        total = 0
        start_idx = 0
        
        for i in range(n):
            curr += gas[i]-cost[i]
            total += gas[i]-cost[i]
            
            if curr < 0:
                start_idx = i+1
                curr = 0
                
        return start_idx if start_idx < n and total>=0 else -1
        
```

## Link To The LeetCode Problem
https://leetcode.com/problems/gas-station/

**Comment by tejasbirsingh** [comment]
I would like to contribute to the issue I created. Thanks!

**Comment by Achyut-sudo** [comment]
I would also like to work on this problem

**Comment by tejasbirsingh** [comment]
closes #XXXX

**Comment by Achyut-sudo** [comment]
hey I am very new to Github so by linking you mean I just have to write "issue- #316" to the commit comment before creating a pull request and also naming the branch "#316"
Thanks in advance!
