### ISSUE TITLE
0016 - 3Sum Closest

### ISSUE THREAD

**Issue by mansisahu127** [vJechsmayr/PythonAlgorithms#299]
**DESCRIPTION**
Given an array nums of n integers and an integer target, find three integers in nums such that the sum is closest to target. Return the sum of the three integers. You may assume that each input would have exactly one solution.

**LINK**
[https://leetcode.com/problems/3sum-closest/](url)

**Comment by TanayKulkarni** [comment]
can I work on This please!

**Comment by mansisahu127** [comment]
I am sorry. I created this issue by mistake. This problem has been already solved.
Sorry again.
