### ISSUE TITLE
0401 - Binary Watch

### ISSUE THREAD

**Issue by alifakbar111** [vJechsmayr/PythonAlgorithms#309]
## Description of the Problem
A binary watch has 4 LEDs on the top which represent the hours (0-11), and the 6 LEDs on the bottom represent the minutes (0-59).

Each LED represents a zero or one, with the least significant bit on the right.
For example, the above binary watch reads "3:25".

Given a non-negative integer n which represents the number of LEDs that are currently on, return all possible times the watch could represent.

## Code
```
class Solution:
    def readBinaryWatch(self, num: int):
        result = []
        for hours in range(12):
            for minutes in range(60):
                if bin(hours).count('1') + bin(minutes).count('1') == num:
                    result.append(str(hours) + ":" + str(minutes).zfill(2))
        return result
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/binary-watch/)

**Comment by alifakbar111** [comment]
Please assign this to me.

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)

**Comment by vJechsmayr** [comment]
@flick-23 There is still no PR from Issue-Creator(@alifakbar111): Feel Free to commit a PR

**Comment by flick-23** [comment]
> @flick-23 There is still no PR from Issue-Creator(@alifakbar111): Feel Free to commit a PR

Will do it in an hour
