### ISSUE TITLE
0058 - Length of Last Word

### ISSUE THREAD

**Issue by HOD101s** [vJechsmayr/PythonAlgorithms#318]
## Description of the Problem
Given a string s consists of upper/lower-case alphabets and empty space characters ' ', return the length of last word (last word means the last appearing word if we loop from left to right) in the string.

If the last word does not exist, return 0.

Note: A word is defined as a maximal substring consisting of non-space characters only.

### Explanation:
```
Input: "Hello World"
Output: 5
```

## Code
```
class Solution:
    def lengthOfLastWord(self, s: str) -> int:
        splits = s.split()
        if len(splits):
            return len(splits[-1])
        return 0
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/length-of-last-word/)

**Comment by HOD101s** [comment]
Kindly assign this to me as there have been no issues for this problem.

**Comment by HOD101s** [comment]
LeetCode Stats:
Runtime: 20 ms, faster than 98.88% of Python3 online submissions for Length of Last Word.

**Comment by HOD101s** [comment]
More optimized solution compared to the previously given solution at
#289

**Comment by vJechsmayr** [comment]
PR does not follow Contribution Guidelines - closed

Please make sure there is not already an Issue Open/Problem Solved (Code in Folder) with the ProblemNr you want to solve!
