### ISSUE TITLE
1046 - LeetCode Problem Title

### ISSUE THREAD

**Issue by PrachiSinghal86** [vJechsmayr/PythonAlgorithms#320]
## Description of the Problem
You may copy that from LeetCode
We have a collection of stones, each stone has a positive integer weight.

Each turn, we choose the two heaviest stones and smash them together.  Suppose the stones have weights x and y with x <= y.  The result of this smash is:

If x == y, both stones are totally destroyed;
If x != y, the stone of weight x is totally destroyed, and the stone of weight y has new weight y-x.
At the end, there is at most 1 stone left.  Return the weight of this stone (or 0 if there are no stones left.)
## Code
```
Code
```

## Link To The LeetCode Problem
https://leetcode.com/problems/last-stone-weight/

**Comment by IhebHaboubi** [comment]
Hi, can I work on this one ?

**Comment by PrachiSinghal86** [comment]
Please assign this to me
