### ISSUE TITLE
0090 - Subsets II

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#33]
## Description of the Problem
Given a collection of integers that might contain duplicates, **_nums_**, return all possible subsets (the power set).

**Note:** The solution set must not contain duplicate subsets.

**Example:**
```
Input: [1,2,2]
Output:
[
  [2],
  [1],
  [1,2,2],
  [2,2],
  [1,2],
  []
]
```

## Code
```
class Solution:
    def subsetsWithDup(self, nums: List[int]) -> List[List[int]]:
```     

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/subsets-ii/)

**Comment by Atheriz-46** [comment]
I would like to take this up
