### ISSUE TITLE
0022 - Generate Parentheses

### ISSUE THREAD

**Issue by c-utkarsh** [vJechsmayr/PythonAlgorithms#331]
## Description of the Problem
Given `n` pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

**Example 1:**
```
Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
```
**Example 2:**
```
Input: n = 1
Output: ["()"]
```
**Constraints:**
`1 <= n <= 8`

## Code
```
class Solution:
    def generateParenthesis(self, n: int) -> List[str]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/generate-parentheses/)

**Comment by c-utkarsh** [comment]
Hi @vJechsmayr, I would like to work on this.

**Comment by afeefaa333** [comment]
Shall I try this problem?
