### ISSUE TITLE
0013 - Roman to Integer 

### ISSUE THREAD

**Issue by anupamabauri** [vJechsmayr/PythonAlgorithms#333]
## Description of the Problem
Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.

Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
For example, 2 is written as II in Roman numeral, just two one's added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:

I can be placed before V (5) and X (10) to make 4 and 9. 
X can be placed before L (50) and C (100) to make 40 and 90. 
C can be placed before D (500) and M (1000) to make 400 and 900.
Given a roman numeral, convert it to an integer.

 

Example 1:

Input: s = "III"
Output: 3
Example 2:

Input: s = "IV"
Output: 4
Example 3:

Input: s = "IX"
Output: 9
Example 4:

Input: s = "LVIII"
Output: 58
Explanation: L = 50, V= 5, III = 3.
Example 5:

Input: s = "MCMXCIV"
Output: 1994
Explanation: M = 1000, CM = 900, XC = 90 and IV = 4.
 

Constraints:

1 <= s.length <= 15
s contains only the characters ('I', 'V', 'X', 'L', 'C', 'D', 'M').
It is guaranteed that s is a valid roman numeral in the range [1, 3999].

## Code
```
class Solution:
    def romanToInt(self, s: str) -> int:
        
        symbolValDict = {
            'I':1,
            'V':5,
            'X':10,
            'L':50,
            'C':100,
            'D':500,
            'M':1000
        }
        
        
        i = 0
        finalDigit = 0
        while(i<len(s)):
            firstDigit = symbolValDict[s[i]]
            if(i+1 < len(s)):
                nextDigit = symbolValDict[s[i+1]]
                if firstDigit >= nextDigit:
                    finalDigit += firstDigit
                    i+=1
                else:
                    finalDigit += nextDigit - firstDigit
                    i+=2
            else:
                finalDigit += firstDigit
                i+=1

            
        return finalDigit
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/roman-to-integer)

**Comment by anupamabauri** [comment]
Please assign this issue to me. I would like to work on this

**Comment by nikhil05-code** [comment]
Please assign it to me.

**Comment by prackode** [comment]
Please assign this issue to me.
