### ISSUE TITLE
0347 - Top K Frequent Elements

### ISSUE THREAD

**Issue by stoicfeats** [vJechsmayr/PythonAlgorithms#338]
## Description of the Problem
Given a non-empty array of integers, return the k most frequent elements.

Example 1:

Input: nums = [1,1,1,2,2,3], k = 2
Output: [1,2]
Example 2:

Input: nums = [1], k = 1
Output: [1]
Note:

You may assume k is always valid, 1 ≤ k ≤ number of unique elements.
Your algorithm's time complexity must be better than O(n log n), where n is the array's size.
It's guaranteed that the answer is unique, in other words, the set of the top k frequent elements is unique.
You can return the answer in any order.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/top-k-frequent-elements/)

**Comment by kajal1122** [comment]
assign it to me

**Comment by stoicfeats** [comment]
#339 closes this issue.

**Comment by stoicfeats** [comment]
> assign it to me

You should try creating your own issue first then link a PR to it, chances will be higher 👍🏽 
Thank you.
