### ISSUE TITLE
0120 - Triangle

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#34]
## Description of the Problem
Given a triangle, find the minimum path sum from top to bottom. Each step you may move to adjacent numbers on the row below.

For example, given the following triangle
```
[
     [2],
    [3,4],
   [6,5,7],
  [4,1,8,3]
]
```

The minimum path sum from top to bottom is `11 `(i.e., **2 + 3 + 5 + 1 = 11**).

**Note:**
Bonus point if you are able to do this using only O(n) extra space, where n is the total number of rows in the triangle.

## Code
```
class Solution:
    def minimumTotal(self, triangle: List[List[int]]) -> int:
```
        
## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/triangle/)

**Comment by RSMuthu** [comment]
Hi,
I shall work on this.
