### ISSUE TITLE
1592 - Rearrange Spaces Between Words

### ISSUE THREAD

**Issue by wanda15tw** [vJechsmayr/PythonAlgorithms#340]
## Description of the Problem
You are given a string text of words that are placed among some number of spaces. Each word consists of one or more lowercase English letters and are separated by at least one space. It's guaranteed that text contains at least one word.

Rearrange the spaces so that there is an equal number of spaces between every pair of adjacent words and that number is maximized. If you cannot redistribute all the spaces equally, place the extra spaces at the end, meaning the returned string should be the same length as text.

Return the string after rearranging the spaces.
## Code
```
class Solution:
    def reorderSpaces(self, text: str) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/rearrange-spaces-between-words)

**Comment by shivangigoel1302** [comment]
Can you assign this to me. I would like to do it in C++

**Comment by wanda15tw** [comment]
Please assign this issue to me @vJechsmayr
