### ISSUE TITLE
1464 - Maximum Product of Two Elements in an Array

### ISSUE THREAD

**Issue by wanda15tw** [vJechsmayr/PythonAlgorithms#342]
## Description of the Problem
Given the array of integers nums, you will choose two different indices `i` and `j` of that array. Return the maximum value of `(nums[i]-1)*(nums[j]-1)`.

## Code
```
class Solution:
    def maxProduct(self, nums: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/maximum-product-of-two-elements-in-an-array/)

**Comment by BassCoder2808** [comment]
Can you assign this issue to me ?

**Comment by wanda15tw** [comment]
Please assign this issue to me @vJechsmayr

**Comment by DhawalKhapre** [comment]
I would like to solve this problem
