### ISSUE TITLE
1380 -  Lucky Numbers in a Matrix

### ISSUE THREAD

**Issue by ishika161** [vJechsmayr/PythonAlgorithms#348]
## Description of the Problem
Given a m * n matrix of distinct numbers, return all lucky numbers in the matrix in any order.

A lucky number is an element of the matrix such that it is the minimum element in its row and maximum in its column.

 

Example 1:

Input: matrix = [[3,7,8],[9,11,13],[15,16,17]]
Output: [15]
Explanation: 15 is the only lucky number since it is the minimum in its row and the maximum in its column

## Code
```
class Solution:
    def luckyNumbers (self, matrix: List[List[int]]) -> List[int]:
        min_n = {min(rows) for rows in matrix}
        max_n = {max(columns) for columns in zip(*matrix)} 
        
        return list(min_n & max_n)

```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/lucky-numbers-in-a-matrix/)

**Comment by ishika161** [comment]
Please assign me this issue @vJechsmayr

**Comment by PriyanshTri** [comment]
assign this to me. thanks
