### ISSUE TITLE
0126 - Word Ladder II

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#35]
## Description of the Problem
Given two words (_beginWord_ and _endWord_), and a dictionary's word list, find all shortest transformation sequence(s) from beginWord to endWord, such that:

1. Only one letter can be changed at a time
2. Each transformed word must exist in the word list. Note that beginWord is not a transformed word.

**Note:**
- Return an empty list if there is no such transformation sequence.
- All words have the same length.
- All words contain only lowercase alphabetic characters.
- You may assume no duplicates in the word list.
- You may assume beginWord and endWord are non-empty and are not the same.

**Example 1:**
```
Input:
beginWord = "hit",
endWord = "cog",
wordList = ["hot","dot","dog","lot","log","cog"]

Output:
[
  ["hit","hot","dot","dog","cog"],
  ["hit","hot","lot","log","cog"]
]
```

**Example 2:**
```
Input:
beginWord = "hit"
endWord = "cog"
wordList = ["hot","dot","dog","lot","log"]

Output: []

Explanation: The endWord "cog" is not in wordList, therefore no possible transformation.
```

## Code
```
class Solution:
    def findLadders(self, beginWord: str, endWord: str, wordList: List[str]) -> List[List[str]]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/word-ladder-ii/)

**Comment by Apoorve73** [comment]
I would like to solve this. Can you please assign this?

**Comment by DhawalKhapre** [comment]
I will solve this issue. Please assign this to me

**Comment by vJechsmayr** [comment]
7 day inactivity - assigned @DhawalKhapre
