### ISSUE TITLE
1374-Generate a String With Characters That Have Odd Counts

### ISSUE THREAD

**Issue by ishika161** [vJechsmayr/PythonAlgorithms#353]
## Description of the Problem
Given an integer n, return a string with n characters such that each character in such string occurs an odd number of times.

The returned string must contain only lowercase English letters. If there are multiples valid strings, return any of them.  

 

Example 1:

Input: n = 4
Output: "pppz"
Explanation: "pppz" is a valid string since the character 'p' occurs three times and the character 'z' occurs once. Note that there are many other valid strings such as "ohhh" and "love".

## Code
```
class Solution:
    def generateTheString(self, n: int) -> str:
 
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/generate-a-string-with-characters-that-have-odd-counts/)

**Comment by ishika161** [comment]
Please assign this issue to me @vJechsmayr

**Comment by AryashDubey** [comment]
Please Assign It To me!
