### ISSUE TITLE
0125 - Valid Palindrome

### ISSUE THREAD

**Issue by afeefaa333** [vJechsmayr/PythonAlgorithms#354]
## Description of the Problem
Given a string, determine if it is a palindrome, considering only alphanumeric characters and ignoring cases.

Note: For the purpose of this problem, we define empty string as valid palindrome.

Example 1:

Input: "A man, a plan, a canal: Panama"
Output: true
Example 2:

Input: "race a car"
Output: false

## Code
```
class Solution:
    def isPalindrome(self, s: str) -> bool:
      alphnum = ""
      #Extract only alphanumeric characters from the given string
      for i in s:
         #Check if the character is a lowercase letter or a number
         if ord(i)>=ord('a') and ord(i)<=ord('z') or ord(i)>=ord("0") and ord(i)<=ord("9"):
            alphnum+=i
         #Check if the character is an uppercase letter 
         #If yes,convert to lower case
         elif ord(i)>=ord('A') and ord(i)<=ord('Z'):
            i = chr(32+ord(i))
            alphnum+=i
      #Reverse the alphanumeric string and check whether it is a palindrome
      rev= alphnum[::-1]
      result= rev==alphnum
      return result
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/valid-palindrome/)

**Comment by afeefaa333** [comment]
Please assign this to me, I can solve this

**Comment by ajyan** [comment]
Hi, I'd like to take this as an issue!

**Comment by haard19** [comment]
I have submitted the solution and have performed all the checks for opening PR: https://github.com/vJechsmayr/PythonAlgorithms/pull/362 
Kindly review and merge.
