### ISSUE TITLE
0048 - Rotate Image

### ISSUE THREAD

**Issue by anupamabauri** [vJechsmayr/PythonAlgorithms#355]
## Description of the Problem

You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

 

Example 1:

Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [[7,4,1],[8,5,2],[9,6,3]]
Example 2:

Input: matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
Output: [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]
Example 3:

Input: matrix = [[1]]
Output: [[1]]
Example 4:

Input: matrix = [[1,2],[3,4]]
Output: [[3,1],[4,2]]
 

Constraints:

matrix.length == n
matrix[i].length == n
1 <= n <= 20
-1000 <= matrix[i][j] <= 1000

## Code
```
class Solution:
    def rotate(self, matrix: List[List[int]]) -> None:
        """
        Do not return anything, modify matrix in-place instead.
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/rotate-image/)

**Comment by anupamabauri** [comment]
Please assign this issue to me

**Comment by HarlockOfficial** [comment]
please assign this issue to me

**Comment by Curious-Ujjwal** [comment]
Please assign this issue to me, if it is yet open.

**Comment by anupamabauri** [comment]
@vJechsmayr  Can u assign it to @Curious-Ujjwal 
I will unassign myself.

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)
