### ISSUE TITLE
1323## - Maximum 69 Number

### ISSUE THREAD

**Issue by Eliran-Turgeman** [vJechsmayr/PythonAlgorithms#356]
## Description of the Problem
Given a positive integer num consisting only of digits 6 and 9.

Return the maximum number you can get by changing at most one digit (6 becomes 9, and 9 becomes 6).

 

Example 1:

Input: num = 9669
Output: 9969
Explanation: 
Changing the first digit results in 6669.
Changing the second digit results in 9969.
Changing the third digit results in 9699.
Changing the fourth digit results in 9666. 
The maximum number is 9969.
Example 2:

Input: num = 9996
Output: 9999
Explanation: Changing the last digit 6 to 9 results in the maximum number.
Example 3:

Input: num = 9999
Output: 9999
Explanation: It is better not to apply any change.
 

Constraints:

1 <= num <= 10^4
num's digits are 6 or 9.

## Code
```
class Solution:
    def maximum69Number (self, num: int) -> int:
        num_arr = [digit for digit in str(num)]
        try:
            num_arr[num_arr.index('6')] = '9'
        except ValueError:
            pass
        return int(''.join(num_arr))
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/maximum-69-number/)

**Comment by Harsh-Udai** [comment]
@DevEliran  can you assign me this

**Comment by HarlockOfficial** [comment]
@DevEliran can you assign this to me please?

**Comment by sanujana045** [comment]
I want to do this

**Comment by vJechsmayr** [comment]
@DevEliran Do you work on that Issue on your own?

**Comment by Sounakde** [comment]
@DevEliran Can you assign me to this issue?

**Comment by Eliran-Turgeman** [comment]
@vJechsmayr Yes, I would like to

**Comment by bhartish** [comment]
@DevEliran  please assign this problem to me.

**Comment by Shivansh-Malhotra** [comment]
@DevEliran i think i can solve it, please assign this to me.

**Comment by Curious-Ujjwal** [comment]
Hey @vJechsmayr , I think I can solve this issue. Can you assign it to me, if it is open.

**Comment by flick-23** [comment]
Please assign this to me. I will do it!
