### ISSUE TITLE
Create 1568_Python_Program_To_Split_And_Join_A_String.py

### ISSUE THREAD

**Issue by Swatigupta-droid** [vJechsmayr/PythonAlgorithms#360]
# CODE
def split_string(string): 
    list_string = string.split(' ') 
    return list_string 
def join_string(list_string): 
    string = '-'.join(list_string) 
    return string 
if __name__ == '__main__': 
    string = 'coding is awesome'
    list_string = split_string(string) 
    print(list_string)
    new_string = join_string(list_string) 
    print(new_string)

**Comment by RadientBrain** [comment]
please assign this to me @Swatigupta-droid

**Comment by geekyvedic** [comment]
@Swatigupta-droid  why is "**if name == 'main':**" used

**Comment by RadientBrain** [comment]
> @Swatigupta-droid why is "**if name == 'main':**" used




@geekyvedic hope you will understand it:

## <code>  if \_\_name\_\_ == '\_\_main\_\_' </code>

* It actually tells the python interpreter to check whether the current python code is called by another file or not.
If it is called by another file then the code below this line will not be executed, else it will.

**Comment by RadientBrain** [comment]
@Swatigupta-droid and @vJechsmayr, I have made the PR numbered #365 which resolves this issue.
please merge it and close this issue!

**Comment by Swatigupta-droid** [comment]
@RadientBrain it means if the module runs in main program the variable name will be considered as main,
And if import module from some other module, it will set to name of the module it is being imported.
Modules are the python files

**Comment by RadientBrain** [comment]
> > @Swatigupta-droid why is "**if name == 'main':**" used
> 
> @geekyvedic hope you will understand it:
> 
> ## ` if __name__ == '__main__' `
> * It actually tells the python interpreter to check whether the current python code is called by another file or not.
>   If it is called by another file then the code below this line will not be executed, else it will.

@Swatigupta-droid  I think that what I explained was just the same as your explanation but in simpler words. But yes if @geekyvedic  was searching for a more precise definition then your definition is much more precise than mine.

(Hoping to get PR no. #365 to be merged soon 😃 )

**Comment by vJechsmayr** [comment]
Issue Closed - @Swatigupta-droid Please use the Issue-Template I Created when you create a new Issue!
