### ISSUE TITLE
0047 - Permutations II

### ISSUE THREAD

**Issue by anupamabauri** [vJechsmayr/PythonAlgorithms#363]
## Description of the Problem
Given a collection of numbers that might contain duplicates, return all possible unique permutations.

Example:

Input: [1,1,2]
Output:
[
  [1,1,2],
  [1,2,1],
  [2,1,1]
]

## Code
```
class Solution:
    def permuteUnique(self, nums: List[int]) -> List[List[int]]:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/permutations-ii/)

**Comment by anupamabauri** [comment]
Please assign this issue to me

**Comment by Mrsterius** [comment]
I would like to solve this issue using recursion. Please assign if it seems fit.
