### ISSUE TITLE
0036 - Valid Sudoku

### ISSUE THREAD

**Issue by Swarn10** [vJechsmayr/PythonAlgorithms#367]
## Description of the Problem
Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules:

- Each row must contain the digits 1-9 without repetition.
- Each column must contain the digits 1-9 without repetition.
- Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.

Note:
- A Sudoku board (partially filled) could be valid but is not necessarily solvable.
- Only the filled cells need to be validated according to the mentioned rules.

## Example 1 
```
Input: board = 
[["5","3",".",".","7",".",".",".","."]
,["6",".",".","1","9","5",".",".","."]
,[".","9","8",".",".",".",".","6","."]
,["8",".",".",".","6",".",".",".","3"]
,["4",".",".","8",".","3",".",".","1"]
,["7",".",".",".","2",".",".",".","6"]
,[".","6",".",".",".",".","2","8","."]
,[".",".",".","4","1","9",".",".","5"]
,[".",".",".",".","8",".",".","7","9"]]
Output: true
``` 
## Example 2 
```
Input: board = 
[["8","3",".",".","7",".",".",".","."]
,["6",".",".","1","9","5",".",".","."]
,[".","9","8",".",".",".",".","6","."]
,["8",".",".",".","6",".",".",".","3"]
,["4",".",".","8",".","3",".",".","1"]
,["7",".",".",".","2",".",".",".","6"]
,[".","6",".",".",".",".","2","8","."]
,[".",".",".","4","1","9",".",".","5"]
,[".",".",".",".","8",".",".","7","9"]]
Output: false
Explanation: Same as Example 1, except with the 5 in the top left corner being modified to 8. Since there are two 8's in the top left 3x3 sub-box, it is invalid.
```
## Code
```
class Solution:
    def isValidSudoku(self, board: List[List[str]]) -> bool:
```

## Link To The LeetCode Problem
[Valid Sudoku](https://leetcode.com/problems/valid-sudoku/)

**Comment by Swarn10** [comment]
@vJechsmayr Please assign this issue to me. Will be happy to contribute.

**Comment by Dave-Browne** [comment]
@vJechsmayr Happy to give a python solution to. Big fan of Sudoku.

**Comment by Kishore-abhimanyu** [comment]
I like to work on this.Could you please assign me on this?

**Comment by vJechsmayr** [comment]
@Dave-Browne @Kishore-abhimanyu The Creator of the Issue will be prefered to assignment
