### ISSUE TITLE
1480 - Running Sum of 1d Array

### ISSUE THREAD

**Issue by Vineet-Dhaimodker** [vJechsmayr/PythonAlgorithms#368]
## Description of the Problem
Given an array nums. We define a running sum of an array as runningSum[i] = sum(nums[0]…nums[i]).

Return the running sum of nums.

## Example 1:
```
Input: nums = [1,2,3,4]
Output: [1,3,6,10]
Explanation: Running sum is obtained as follows: [1, 1+2, 1+2+3, 1+2+3+4].
```
## Example 2:
```
Input: nums = [1,1,1,1,1]
Output: [1,2,3,4,5]
Explanation: Running sum is obtained as follows: [1, 1+1, 1+1+1, 1+1+1+1, 1+1+1+1+1].
```
## Example 3:
```
Input: nums = [3,1,2,10,1]
Output: [3,4,6,16,17]
```
## Code
```
class Solution:
    def runningSum(self, nums: List[int]) -> List[int]:
```

## Link To The LeetCode Problem
[Running Sum of 1d Array](https://leetcode.com/problems/running-sum-of-1d-array/)

**Comment by Vineet-Dhaimodker** [comment]
@vJechsmayr Please assign this issue to me. I am happy to contribute.

**Comment by AldoTu** [comment]
Hi @Vineet-Dhaimodker, @vJechsmayr , uploaded PR #371 as a solution. 👍🏻

**Comment by Vineet-Dhaimodker** [comment]
@AldoTu I think you need to be assigned to an issue before uploading a PR. Clearly mentioned in the Contributing guidelines.

**Comment by AldoTu** [comment]
@Vineet-Dhaimodker you are right... I missed that file :( just saw it.

**Comment by AryashDubey** [comment]
I can do it Please Assign me!

**Comment by vJechsmayr** [comment]
@AldoTu @AryashDubey Please consider Contribution Guidelines - The one who Created an Issue will prefered be assigned to the issue

**Comment by Vaibhhav7860** [comment]
@Vineet-Dhaimodker Sir please assign this issue to me . I can easily contribute to it.

**Comment by Vineet-Dhaimodker** [comment]
#400

**Comment by Shivansh-Malhotra** [comment]
@vJechsmayr please it to me.
