### ISSUE TITLE
0561 - Array Partition I

### ISSUE THREAD

**Issue by stevehan00** [vJechsmayr/PythonAlgorithms#369]
## Description of the Problem
First, given array is sorted. And the sum was obtained by increasing the index of the array by two. That is sum of min(ai, bi) at problem.

## Code
```
class Solution:
    def arrayPairSum(self, nums: List[int]) -> int:
        return sum(sorted(nums)[::2])
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/array-partition-i/)

**Comment by stevehan00** [comment]
Please assign this issue to me

**Comment by Vineet-Dhaimodker** [comment]
@h5jam How did you link the PR that closes this issue?

**Comment by stevehan00** [comment]
If you enter the '#' key in your PR write, you'll see drop menu. Then, Enter your issue nubmer like this -> #368

**Comment by Vineet-Dhaimodker** [comment]
> If you enter the '#' key in your PR write, you'll see drop menu. Then, Enter your issue nubmer like this -> #368

Thanks a lot!
