### ISSUE TITLE
1002 - Find Common Characters

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#37]
## Description of the Problem
Given an array `A `of strings made only from lowercase letters, return a list of all characters that show up in all strings within the list (**including duplicates**).  For example, if a character occurs 3 times in all strings but not 4 times, you need to include that character three times in the final answer.

You may return the answer in any order.

**Example 1:**
```
Input: ["bella","label","roller"]
Output: ["e","l","l"]
```

**Example 2:**
```
Input: ["cool","lock","cook"]
Output: ["c","o"]
```
 
**Note:**
1. `1 <= A.length <= 100`
2. `1 <= A[i].length <= 100`
3. `A[i][j]` is a lowercase letter

## Code
```
class Solution:
    def commonChars(self, A: List[str]) -> List[str]:
```
        
## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/find-common-characters/)

**Comment by kandasamyc** [comment]
Can I work on this?

**Comment by vJechsmayr** [comment]
@SamC302 sure, go ahead 😄
