### ISSUE TITLE
0268 - Missing Number

### ISSUE THREAD

**Issue by AkshatBhat** [vJechsmayr/PythonAlgorithms#373]
## Description of the Problem
Given an array nums containing n distinct numbers in the range [0, n], return the only number in the range that is missing from the array.

**Follow up:** Could you implement a solution using only O(1) extra space complexity and O(n) runtime complexity?

## Example 1
```
Input: nums = [3,0,1]
Output: 2
Explanation: n = 3 since there are 3 numbers, so all numbers are in the range [0,3]. 2 is the missing number in the range since it does not appear in nums.
```

## Example 2
```
Input: nums = [0,1]
Output: 2
Explanation: n = 2 since there are 2 numbers, so all numbers are in the range [0,2]. 2 is the missing number in the range since it does not appear in nums.
```

## Example 3
```
Input: nums = [9,6,4,2,3,5,7,0,1]
Output: 8
Explanation: n = 9 since there are 9 numbers, so all numbers are in the range [0,9]. 8 is the missing number in the range since it does not appear in nums.
```

## Example 4
```
Input: nums = [0]
Output: 1
Explanation: n = 1 since there is 1 number, so all numbers are in the range [0,1]. 1 is the missing number in the range since it does not appear in nums.
```

## Constraints
```
- n == nums.length
- 1 <= n <= 104
- 0 <= nums[i] <= n
- All the numbers of nums are unique.
```

## Code
```
class Solution:
    def missingNumber(self, nums: List[int]) -> int:
```

## Link To The LeetCode Problem
[Missing Number](https://leetcode.com/problems/missing-number/)

**Comment by AkshatBhat** [comment]
@vJechsmayr Please assign this issue to me. I am happy to contribute.

**Comment by AryashDubey** [comment]
Please Assign It To Me .I will make it A.S.A.P

**Comment by preety311** [comment]
Please assign this to me

**Comment by ghost** [comment]
Hey! I would like to work on this problem. Please assign it to me.

**Comment by khushi2031** [comment]
def printRepeating(arr, size): 
      
    print("The repeating elements are: ") 
      
    for i in range(0, size): 
          
        if arr[abs(arr[i])] >= 0: 
            arr[abs(arr[i])] = -arr[abs(arr[i])] 
        else: 
            print (abs(arr[i]), end = " ") 
              
# Driver code 
arr = [1, 2, 3, 1, 3, 6, 6] 
arr_size = len(arr) 
  
printRepeating(arr, arr_size) 
  # @

**Comment by ghost** [comment]
Hi,Can I Contribute on this?
