### ISSUE TITLE
0414 - Third Maximum Number

### ISSUE THREAD

**Issue by riwim** [vJechsmayr/PythonAlgorithms#374]
## Description of the Problem
Given a **non-empty** array of integers, return the **third** maximum number in this array. If it does not exist, return the maximum number. The time complexity must be in O(n).

### Example 1

```
Input: [3, 2, 1]

Output: 1

Explanation: The third maximum is 1.
```

### Example 2

```
Input: [1, 2]

Output: 2

Explanation: The third maximum does not exist, so the maximum (2) is returned instead.
```

### Example 3

```
Input: [2, 2, 3, 1]

Output: 1

Explanation: Note that the third maximum here means the third maximum distinct number.
Both numbers with value 2 are both considered as second maximum.
```

## Code

```python
class Solution:
    def thirdMax(self, nums: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode 414](https://leetcode.com/problems/third-maximum-number/)

**Comment by AryashDubey** [comment]
Please Assign It To me!

**Comment by A7med650** [comment]
Please Assign It To me!
