### ISSUE TITLE
0016 - 3Sum Closest

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#38]
## Description of the Problem
Given an array `nums `of n integers and an integer `target`, find three integers in `nums `such that the sum is closest to `target`. Return the sum of the three integers. You may assume that each input would have exactly one solution.

**Example 1:**
```
Input: nums = [-1,2,1,-4], target = 1
Output: 2
Explanation: The sum that is closest to the target is 2. (-1 + 2 + 1 = 2).
```
 
**Constraints:**
- `3 <= nums.length <= 10^3`
- `-10^3 <= nums[i] <= 10^3`
- `-10^4 <= target <= 10^4`

## Code
```
class Solution:
    def threeSumClosest(self, nums: List[int], target: int) -> int:
```
        
## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/3sum-closest/)

**Comment by BALaka-18** [comment]
@vJechsmayr can I work on this issue ?
