### ISSUE TITLE
0104 - Maximum Depth of Binary Tree

### ISSUE THREAD

**Issue by nivalderramas** [vJechsmayr/PythonAlgorithms#382]
## Description of the Problem
Given a binary tree, find its maximum depth.

The maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.

Note: A leaf is a node with no children.

Example:

Given binary tree [3,9,20,null,null,15,7],
return its depth = 3.
## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/maximum-depth-of-binary-tree/)

**Comment by nivalderramas** [comment]
Can I work on this one?

**Comment by Suyyashaa** [comment]
Can I work on this?

**Comment by abhishekpatel946** [comment]
Hey @ExpectoPatrom,

Can I work on this problem?

**Comment by PravunathSingh** [comment]
Hey, @ExpectoPatrom can I work on this issue?

**Comment by gaurangisinha** [comment]
Hello, @ExpectoPatrom Can I work on this? Please assign it to me, I will be grateful as this is my first time in open source.
