### ISSUE TITLE
0123 - Best Time to Buy and Sell Stock III

### ISSUE THREAD

**Issue by TobiSan5** [vJechsmayr/PythonAlgorithms#383]
## Description of the Problem
Say you have an array for which the ith element is the price of a given stock on day i.

Design an algorithm to find the maximum profit. You may complete at most two transactions.

Note: You may not engage in multiple transactions at the same time (i.e., you must sell the stock before you buy again).

## Code
```
class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        max_profit = 0
        pass
        return max_profit
```

## Link To The LeetCode Problem
[LeetCode 123](https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/)

**Comment by Deepak2417** [comment]
Please assign it to me.

**Comment by Sayantan-world** [comment]
Hey, I want to write a code in C++ can you assign it to me?

**Comment by PravunathSingh** [comment]
Hey, @TobiSan5 can you please assign this issue to me. This problem seems interesting and I would like to work on it.

**Comment by IamAbhiKaushik** [comment]
Hey @TobiSan5, Can I do this task?

**Comment by vJechsmayr** [comment]
@TobiSan5 Do you work on that issue on your own?

@Sayantan-world NO, this Repo is **Python** only!

**Comment by TobiSan5** [comment]
> @TobiSan5 Do you work on that issue on your own?

Yes, I've got a solution.

**Comment by vJechsmayr** [comment]
> > @TobiSan5 Do you work on that issue on your own?
> 
> Yes, I've got a solution.

Great! Make sure to link this issue when creating a PR.

**Comment by TobiSan5** [comment]
**Failed to pass, dropping this issue**
I met difficulties when trying to validate my solution with Leetcode. My solution was based on iteration, and it is not effective enough when the algorithm gets validated with a list of 1000 items. Due to time-restraints, I will not pursue a solution to this problem, and it should be assigned to someone else.

**Comment by vJechsmayr** [comment]
@Deepak2417 You are the next one in line - would you still like to work on this issue?

**Comment by Deepak2417** [comment]
Yeah, sure.

**Comment by Curious-Ujjwal** [comment]
Hey @vJechsmayr , it seems I can work on this issue. If it is open, assign it to me.
