### ISSUE TITLE
1582 - Special Positions in a Binary Matrix

### ISSUE THREAD

**Issue by chw9** [vJechsmayr/PythonAlgorithms#385]
## Description of the Problem

Given a rows x cols matrix mat, where mat[i][j] is either 0 or 1, return the number of special positions in mat.

A position (i,j) is called special if mat[i][j] == 1 and all other elements in row i and column j are 0 (rows and columns are 0-indexed).

## Code
```
class Solution(object):
    def numSpecial(self, mat):
        """
        :type mat: List[List[int]]
        :rtype: int
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/special-positions-in-a-binary-matrix/)

**Comment by chw9** [comment]
Please assign me to this issue

**Comment by olunusib** [comment]
would love to tackle this

**Comment by Suyyashaa** [comment]
Can I work on it?

**Comment by sanujana045** [comment]
i want to work on this
