### ISSUE TITLE
0021 - Merge Two Sorted Lists

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#39]
## Description of the Problem
Merge two sorted linked lists and return it as a new **sorted** list. The new list should be made by splicing together the nodes of the first two lists.

**Example:**
```
Input: 1->2->4, 1->3->4
Output: 1->1->2->3->4->4
```

## Code
```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def mergeTwoLists(self, l1: ListNode, l2: ListNode) -> ListNode:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/merge-two-sorted-lists/)

**Comment by ExpressHermes** [comment]
@vJechsmayr I would like to work on this issue too.

**Comment by francescobozzo** [comment]
@vJechsmayr I've just implemented my own solution for this problem. Feel free to choose which one you prefer
