### ISSUE TITLE
39. Combination Sum

### ISSUE THREAD

**Issue by TechTarun** [vJechsmayr/PythonAlgorithms#394]
## Description of the Problem
Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target. You may return the combinations in any order.

The same number may be chosen from candidates an unlimited number of times. Two combinations are unique if the frequency of at least one of the chosen numbers is different.

It is guaranteed that the number of unique combinations that sum up to target is less than 150 combinations for the given input.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/combination-sum/)

**Comment by TechTarun** [comment]
I want to add my accepted solution for this issue. Not only for this, I will also add my accepted solutions for combination sum 2, 3, 4 and 5. Please assign it to me.

**Comment by Gauravsaha-97** [comment]
I would like to work on this issue, if possible.

**Comment by vJechsmayr** [comment]
Closed - Problem Already Solved - Please Read Contribution Guidelines before creating an Issue & Check if your Problem is already solved in the code Folder
