### ISSUE TITLE
0023 - Merge k Sorted Lists

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#40]
## Description of the Problem
You are given an array of `k `linked-lists `lists`, each linked-list is sorted in ascending order.

_Merge all the linked-lists into one sorted linked-list and return it._

**Example 1:**
```
Input: lists = [[1,4,5],[1,3,4],[2,6]]
Output: [1,1,2,3,4,4,5,6]
Explanation: The linked-lists are:
[
  1->4->5,
  1->3->4,
  2->6
]
merging them into one sorted list:
1->1->2->3->4->4->5->6
```

**Example 2:**
```
Input: lists = []
Output: []
```

**Example 3:**
```
Input: lists = [[]]
Output: []
```

**Constraints:**

- `k == lists.length`
- `0 <= k <= 10^4`
- _0 <= lists[i].length <= 500_
- `-10^4 <= lists[i][j] <= 10^4`
- `lists[i]` is sorted in **ascending order**.
- The sum of` lists[i].length` won't exceed `10^4`.

## Code
```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def mergeKLists(self, lists: List[ListNode]) -> ListNode:
```
        
## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/merge-k-sorted-lists/)

**Comment by officialpm** [comment]
Hey @vJechsmayr ,
I shall work on this.

**Comment by officialpm** [comment]
@vJechsmayr 
#### PR #57 
Added Solution for 0023 - Merge-k-Sorted-Lists 🤘🏻
Space Complexity - O(n)
Time Complexity - O(n logn)
