### ISSUE TITLE
1108## Defanging an IP Address

### ISSUE THREAD

**Issue by AshishVarshneyy** [vJechsmayr/PythonAlgorithms#406]
## Description of the Problem
Given a valid (IPv4) IP address, return a defanged version of that IP address.

A defanged IP address replaces every period "." with "[.]".

Example 1:

Input: address = "1.1.1.1"
Output: "1[.]1[.]1[.]1"

Example 2:

Input: address = "255.100.50.0"
Output: "255[.]100[.]50[.]0"

Constraints:
The given address is a valid IPv4 address.

## Code
```
class Solution:
    def defangIPaddr(self, address: str) -> str:
        return(address.replace('.','[.]'))
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/defanging-an-ip-address/)

**Comment by AshishVarshneyy** [comment]
I would like to contribute on this Issue that I created. Thanks!!

**Comment by AnweshaSen** [comment]
I want to work on it :)
