### ISSUE TITLE
0102 - Binary Tree Level Order Traversal

### ISSUE THREAD

**Issue by OfiliPatrick** [vJechsmayr/PythonAlgorithms#409]
## Description of the Problem
Given a binary tree, return the level order traversal of its nodes' values. (ie, from left to right, level by level).

For example:
Given binary tree [3,9,20,null,null,15,7],
    3
   / \
  9  20
    /  \
   15   7
return its level order traversal as:
[
  [3],
  [9,20],
  [15,7]
]

## Code
```
class Solution:
    def levelOrder(self, root: TreeNode) -> List[List[int]]:
```

## Link To The LeetCode Problem
[Leetcode](https://leetcode.com/problems/binary-tree-level-order-traversal/)

**Comment by Halix267** [comment]
Hey @OfiliPatrick . Can i work on this issue

**Comment by OfiliPatrick** [comment]
I would like to also contribute through this problem.

**Comment by Halix267** [comment]
Oh sorry . But I saw help wanted tag . So i had ask for the issue

**Comment by OfiliPatrick** [comment]
> Oh sorry . But I saw help wanted tag . So i had ask for the issue

No worries, I was already working on this issue but you could create a new issue yourself and work on it. It's much better.
