### ISSUE TITLE
0024 - Swap Nodes in Pairs

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#41]
## Description of the Problem
Given a linked list, swap every two adjacent nodes and return its head.

You may **not** modify the values in the list's nodes, only nodes itself may be changed.

**Example:**
`Given 1->2->3->4, you should return the list as 2->1->4->3.`

## Code
```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def swapPairs(self, head: ListNode) -> ListNode:
```
        

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/swap-nodes-in-pairs/)

**Comment by bislara** [comment]
Hi, @vJechsmayr  I would like to work on this issue. Can you please assign it to me?
