### ISSUE TITLE
0367 - Valid Perfect Square

### ISSUE THREAD

**Issue by chw9** [vJechsmayr/PythonAlgorithms#419]
## Description of the Problem
Given a positive integer num, write a function which returns True if num is a perfect square else False.

Follow up: Do not use any built-in library function such as sqrt.

## Code
```
class Solution(object):
    def isPerfectSquare(self, num):
        """
        :type num: int
        :rtype: bool
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/valid-perfect-square/)

**Comment by chw9** [comment]
please assign me to this issue

**Comment by reyjoshuamacarat** [comment]
i can work on this issue @chw9 please assign me
