### ISSUE TITLE
0112 - Path Sum

### ISSUE THREAD

**Issue by HOD101s** [vJechsmayr/PythonAlgorithms#421]
## Description of the Problem
You may copy that from LeetCode
Given a binary tree and a sum, determine if the tree has a root-to-leaf path such that adding up all the values along the path equals the given sum.

## Example:
Given the below binary tree and sum = 22,
```
      5
     / \
    4   8
   /   / \
  11  13  4
 /  \      \
7    2      1
```
return true, as there exist a root-to-leaf path 5->4->11->2 which sum is 22.

## Code
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
        
class Solution:
    def hasPathSum(self, root: TreeNode, sum: int) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/path-sum/)

**Comment by HOD101s** [comment]
Kindly assign this issue to me as there is no other issue for this problem

**Comment by HOD101s** [comment]
I would be glad to contribute a solution @vJechsmayr

**Comment by HOD101s** [comment]
Kindly assign issue to me so i can make PR

**Comment by vJechsmayr** [comment]
Hi @HOD101s !

Please consider that I have a fulltimejob and cannot be online 24/7 - For the time between 10pm-5pm on workday I have to sleep&work - as soon as I get some free time I work through the Issues/PRs. 😸

**Comment by HOD101s** [comment]
Hi @vJechsmayr apologies if I came off as slightly over-persuasive. Just eager to contribute. We all really appreciate and are grateful for the efforts you're taking on these repos. Thank you!
