### ISSUE TITLE
1460 - Make Two Arrays Equal by Reversing Sub-arrays

### ISSUE THREAD

**Issue by HOD101s** [vJechsmayr/PythonAlgorithms#422]
## Description of the Problem
Given two integer arrays of equal length target and arr.

In one step, you can select any non-empty sub-array of arr and reverse it. You are allowed to make any number of steps.

Return True if you can make arr equal to target, or False otherwise.

## Example 1:
```
Input: target = [1,2,3,4], arr = [2,4,1,3]
Output: true
Explanation: You can follow the next steps to convert arr to target:
1- Reverse sub-array [2,4,1], arr becomes [1,4,2,3]
2- Reverse sub-array [4,2], arr becomes [1,2,4,3]
3- Reverse sub-array [4,3], arr becomes [1,2,3,4]
There are multiple ways to convert arr to target, this is not the only way to do so.
```

## Code
```
class Solution:
    def canBeEqual(self, target: List[int], arr: List[int]) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/make-two-arrays-equal-by-reversing-sub-arrays/)

**Comment by HOD101s** [comment]
Kindly Assign issue to me, as there is no issue against this problem

**Comment by HOD101s** [comment]
I would be glad to contribute a solution @vJechsmayr

**Comment by joy2306** [comment]
@vJechsmayr  kindly assign this to me i want to give it a try

**Comment by HOD101s** [comment]
@joy2306 kindly read Contributing guidelines.
