### ISSUE TITLE
0043 - Multiply Strings

### ISSUE THREAD

**Issue by Dave-Browne** [vJechsmayr/PythonAlgorithms#425]
## Description of the Problem
Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.

## Example
```
Input: num1 = "2", num2 = "3"
Output: "6"
```

## Code
```
class Solution:
    def multiply(self, num1: str, num2: str) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/multiply-strings/)

**Comment by dennis-pg** [comment]
Can look into this

**Comment by Dave-Browne** [comment]
@vJechsmayr Please assign this to me, i'll be happy to provide the solution.

**Comment by joy2306** [comment]
@Dave-Browne if this issue is still open i want to try it , can u assign it to me please?

**Comment by GorettiRivera** [comment]
@Dave-Browne 
Could you please assign me  this issue?

**Comment by Dave-Browne** [comment]
@GorettiRivera @dennis-pg Check the Readme and Contribution files. You need to find a problem on Leetcode that hasn't already been solved here and create an issue. The issue will be assigned to the person who created it.
