### ISSUE TITLE
0080 - Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by Dave-Browne** [vJechsmayr/PythonAlgorithms#426]
## Description of the Problem
Given a sorted array nums, remove the duplicates in-place such that duplicates appeared at most twice and return the new length.
Do not allocate extra space for another array, you must do this by modifying the input array in-place with O(1) extra memory.

## Example
```
Given nums = [0,0,1,1,1,1,2,3,3],
Your function should return length = 7, with the first seven elements of nums being modified to 0, 0, 1, 1, 2, 3 and 3 respectively.
It doesn't matter what values are set beyond the returned length.
```

## Code
```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/)

**Comment by Dave-Browne** [comment]
@vJechsmayr Please assign this issue to me. I'll be happy to provide the solution.

**Comment by reyjoshuamacarat** [comment]
@vJechsmayr can I work on this issue?

**Comment by bhartish** [comment]
@vJechsmayr please assign this issue to me.

**Comment by Shivansh-Malhotra** [comment]
@vJechsmayr please assign this issue to me.
