### ISSUE TITLE
0458 - Poor Pigs

### ISSUE THREAD

**Issue by niftyNitin** [vJechsmayr/PythonAlgorithms#428]
## Description of the Problem
There are 1000 buckets, one and only one of them is poisonous, while the rest are filled with water. They all look identical. If a pig drinks the poison it will die within 15 minutes. What is the minimum amount of pigs you need to figure out which bucket is poisonous within one hour?

Answer this question, and write an algorithm for the general case.

 

General case:

If there are n buckets and a pig drinking poison will die within m minutes, how many pigs (x) you need to figure out the poisonous bucket within p minutes? There is exactly one bucket with poison.

 

Note:

A pig can be allowed to drink simultaneously on as many buckets as one would like, and the feeding takes no time.
After a pig has instantly finished drinking buckets, there has to be a cool down time of m minutes. During this time, only observation is allowed and no feedings at all.
Any given bucket can be sampled an infinite number of times (by an unlimited number of pigs).

## Code
```
class Solution:
    def poorPigs(self, buckets: int, minutesToDie: int, minutesToTest: int) -> int:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/poor-pigs/)

**Comment by niftyNitin** [comment]
Can you assign this problem to me? I would like to work on the solution with a proper documentation

**Comment by Aditya489** [comment]
can you assign me this task? i would like to work on this

**Comment by vJechsmayr** [comment]
> can you assign me this task? i would like to work on this

@Aditya489 There is already @niftyNitin assigned to it. If there is no PR in the next 14days I will assign it to you. If you like to participate in the meantime you can look for an problem that is not solved & no open issue
