### ISSUE TITLE
0500 - Keyboard Row

### ISSUE THREAD

**Issue by riwim** [vJechsmayr/PythonAlgorithms#430]
## Description of the Problem

Given a List of words, return the words that can be typed using letters of **alphabet** on only one row's of American keyboard like the image below.

![American keyboard](https://assets.leetcode.com/uploads/2018/10/12/keyboard.png)

### Example

```
Input: ["Hello", "Alaska", "Dad", "Peace"]
Output: ["Alaska", "Dad"]
```

### Note

1. You may use one character in the keyboard more than once.
1. You may assume the input string will only contain letters of alphabet.

## Code

```python
class Solution:
    def findWords(self, words: List[str]) -> List[str]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/keyboard-row/)

**Comment by vaderjunior** [comment]
Hey,
I would like to do this.
Can you assign this to me?
