### ISSUE TITLE
14## - longest-common-prefix

### ISSUE THREAD

**Issue by adityaarakeri** [vJechsmayr/PythonAlgorithms#432]
#### Longest Common Prefix
Write a function to find the longest common prefix string amongst an array of strings.
If there is no common prefix, return an empty string "".
Example 1:
Input: ["flower","flow","flight"]
Output: "fl"

Example 2:
Input: ["dog","racecar","car"]
Output: ""
Explanation: There is no common prefix among the input strings.

## Code
LeetCode/0014_longest_common_prefix.py

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/longest-common-prefix/)

**Comment by adityaarakeri** [comment]
please assign this to me, thanks

**Comment by vJechsmayr** [comment]
Not assigned to the linked issue - please consider Contributing Guidelines
