### ISSUE TITLE
0279 - Perfect Squares

### ISSUE THREAD

**Issue by anirudhvsp** [vJechsmayr/PythonAlgorithms#435]
## Description of the Problem
Given a positive integer n, find the least number of perfect square numbers (for example, 1, 4, 9, 16, ...) which sum to n.

Example 1:

Input: n = 12
Output: 3 
Explanation: 12 = 4 + 4 + 4.
Example 2:

Input: n = 13
Output: 2
Explanation: 13 = 4 + 9.

## Code
```
class Solution(object):
	def numSquares(self, n):
		"""
		:type n: int
		:rtype: int
		"""
Code
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/perfect-squares/description/)

**Comment by anirudhvsp** [comment]
Please assign this problem to me

**Comment by sajeevan16** [comment]
assign me

**Comment by kanchitank** [comment]
```
class Solution(object):
    def numSquares(self,n):
        if(n == 0):
            return 0
        if(n == 1):
            return 1
        squares = self.findSquares(n)
        rows = len(squares)
        cols = n + 1
        mat = [n] * cols
        mat[0] = 0

        for s in squares:
            for j in range(s,cols):
                mat[j] = min(mat[j], 1 + mat[j - s])

        return mat[n]

    def min(self,a,b):
        if(a <= b):
            return a
        else:
            return b


    def findSquares(self,n):
        i = 1
        squares = []
        while (i * i <= n):
            squares.append(i * i)
            i = i + 1
        return squares

x = Solution()

print(x.numSquares(12))
```

**Comment by kanchitank** [comment]
@anirudhvsp Will this work?

**Comment by kanchitank** [comment]
#445

**Comment by anirudhvsp** [comment]
@kanchitank I already have the solution, I was asking for the repo maintainer to assign this particular problem to me so that I can a make pull request

**Comment by kanchitank** [comment]
@anirudhvsp Oh so I cannot contribute to this?

**Comment by anirudhvsp** [comment]
You can, but you'll need to make a separate issue stating the problem you wish to solve and if the maintainer assigns said problem to you then you can make a pull request and your solution would be merged with the master branch.

**Comment by anirudhvsp** [comment]
Apologies, It was negligence on my part.
I did not realize I had to link a pull request to the issue, I was waiting for the problem to be assigned to me.
If you have already made a pull request then you can contribute to the repo.

**Comment by illusionrs** [comment]
we have to submit solution with problem by ourself choice in python?

**Comment by vJechsmayr** [comment]
@anirudhvsp Go for it! The Creator of an issue gets prefered assigned to it.

**Comment by illusionrs** [comment]
please assign to mer

**Comment by illusionrs** [comment]
please assign me a problem

**Comment by vJechsmayr** [comment]
@illusionrs Sorry - the creator of the Issue gets assigned prefered

**Comment by sumasreeeduru** [comment]
Can you assign me anything

**Comment by SRINIDHI-G** [comment]
could u assign this problem

**Comment by anirudhvsp** [comment]
> @anirudhvsp Go for it! The Creator of an issue gets prefered assigned to it.

Awesome, I have made a pull request for this problem but for some reason I am unable to link it to this issue, I have mentioned this issue in one of the commits though.

**Comment by vibhoragarwal019** [comment]
assign the problem

**Comment by krateepareek** [comment]
Could you please assign this problem to me.

**Comment by krateepareek** [comment]
would you assign me this problem

**Comment by vJechsmayr** [comment]
> > @anirudhvsp Go for it! The Creator of an issue gets prefered assigned to it.
> 
> Awesome, I have made a pull request for this problem but for some reason I am unable to link it to this issue, I have mentioned this issue in one of the commits though.

@anirudhvsp let me see if i can find it... there are pretty much PRs at the moment
