### ISSUE TITLE
1023 - Camelcase Matching

### ISSUE THREAD

**Issue by Rollerss** [vJechsmayr/PythonAlgorithms#437]
## Description of the Problem
A query word matches a given pattern if we can insert lowercase letters to the pattern word so that it equals the query. (We may insert each character at any position, and may insert 0 characters.)

Given a list of queries, and a pattern, return an answer list of booleans, where answer[i] is true if and only if queries[i] matches the pattern.

## Example 1:
```
Input: queries = ["FooBar","FooBarTest","FootBall","FrameBuffer","ForceFeedBack"], pattern = "FB"
Output: [true,false,true,true,false]
Explanation: 
"FooBar" can be generated like this "F" + "oo" + "B" + "ar".
"FootBall" can be generated like this "F" + "oot" + "B" + "all".
"FrameBuffer" can be generated like this "F" + "rame" + "B" + "uffer".
```

## Code
```
class Solution:
    def camelMatch(self, queries: List[str], pattern: str) -> List[bool]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/camelcase-matching/)

**Comment by Rollerss** [comment]
Please assign this issue to me. Thank you.

**Comment by Aditya489** [comment]
please assign me this task

**Comment by PriyanshTri** [comment]
assign this to me. thankyou
