### ISSUE TITLE
0082 - Remove Duplicates from Sorted List II

### ISSUE THREAD

**Issue by Dave-Browne** [vJechsmayr/PythonAlgorithms#440]
## Description of the Problem
Given a sorted linked list, delete all nodes that have duplicate numbers, leaving only distinct numbers from the original list.
Return the linked list sorted as well.

## Example
```
Input: 1->2->3->3->4->4->5
Output: 1->2->5
```

## Code
```
# Definition for singly-linked list.
#class ListNode:
#    def __init__(self, val=0, next=None):
#        self.val = val
#        self.next = next
class Solution:
    def deleteDuplicates(self, head: ListNode) -> ListNode:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/)

**Comment by Dave-Browne** [comment]
Please assign the issue to me. Thanks

**Comment by aishuo07** [comment]
please assign this task to me

**Comment by Aditya489** [comment]
please assign the issue to me i would like to work on this! thank you
