### ISSUE TITLE
0929 - Unique Email Addresses

### ISSUE THREAD

**Issue by spoorgholi74** [vJechsmayr/PythonAlgorithms#448]
## Description of the Problem
Every email consists of a local name and a domain name, separated by the @ sign.

For example, in alice@leetcode.com, alice is the local name, and leetcode.com is the domain name.

Besides lowercase letters, these emails may contain '.'s or '+'s.

If you add periods ('.') between some characters in the local name part of an email address, mail sent there will be forwarded to the same address without dots in the local name.  For example, "alice.z@leetcode.com" and "alicez@leetcode.com" forward to the same email address.  (Note that this rule does not apply for domain names.)

If you add a plus ('+') in the local name, everything after the first plus sign will be ignored. This allows certain emails to be filtered, for example m.y+name@email.com will be forwarded to my@email.com.  (Again, this rule does not apply for domain names.)

It is possible to use both of these rules at the same time.

Given a list of emails, we send one email to each address in the list.  How many different addresses actually receive mails? 

## Code
```
class Solution:
    def numUniqueEmails(self, emails: List[str]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/unique-email-addresses/)

**Comment by spoorgholi74** [comment]
Please assign this to me.

**Comment by sourabmaity** [comment]
i am also interested

**Comment by Rupa-421** [comment]
I'm also interested.Can you add me too?
