### ISSUE TITLE
0067 - Add Binary

### ISSUE THREAD

**Issue by vmgmreddy** [vJechsmayr/PythonAlgorithms#449]
## Description of the Problem
Given two binary strings, return their sum (also a binary string).

The input strings are both non-empty and contains only characters 1 or 0.

Example 1:
```
Input: a = "11", b = "1"
Output: "100"
```
Example 2:
```
Input: a = "1010", b = "1011"
Output: "10101"
 ```

Constraints:

Each string consists only of '0' or '1' characters.
1 <= a.length, b.length <= 10^4
Each string is either "0" or doesn't contain any leading zero.

## Code
```
PR
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/add-binary/)

**Comment by vmgmreddy** [comment]
please assign this problem to me!

**Comment by mkiglics** [comment]
I would like to work on this one

**Comment by vJechsmayr** [comment]
Issue with Problem 67 is already open - please find another Problem you want to solve 😸
