### ISSUE TITLE
0200 - Number of Islands

### ISSUE THREAD

**Issue by mkiglics** [vJechsmayr/PythonAlgorithms#452]
## Description of the Problem
Given a 2d grid map of '1's (land) and '0's (water), count the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.

__Example 1:__

```
Input: grid = [
  ["1","1","1","1","0"],
  ["1","1","0","1","0"],
  ["1","1","0","0","0"],
  ["0","0","0","0","0"]
]
Output: 1
```
__Example 2:__

```
Input: grid = [
  ["1","1","0","0","0"],
  ["1","1","0","0","0"],
  ["0","0","1","0","0"],
  ["0","0","0","1","1"]
]
Output: 3
```
## Code
```python
class Solution(object):
    def numIslands(self, grid):
        """
        :type grid: List[List[str]]
        :rtype: int
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/number-of-islands/)

**Comment by mkiglics** [comment]
I would like to work on this one

**Comment by Krishna-Sivakumar** [comment]
I'd like to try this one
