### ISSUE TITLE
0014 - Longest Common Prefix

### ISSUE THREAD

**Issue by Zaman3027** [vJechsmayr/PythonAlgorithms#464]
## Description of the Problem
Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

 

Example 1:

Input: strs = ["flower","flow","flight"]
Output: "fl"

Example 2:

Input: strs = ["dog","racecar","car"]
Output: ""
Explanation: There is no common prefix among the input strings.

## Code
```
class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        # compares first letter of all words, then moves to next letter
        s = ""
        if len(strs)==0: #edge case, no elements in list
            return s
        elif len(strs)==1: #edge case, single element in list
            return strs[0]

        #word length of shortest word to prevent index out of range
        for a in range(len(min(strs))): 
            #loops through each word in list, starting with second word
            for b in range(1, len(strs)): 
                #compares nth character of first word to other words
                if strs[0][a]==strs[b][a]: 
                    #only adds to pattern if nth character same up to the last word
                    if b==len(strs)-1: 
                        s += strs[0][a]
                else: #exits when characters don't match
                    return s
        return s
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/longest-common-prefix)

**Comment by Double77x** [comment]
Can you assign this to me please, thank you.

**Comment by Zaman3027** [comment]
I want to get assigned on this

**Comment by sourabmaity** [comment]
i want to work in this issue

**Comment by vJechsmayr** [comment]
Please Read Contribution Guidelines - closed as **spam** Issue already open!
