### ISSUE TITLE
0006 - ZigZag Conversion

### ISSUE THREAD

**Issue by MaferMazu** [vJechsmayr/PythonAlgorithms#476]
## Description of the Problem
The string `"PAYPALISHIRING"` is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)
```
P   A   H   N
A P L S I I G
Y   I   R
```
And then read line by line: `"PAHNAPLSIIGYIR"`

Write the code that will take a string and make this conversion given a number of rows:

`string convert(string s, int numRows);`
 

Example 1:
```
Input: s = "PAYPALISHIRING", numRows = 3
Output: "PAHNAPLSIIGYIR"
```

Example 2:
```
Input: s = "PAYPALISHIRING", numRows = 4
Output: "PINALSIGYAHRPI"
Explanation:
P     I    N
A   L S  I G
Y A   H R
P     I
```

Example 3:
```
Input: s = "A", numRows = 1
Output: "A"
```
 
Constraints:

`1 <= s.length <= 1000`
`s consists of English letters (lower-case and upper-case), ',' and '.'.`
`1 <= numRows <= 1000`

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/zigzag-conversion/)

**Comment by MaferMazu** [comment]
I'd like to work on this.

**Comment by Achyut-sudo** [comment]
I would also like to work on this

**Comment by Achyut-sudo** [comment]
can I use CamelCase ?
(i.e instead of "string convert"  can I use "StringConvert")

**Comment by wibbn** [comment]
I'd also like to work with this problem

**Comment by wibbn** [comment]
#486

**Comment by Achyut-sudo** [comment]
I have completed this Stru=ingConvert function. do I need to add code to take input? (not specified in issue)
and if yes I am supposed to do that then please let me know the format of input for example is it in form of 
S = "PAYPALISHIRING" n = 3     (i.e. do i need to filter out "s = " and " n = ")
or it's just 
"PAYPALISHIRING" 3    (i.e  just get take a string and an int from a single separate data)

**Comment by Achyut-sudo** [comment]
![leewtcode _doubt](https://user-images.githubusercontent.com/71660666/95612202-a37e7f00-0a80-11eb-86ad-dadd4794c793.jpg)
stdout == expected still wrong ??? (i am very sorry to ask so much. I am very new to this )

**Comment by vJechsmayr** [comment]
Closed - Issue already open!
