### ISSUE TITLE
0028 - Implement strStr()

### ISSUE THREAD

**Issue by kevinbeirne1** [vJechsmayr/PythonAlgorithms#488]
## Description of the Problem
Implement strStr().

Return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.

Clarification:

What should we return when needle is an empty string? This is a great question to ask during an interview.

For the purpose of this problem, we will return 0 when needle is an empty string. This is consistent to C's strstr() and Java's indexOf().

 

Example 1:

Input: haystack = "hello", needle = "ll"
Output: 2
Example 2:

Input: haystack = "aaaaa", needle = "bba"
Output: -1
Example 3:

Input: haystack = "", needle = ""
Output: 0
 

Constraints:

0 <= haystack.length, needle.length <= 5 * 104
haystack and needle consist of only lower-case English characters.

## Code
```
class Solution:
    def strStr(self, haystack: str, needle: str) -> int:
        try:
            res = haystack.index(needle)
            return res
        except:
            return -1 if needle else 0

```

## Link To The LeetCode Problem
https://leetcode.com/problems/implement-strstr/

**Comment by Gitesh1209** [comment]
can i do

**Comment by vJechsmayr** [comment]
Problem already solved/Issue already open 

CLOSED
