### ISSUE TITLE
10. Regular Expression Matching

### ISSUE THREAD

**Issue by princesinghtomar** [vJechsmayr/PythonAlgorithms#496]
## Description of the Problem
Given an input string (s) and a pattern (p), implement regular expression matching with support for '.' and '*' where: 

    '.' Matches any single character.​​​​
    '*' Matches zero or more of the preceding element.

The matching should cover the entire input string (not partial).

 

Example 1:

Input: s = "aa", p = "a"
Output: false
Explanation: "a" does not match the entire string "aa".

Example 2:

Input: s = "aa", p = "a*"
Output: true
Explanation: '*' means zero or more of the preceding element, 'a'. Therefore, by repeating 'a' once, it becomes "aa".

Example 3:

Input: s = "ab", p = ".*"
Output: true
Explanation: ".*" means "zero or more (*) of any character (.)".

Example 4:

Input: s = "aab", p = "c*a*b"
Output: true
Explanation: c can be repeated 0 times, a can be repeated 1 time. Therefore, it matches "aab".

Example 5:

Input: s = "mississippi", p = "mis*is*p*."
Output: false

 

Constraints:

    0 <= s.length <= 20
    0 <= p.length <= 30
    s contains only lowercase English letters.
    p contains only lowercase English letters, '.', and '*'.

## Code
```
class Solution(object):
    def isMatch(self, s, p):

```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/regular-expression-matching/)

**Comment by princesinghtomar** [comment]
I would like to do this.

**Comment by vJechsmayr** [comment]
Issue Already open! Please make sure to check that first before creating an Issue
