### ISSUE TITLE
0022 - Generate Parentheses

### ISSUE THREAD

**Issue by princesinghtomar** [vJechsmayr/PythonAlgorithms#497]
## Description of the Problem
Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

 

Example 1:

Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]

Example 2:

Input: n = 1
Output: ["()"]

 

Constraints:

    1 <= n <= 8

## Code
```
class Solution(object):
    def generateParenthesis(self, n):
        """
        :type n: int
        :rtype: List[str]
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/generate-parentheses/)

**Comment by princesinghtomar** [comment]
i will like to do this one myself

**Comment by Gauravsaha-97** [comment]
I would like to work on this issue, if possible.

**Comment by vJechsmayr** [comment]
There is already an open Issue for that Problem - Please make sure to check that first
