### ISSUE TITLE
0005 - Longest Palindromic Substring

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#5]
Given a string **s**, find the longest palindromic substring in **s**. You may assume that the maximum length of **s** is 1000.

**Example 1:**
```
Input: "babad"
Output: "bab"
Note: "aba" is also a valid answer.
```

**Example 2:**
```
Input: "cbbd"
Output: "bb"
```

## LeetCode Problem
[LeetCode Problem 5](https://leetcode.com/problems/longest-palindromic-substring/)

**Comment by bislara** [comment]
Hey, @vJechsmayr   I would like to work on this issue. Can you please assign it to me?
