### ISSUE TITLE
1018 - Binary Prefix Divisible By 5

### ISSUE THREAD

**Issue by daniel-vdp** [vJechsmayr/PythonAlgorithms#502]
Given an array A of 0s and 1s, consider N_i: the i-th subarray from A[0] to A[i] interpreted as a binary number (from most-significant-bit to least-significant-bit.)

Return a list of booleans answer, where answer[i] is true if and only if N_i is divisible by 5.

## Code
```
class Solution(object):
    def prefixesDivBy5(self, A):
        """
        :type A: List[int]
        :rtype: List[bool]
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/binary-prefix-divisible-by-5/)

**Comment by frank731** [comment]
Can I be assigned this?

**Comment by daniel-vdp** [comment]
> Can I be assigned this?

I've made the issue so I can solve it. I've just putting a pull request through now.
