### ISSUE TITLE
0215 - Kth Largest Element in an Array

### ISSUE THREAD

**Issue by OMEGAeNcore** [vJechsmayr/PythonAlgorithms#509]
## Description of the Problem
Find the kth largest element in an unsorted array. Note that it is the kth largest element in the sorted order, not the kth distinct element.

Example 1:

Input: [3,2,1,5,6,4] and k = 2
Output: 5
Example 2:

Input: [3,2,3,1,2,4,5,5,6] and k = 4
Output: 4

Note:
You may assume k is always valid, 1 ≤ k ≤ array's length.

## Code
```
class Solution:
    def findKthLargest(self, nums: List[int], k: int) -> int:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/kth-largest-element-in-an-array/)

**Comment by OMEGAeNcore** [comment]
I would like to be assigned to this

**Comment by prakhar-agarwall** [comment]
I'd like to take up this issue.

**Comment by camilosalazar98** [comment]
If no one has submitted to this one can I have it? :D

**Comment by vJechsmayr** [comment]
@prakhar-agarwall @camilosalazar98 - The Creator will always get assigned prefered - Please consider that I'm not online 24/7 so when the Issue-Creator had already written that he/she wants to work on it I assign them as soon as I'm online
