### ISSUE TITLE
0125## - Valid Palindrome

### ISSUE THREAD

**Issue by AditSoni** [vJechsmayr/PythonAlgorithms#519]
## Description of the Problem
Given a string, determine if it is a palindrome, considering only alphanumeric characters and ignoring cases.

Note: For the purpose of this problem, we define empty string as valid palindrome.

Example 1:

Input: "A man, a plan, a canal: Panama"
Output: true

Example 2:

Input: "race a car"
Output: false

 

Constraints:

    s consists only of printable ASCII characters.

## Code
```
class Solution:
    def isPalindrome(self, s: str) -> bool:
       #Your code here 
     
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/valid-palindrome/)

**Comment by AditSoni** [comment]
#520 Made a pull request

**Comment by vJechsmayr** [comment]
@AditSoni There is already an Issue for that Problem open - please check that first before creating an Issue 😸
