### ISSUE TITLE
0041 - First Missing Positive

### ISSUE THREAD

**Issue by soham0-0** [vJechsmayr/PythonAlgorithms#52]
## Description of the Problem
Given an unsorted integer array, find the smallest missing positive integer.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/first-missing-positive/)

**Comment by soham0-0** [comment]
@vJechsmayr May I work on this?

**Comment by vJechsmayr** [comment]
@soham0-0  sure go ahead 😄

**Comment by devanshi-katyal** [comment]
I would like to work on this issue!
