### ISSUE TITLE
0448 - Find All Numbers Disappeared in an Array

### ISSUE THREAD

**Issue by sj538** [vJechsmayr/PythonAlgorithms#521]
**Description of the problem**

Given an array of integers where 1 ≤ a[i] ≤ n (n = size of array), some elements appear twice and others appear once.

Find all the elements of [1, n] inclusive that do not appear in this array.

Could you do it without extra space and in O(n) runtime? You may assume the returned list does not count as extra space.

Example:

Input:
[4,3,2,7,8,2,3,1]

Output:
[5,6]

**Code**

class Solution:
    def findDisappearedNumbers(self, nums: List[int]) -> List[int]:
        
**Link to the Leetcode problem**
https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/

**Comment by sj538** [comment]
Please assign this to me.

**Comment by Deepak2417** [comment]
I am eager to solve this problem with complexity as mentioned. Kindly assign this to me.
