### ISSUE TITLE
1160 - Find Words That Can Be Formed by Characters

### ISSUE THREAD

**Issue by dangerworm** [vJechsmayr/PythonAlgorithms#528]
## Description of the Problem
You are given an array of strings words and a string chars.

A string is good if it can be formed by characters from chars (each character can only be used once).

Return the sum of lengths of all good strings in words.

## Code
```
class Solution:
    def countCharacters(self, words: List[str], chars: str) -> int:
```

## Link To The LeetCode Problem
[LeetCode 1160](https://leetcode.com/problems/find-words-that-can-be-formed-by-characters/)

**Comment by Gabriel-nps** [comment]
I would like to be assigned to this.

**Comment by dangerworm** [comment]
I was hoping I could be assigned this, as I've already done the work.

**Comment by Gabriel-nps** [comment]
I see. Go ahead :)

**Comment by dangerworm** [comment]
Thank you Gabriel.
