### ISSUE TITLE
0139 - Word Break

### ISSUE THREAD

**Issue by Karnak123** [vJechsmayr/PythonAlgorithms#53]
## Description of the Problem
Given a non-empty string s and a dictionary wordDict containing a list of non-empty words, determine if s can be segmented into a space-separated sequence of one or more dictionary words.

Note:
- The same word in the dictionary may be reused multiple times in the segmentation.
- You may assume the dictionary does not contain duplicate words.

Example 1:
```
Input: s = "leetcode", wordDict = ["leet", "code"]
Output: true
Explanation: Return true because "leetcode" can be segmented as "leet code".
```
Example 2:
```
Input: s = "applepenapple", wordDict = ["apple", "pen"]
Output: true
Explanation: Return true because "applepenapple" can be segmented as "apple pen apple".
             Note that you are allowed to reuse a dictionary word.
```
Example 3:
```
Input: s = "catsandog", wordDict = ["cats", "dog", "sand", "and", "cat"]
Output: false
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/word-break)

**Comment by Karnak123** [comment]
@vJechsmayr may I be assigned to this issue?

**Comment by vJechsmayr** [comment]
@Karnak123 done - please go ahead and do your best 😄
