### ISSUE TITLE
0091 - Decode Ways

### ISSUE THREAD

**Issue by neaGaze** [vJechsmayr/PythonAlgorithms#535]
## Description of the Problem
A message containing letters from A-Z is being encoded to numbers using the following mapping:
```
'A' -> 1
'B' -> 2
...
'Z' -> 26
```
Given a non-empty string containing only digits, determine the total number of ways to decode it.

The answer is guaranteed to fit in a 32-bit integer.

## Code
```
class Solution:
    def numDecodings(self, s: str) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/decode-ways/)

**Comment by reach-the-sky** [comment]
Can you assign this to me.
