### ISSUE TITLE
1340 - Jump Game V

### ISSUE THREAD

**Issue by livace** [vJechsmayr/PythonAlgorithms#542]
## Description of the Problem
You may copy that from LeetCode
Given an array of integers `arr` and an integer `d`. In one step you can jump from index i to index:

- `i + x` where: `i + x < arr.length` and `0 < x <= d`

- `i - x` where: `i - x >= 0` and `0 < x <= d`

In addition, you can only jump from index `i` to index `j` if `arr[i] > arr[j]` and `arr[i] > arr[k]` for all indices k between `i` and `j` (More formally `min(i, j) < k < max(i, j)`).

You can choose any index of the array and start jumping. Return the maximum number of indices you can visit.

Notice that you can not jump outside of the array at any time.

## Code
```
class Solution(object):
    def maxJumps(self, arr, d):
        """
        :type arr: List[int]
        :type d: int
        :rtype: int
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/jump-game-v/)

**Comment by livace** [comment]
Please assign it to me

**Comment by reach-the-sky** [comment]
Can you please assign this to me.

**Comment by RgnDunes** [comment]
Can you please assign this to me ?
