### ISSUE TITLE
0258 - Add Digits

### ISSUE THREAD

**Issue by rkkksss** [vJechsmayr/PythonAlgorithms#545]
## Description of the Problem
Given a non-negative integer num, repeatedly add all its digits until the result has only one digit.

**Example:**
```
Input: 38
Output: 2 
Explanation: The process is like: 3 + 8 = 11, 1 + 1 = 2. 
             Since 2 has only one digit, return it.
```
Follow up:
Could you do it without any loop/recursion in O(1) runtime?

## Code
```
class Solution:
    def addDigits(self, num: int) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/add-digits/)

**Comment by LCVcode** [comment]
Can you please assign this to me?
