### ISSUE TITLE
0368 - Largest Divisible Subset

### ISSUE THREAD

**Issue by sailok** [vJechsmayr/PythonAlgorithms#548]
## Description of the Problem
Given a set of distinct positive integers, find the largest subset such that every pair (Si, Sj) of elements in this subset satisfies:
Si % Sj = 0 or Sj % Si = 0.

If there are multiple solutions, return any subset is fine.

## Code
```
class Solution:
    def largestDivisibleSubset(self, nums: List[int]) -> List[int]:
        
```

## Link To The LeetCode Problem
[Largest Divisible Subset](https://leetcode.com/problems/largest-divisible-subset/)

**Comment by sailok** [comment]
i'll do this one.

**Comment by flick-23** [comment]
Please assign this to me. I will do it!

**Comment by prajjval30-zz** [comment]
Please assing it to me
