### ISSUE TITLE
0437 - Path Sum III

### ISSUE THREAD

**Issue by frank731** [vJechsmayr/PythonAlgorithms#550]
## Description of the Problem
You are given a binary tree in which each node contains an integer value.

Find the number of paths that sum to a given value.

The path does not need to start or end at the root or a leaf, but it must go downwards (traveling only from parent nodes to child nodes).

The tree has no more than 1,000 nodes and the values are in the range -1,000,000 to 1,000,000.

## Code
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def pathSum(self, root: TreeNode, sum: int) -> int:

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/path-sum-iii/)

**Comment by frank731** [comment]
I'll do this problem

**Comment by flick-23** [comment]
Please assign this to me. I will do it!

**Comment by frank731** [comment]
> Please assign this to me. I will do it!

Sorry, I have already been assigned and have opened a pull request
