### ISSUE TITLE
1589 - Maximum Sum Obtained of Any Permutation

### ISSUE THREAD

**Issue by bhawesh96** [vJechsmayr/PythonAlgorithms#553]
## Description of the Problem
We have an array of integers, nums, and an array of requests where requests[i] = [starti, endi]. The ith request asks for the sum of nums[starti] + nums[starti + 1] + ... + nums[endi - 1] + nums[endi]. Both starti and endi are 0-indexed.

Return the maximum total sum of all requests among all permutations of nums.

Since the answer may be too large, return it modulo 109 + 7.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/)

**Comment by bhawesh96** [comment]
I'd like to take this up.

**Comment by Curious-Ujjwal** [comment]
If this issue is currently open, I would like to solve it.
Can you assign this to me?
Thank You!

**Comment by vampirepapi** [comment]
please assign this to me! Thanks!

**Comment by makshat01** [comment]
This is my first hacktoberfest participation and getting to solve a problem would help me grow in terms of knowledge and help towards open-source. If it is still open can you assign this to me?
