### ISSUE TITLE
0030 - Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by hpp3** [vJechsmayr/PythonAlgorithms#555]
## Description of the Problem
You are given a string s and an array of strings words of the same length. Return all starting indices of substring(s) in s that is a concatenation of each word in words exactly once, in any order, and without any intervening characters.

You can return the answer in any order.
Example 1:

```
Input: s = "barfoothefoobarman", words = ["foo","bar"]
Output: [0,9]
Explanation: Substrings starting at index 0 and 9 are "barfoo" and "foobar" respectively.
The output order does not matter, returning [9,0] is fine too.
```

## Link To The LeetCode Problem
[Substring with Concatenation of All Words](https://leetcode.com/problems/substring-with-concatenation-of-all-words/)

**Comment by DhawalKhapre** [comment]
Please assign this issue to me

**Comment by Achyut-sudo** [comment]
please assign me to  this issue

**Comment by Achyut-sudo** [comment]
#592

**Comment by vJechsmayr** [comment]
Issue already open (#17 ) Please read Contribution Guidelines before creating an Issue 😸
