### ISSUE TITLE
1593## - Show your machine information in command line

### ISSUE THREAD

**Issue by hoseinfzad** [vJechsmayr/PythonAlgorithms#576]
## Description of the Problem
i want to show pc information in command line 

## Code
def show_sensors():
    print("Python Version:{0.major}.{0.minor}".format(python_version()))
    for address in ip_addresses():
        print("IP Addresses: {0[1]} ({0[0]})".format(address))
        print("CPU Load: {:.1f}".format(cpu_load()))
        print("RAM Available: {} MiB".format(ram_available() / 1024**2))
        print("AC Connected: {}".format(ac_connected()))

Code
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/)

**Comment by vJechsmayr** [comment]
If you want to solve the [LeetCode Problem 1593](https://leetcode.com/problems/split-a-string-into-the-max-number-of-unique-substrings/) you can do so - if not: **Read Contribution Guidelines**
