### ISSUE TITLE
0043 - Multiply Strings

### ISSUE THREAD

**Issue by SatyamYadav-cmd** [vJechsmayr/PythonAlgorithms#577]
## Description of the Problem
Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.

Example 1:

Input: num1 = "2", num2 = "3"
Output: "6"
Example 2:

Input: num1 = "123", num2 = "456"
Output: "56088"
Note:

The length of both num1 and num2 is < 110.
Both num1 and num2 contain only digits 0-9.
Both num1 and num2 do not contain any leading zero, except the number 0 itself.
You must not use any built-in BigInteger library or convert the inputs to integer directly.

## Code
```
class Solution(object):
    def multiply(self, num1, num2):
        """
        :type num1: str
        :type num2: str
        :rtype: str
        """

```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/multiply-strings/)

**Comment by SatyamYadav-cmd** [comment]
I would like to be assigned to this

**Comment by reach-the-sky** [comment]
I would Like to do this task.
