### ISSUE TITLE
1470 - Shuffle the Array

### ISSUE THREAD

**Issue by tejasvicsr1** [vJechsmayr/PythonAlgorithms#584]
## Description of the Problem
Given the array nums consisting of 2n elements in the form [x1,x2,...,xn,y1,y2,...,yn].

Return the array in the form [x1,y1,x2,y2,...,xn,yn].

 

Example 1:

Input: nums = [2,5,1,3,4,7], n = 3
Output: [2,3,5,4,1,7] 
Explanation: Since x1=2, x2=5, x3=1, y1=3, y2=4, y3=7 then the answer is [2,3,5,4,1,7].

Example 2:

Input: nums = [1,2,3,4,4,3,2,1], n = 4
Output: [1,4,2,3,3,2,4,1]

Example 3:

Input: nums = [1,1,2,2], n = 2
Output: [1,2,1,2]
 

Constraints:

1 <= n <= 500
nums.length == 2n
1 <= nums[i] <= 10^3
## Code
```
class Solution:
    def shuffle(self, nums: List[int], n: int) -> List[int]:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/shuffle-the-array/)

**Comment by tejasvicsr1** [comment]
I would like to be assigned to this.

**Comment by reach-the-sky** [comment]
Can you please assign this to me.
