### ISSUE TITLE
1402 - Reducing Dishes

### ISSUE THREAD

**Issue by nainys** [vJechsmayr/PythonAlgorithms#585]
## Description of the Problem
A chef has collected data on the satisfaction level of his n dishes. Chef can cook any dish in 1 unit of time.

Like-time coefficient of a dish is defined as the time taken to cook that dish including previous dishes multiplied by its satisfaction level  i.e.  time[i]*satisfaction[i]

Return the maximum sum of Like-time coefficient that the chef can obtain after dishes preparation.

Dishes can be prepared in any order and the chef can discard some dishes to get this maximum value.

## Code
```
class Solution:
    def maxSatisfaction(self, satisfaction: List[int]) -> int:
```

## Link To The LeetCode Problem
[ReducingDishes](https://leetcode.com/problems/reducing-dishes/)

**Comment by learn-everyday-with-me** [comment]
Can you assign this to me.

**Comment by reach-the-sky** [comment]
Can you assign this to me.

**Comment by nainys** [comment]
I would like to be assigned to this.
