### ISSUE TITLE
0088 - Merge Sorted Array

### ISSUE THREAD

**Issue by SatyamYadav-cmd** [vJechsmayr/PythonAlgorithms#591]
## Description of the Problem
Given two sorted integer arrays nums1 and nums2, merge nums2 into nums1 as one sorted array.

Note:

The number of elements initialized in nums1 and nums2 are m and n respectively.
You may assume that nums1 has enough space (size that is equal to m + n) to hold additional elements from nums2.
Example:

Input:
nums1 = [1,2,3,0,0,0], m = 3
nums2 = [2,5,6],       n = 3

Output: [1,2,2,3,5,6]
 

Constraints:

-10^9 <= nums1[i], nums2[i] <= 10^9
nums1.length == m + n
nums2.length == n

## Code
```
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/merge-sorted-array/)

**Comment by SatyamYadav-cmd** [comment]
I would like to be assigned to this

**Comment by vJechsmayr** [comment]
Merged
