### ISSUE TITLE
0273 - Integer to English Words

### ISSUE THREAD

**Issue by na-vural** [vJechsmayr/PythonAlgorithms#599]
## Description of the Problem
Convert a non-negative integer to its english words representation. Given input is guaranteed to be less than 2**31 - 1.

**Example 1:**
```
Input: 123
Output: "One Hundred Twenty Three"
```
**Example 2:**
```
Input: 12345
Output: "Twelve Thousand Three Hundred Forty Five"
```
**Example 3:**
```
Input: 1234567
Output: "One Million Two Hundred Thirty Four Thousand Five Hundred Sixty Seven"
```
**Example 4:**
```
Input: 1234567891
Output: "One Billion Two Hundred Thirty Four Million Five Hundred Sixty Seven Thousand Eight Hundred Ninety One"
```

## Code
```
class Solution(object):
    def numberToWords(self, num: int) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/integer-to-english-words)

**Comment by na-vural** [comment]
I want to solve this one. May you assign me?

**Comment by arindam9999** [comment]
@na-vural I would like to work on this issue, could you please assign it to me?

**Comment by shanemin** [comment]
I'd also like this issue

**Comment by na-vural** [comment]
You can select another problem from [LeetCode](https://leetcode.com/problemset/algorithms) for working on. After selecting a problem from [LeetCode](https://leetcode.com/problemset/algorithms/), you should check whether an issue about the problem was opened or not. If there is no issue about the problem, you can create a new issue and work on it.

**Comment by vJechsmayr** [comment]
@na-vural Waiting for your PR
