### ISSUE TITLE
0006 - ZigZag Conversion

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#6]
The string `"PAYPALISHIRING"` is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)

```
P   A   H   N
A P L S I I G
Y   I   R
```
And then read line by line: `"PAHNAPLSIIGYIR"`

Write the code that will take a string and make this conversion given a number of rows:

`string convert(string s, int numRows);`

**Example 1:**
```
Input: s = "PAYPALISHIRING", numRows = 3
Output: "PAHNAPLSIIGYIR"
```

**Example 2:**
```
Input: s = "PAYPALISHIRING", numRows = 4
Output: "PINALSIGYAHRPI"
Explanation:

P     I    N
A   L S  I G
Y A   H R
P     I
```

**Comment by adamcakg** [comment]
Hello, Can you assign me to this ?

**Comment by vJechsmayr** [comment]
@adamcakg Are you still working on this or can I unassign you?

**Comment by HOD101s** [comment]
@adamcakg kindly update as I would like to work on this problem

**Comment by Achyut-sudo** [comment]
Can i work on this

**Comment by Achyut-sudo** [comment]
i have already worked on a copy of this issue #476  ant his #513 was submitted to that issue and even  if i have made all the requirements  that pr got closed by the onwer

**Comment by Achyut-sudo** [comment]
I have added this pr (#513 ) to an issue (#476 ) which was a copy of this issue so  it was closed by @vJechsmayr 
and hence my pr was closed 
so I am adding a new pr here

**Comment by vJechsmayr** [comment]
@Achyut-sudo Please Read Contribution Guidelines! Do not open an PR when you are not assigned to the Issue!

**Comment by Achyut-sudo** [comment]
hey, @vJechsmayr  if @adamcakg is not working on this, can you assign me to this ???
I have a standing solution
