### ISSUE TITLE
0867 - Transpose Matrix

### ISSUE THREAD

**Issue by zeborg** [vJechsmayr/PythonAlgorithms#612]
## Description of the Problem
Problem: Given a matrix A, return the transpose of A. The transpose of a matrix is the matrix flipped over it's main diagonal, switching the row and column indices of the matrix.

**Sample input:**
    [[1,2,3],
     [4,5,6],
     [7,8,9]]

**Sample output:**
    [[1,4,7],
     [2,5,8],
     [3,6,9]]

## Code
```
class Solution:
    def transpose(self, A: List[List[int]]) -> List[List[int]]:
        transpose=[]
        k=0
        for p in range(len(A[0])):
            temp=[]
            for i in A:
                while k<len(i):
                    temp.append(i[k])
                    break
            transpose.append(temp)
            k+=1
        return transpose
```

## Link To The LeetCode Problem
[LeetCode Problem 0867](https://leetcode.com/problems/transpose-matrix/)

**Comment by Curious-Ujjwal** [comment]
If this issue is yet opened, can it be assigned to me.
Thank You!

**Comment by zeborg** [comment]
> If this issue is yet opened, can it be assigned to me.
> Thank You!

Hey @Curious-Ujjwal , although I haven't been assigned to this issue yet, I've already made a commit since I've already solved this problem on LeetCode about an year and a half ago. If the maintainer feels like there's any flaw in my code, I believe you can further work on it.

Thanks for your interest though.
