### ISSUE TITLE
0155 - Min Stack

### ISSUE THREAD

**Issue by kevinbeirne1** [vJechsmayr/PythonAlgorithms#615]
## Description of the Problem
Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.

push(x) -- Push element x onto stack.
pop() -- Removes the element on top of the stack.
top() -- Get the top element.
getMin() -- Retrieve the minimum element in the stack.
 

Example 1:

Input
["MinStack","push","push","push","getMin","pop","top","getMin"]
[[],[-2],[0],[-3],[],[],[],[]]

Output
[null,null,null,null,-3,null,0,-2]

Explanation
MinStack minStack = new MinStack();
minStack.push(-2);
minStack.push(0);
minStack.push(-3);
minStack.getMin(); // return -3
minStack.pop();
minStack.top();    // return 0
minStack.getMin(); // return -2
 

Constraints:

Methods pop, top and getMin operations will always be called on non-empty stacks.

## Code
```
class MinStack:

    def __init__(self):
        """
        initialize your data structure here.
        """
        self.stack = []


    def push(self, x: int) -> None:
        self.stack.append(x)
        

    def pop(self) -> None:
        self.stack.pop() # = self.stack[:-1] #pop()
        

    def top(self) -> int:
        return self.stack[-1]
    
        

    def getMin(self) -> int:
        return min(self.stack)
        


# Your MinStack object will be instantiated and called as such:
# obj = MinStack()
# obj.push(x)
# obj.pop()
# param_3 = obj.top()
# param_4 = obj.getMin()
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/min-stack/)

**Comment by javmarina** [comment]
Can you assign it to me? I can optimize

**Comment by Curious-Ujjwal** [comment]
Hey @kevin454475  I want to work on this issue.
Please assign this to me.

**Comment by flick-23** [comment]
Please assign this to me. I will do it!
