### ISSUE TITLE
0345 - Reverse Vowels of a String

### ISSUE THREAD

**Issue by anqkhieu** [vJechsmayr/PythonAlgorithms#619]
## Description of the Problem
Write a function that takes a string as input and reverse only the vowels of a string.

Example 1:
```
Input: "hello"
Output: "holle"
```

Example 2:
```
Input: "leetcode"
Output: "leotcede"
Note: The vowels does not include the letter "y".
```

## Code
```
class Solution(object):
    def reverseVowels(self, s):
        """
        :type s: str
        :rtype: str
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/reverse-vowels-of-a-string/)

I would like to contribute the code to this issue please.

**Comment by anqkhieu** [comment]
Would like to take this problem above please.

**Comment by DeepanshuGOYAL05** [comment]
Hey, can you assign this to me?

**Comment by ZarghamDanial** [comment]
Hey, is this issue open?

**Comment by vJechsmayr** [comment]
@anqkhieu 
Waiting for your PR 😸
