### ISSUE TITLE
0445 - Add Two Numbers II

### ISSUE THREAD

**Issue by frank731** [vJechsmayr/PythonAlgorithms#629]
## Description of the Problem
You are given two non-empty linked lists representing two non-negative integers. The most significant digit comes first and each of their nodes contain a single digit. Add the two numbers and return it as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.

## Code
class Solution:
    def addTwoNumbers(self, l1: ListNode, l2: ListNode) -> ListNode:

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/add-two-numbers-ii/)

**Comment by frank731** [comment]
I can do this problem

**Comment by TechLead-War** [comment]
I have done this issue.

**Comment by frank731** [comment]
> I have done this issue.

Oh oops, I didn't think that 0002 would be this problem, sorry about that

**Comment by frank731** [comment]
Wait I just realized that the two questions are slightly different, where one the lists are reversed and this one they aren't.  If you can link me your issue then I'll reclose it.
