### ISSUE TITLE
0025 - Reverse Nodes in k-Group

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#63]
## Description of the Problem
Given a linked list, reverse the nodes of a linked list _k_ at a time and return its modified list.

_k_ is a positive integer and is less than or equal to the length of the linked list. If the number of nodes is not a multiple of _k_ then left-out nodes in the end should remain as it is.

**Example:**
Given this linked list: `1->2->3->4->5`
For _k = 2_, you should return: `2->1->4->3->5`
For _k = 3_, you should return: `3->2->1->4->5`

**Note:**
- Only constant extra memory is allowed.
- You may not alter the values in the list's nodes, only nodes itself may be changed.

##Code
```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def reverseKGroup(self, head: ListNode, k: int) -> ListNode:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/reverse-nodes-in-k-group/)

**Comment by pikachu28** [comment]
Can you assign this to me ?
