### ISSUE TITLE
0338 - Counting Bits

### ISSUE THREAD

**Issue by iamsnj** [vJechsmayr/PythonAlgorithms#631]
## Description of the Problem
Given a non negative integer number num. For every numbers i in the range 0 ≤ i ≤ num calculate the number of 1's in their binary representation and return them as an array.

## Code
```
class Solution:
    def countBits(self, num: int) -> List[int]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/counting-bits/)

**Comment by iamsnj** [comment]
I would like to work on this issue.
Please assign it to me.
Thanks :)

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)

**Comment by vJechsmayr** [comment]
Problem already solved
