### ISSUE TITLE
0202 - Happy Number

### ISSUE THREAD

**Issue by mdbrnowski** [vJechsmayr/PythonAlgorithms#633]
## Description of the Problem
Write an algorithm to determine if a number n is "happy".

A happy number is a number defined by the following process: Starting with any positive integer, replace the number by the sum of the squares of its digits, and repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1. Those numbers for which this process ends in 1 are happy numbers.

Return True if n is a happy number, and False if not.

## Code
```
class Solution(object):
    def isHappy(self, n):
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/happy-number/)

**Comment by sethitushar** [comment]
I would like to try this issue. Please assign it to me!!
Thanks.

**Comment by DeepanshuGOYAL05** [comment]
Hey, I am here with the solution

**Comment by DeepanshuGOYAL05** [comment]
Can i do it in java?

**Comment by BirajCoder** [comment]
I would like to contribute to this issue, Please Assign it to me .

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)
