### ISSUE TITLE
0204 - Count Primes

### ISSUE THREAD

**Issue by mdbrnowski** [vJechsmayr/PythonAlgorithms#635]
## Description of the Problem
Count the number of prime numbers less than a non-negative number, `n`.

## Code
```
class Solution(object):
    def countPrimes(self, n):
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/count-primes/)

**Comment by sethitushar** [comment]
I would like to work on this issue. Please assign it to me!

**Comment by BirajCoder** [comment]
I would like to contribute to this issue, Please Assign it to me! Thanks

**Comment by PraneshUlleri** [comment]
I would like to contribute to this issue!

**Comment by likipreetham145** [comment]
I would like to contribute to this issue

**Comment by flick-23** [comment]
Please assign this to me. I will do it!

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)

**Comment by IsuruAriyarathne** [comment]
I would like to contribute.

**Comment by vJechsmayr** [comment]
Problem already solved
