### ISSUE TITLE
1550 - Three Consecutive Odds

### ISSUE THREAD

**Issue by BirajCoder** [vJechsmayr/PythonAlgorithms#637]
## Description of the Problem
Given an integer array arr, return true if there are three consecutive odd numbers in the array. Otherwise, return false.

## Code
```
class Solution:
    def threeConsecutiveOdds(self, arr: List[int]) -> bool:
```

## Example 1: 
```
Input: arr = [2,6,4,1]
Output: false
Explanation: There are no three consecutive odds.
```

## Example 2:
```
Input: arr = [1,2,34,3,4,5,7,23,12]
Output: true
Explanation: [5,7,23] are three consecutive odds.
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/three-consecutive-odds/)

**Comment by BirajCoder** [comment]
I would like to work on this Issue ,
Please Assign this to me ,
Thank You.

**Comment by BirajCoder** [comment]
I would like to work in this issue , Maintainer please assign this issue to me , Thank You.

**Comment by flick-23** [comment]
Please assign this to me. I will do it!

**Comment by vJechsmayr** [comment]
@BirajCoder 
Waiting for your PR 😸

**Comment by BirajCoder** [comment]
Sure, I will be uploading my code tomorrow as I am out of station for the day.
