### ISSUE TITLE
0891 - Sum of Subsequence Widths

### ISSUE THREAD

**Issue by na-vural** [vJechsmayr/PythonAlgorithms#639]
## Description of the Problem
Given an array of integers `A`, consider all non-empty subsequences of `A`.

For any sequence S, let the width of S be the difference between the maximum and minimum element of S.

Return the sum of the widths of all subsequences of `A`. 

As the answer may be very large, **return the answer modulo 10^9 + 7**.

 

**Example 1:**
```
Input: [2,1,3]
Output: 6
Explanation:
Subsequences are [1], [2], [3], [2,1], [2,3], [1,3], [2,1,3].
The corresponding widths are 0, 0, 0, 1, 1, 2, 2.
The sum of these widths is 6.
```
 
**Note:**
```
    1 <= A.length <= 20000
    1 <= A[i] <= 20000
```

## Code
```
class Solution(object):
    def sumSubseqWidths(self, A: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/sum-of-subsequence-widths/)

**Comment by na-vural** [comment]
I want to solve this. Can you assign me :)

**Comment by sumitmohite0501** [comment]
I have solve this. see my commit 79a039a9fc4d906bfc23455f356a5f555de22489

**Comment by na-vural** [comment]
Which issue about the problem is yours? I did not find another issue about this problem. I also solved this problem but I am waiting for being assigned. Please read the rules before contributing.

**Comment by vJechsmayr** [comment]
@na-vural 
Waiting for your PR 😸
