### ISSUE TITLE
0028 - Implement strStr()

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#64]
## Description of the Problem
Implement _strStr()._

Return the index of the first occurrence of needle in haystack, or **-1** if needle is not part of haystack.

**Example 1:**
```
Input: haystack = "hello", needle = "ll"
Output: 2
```

**Example 2:**
```
Input: haystack = "aaaaa", needle = "bba"
Output: -1
```

**Clarification:**
What should we return when `needle `is an empty string? This is a great question to ask during an interview.
For the purpose of this problem, we will return 0 when `needle `is an empty string. This is consistent to C's `strstr() `and Java's` indexOf()`.

**Constraints:**
`haystack ` and  `needle ` consist only of lowercase English characters.

## Code
```
class Solution:
    def strStr(self, haystack: str, needle: str) -> int:
```    

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/implement-strstr/)

**Comment by devanshi-katyal** [comment]
I would like to work on this issue!

**Comment by satyamasthanaa** [comment]
I would like to solve this. Can you please assign this issue to me?

**Comment by vJechsmayr** [comment]
@devanshi-katyal Are you still working on this, or can I unassign you?

**Comment by va3ndf** [comment]
I have a solution ready to go.

**Comment by prackode** [comment]
Please assign it to me. I have a solution.
