### ISSUE TITLE
0260 - Single-number-III

### ISSUE THREAD

**Issue by aditya113141** [vJechsmayr/PythonAlgorithms#644]
## Description of the Problem
Given an integer array nums, in which exactly two elements appear only once and all the other elements appear exactly twice. Find the two elements that appear only once. You can return the answer in any order.

## Code
```
class Solution:
    def singleNumber(self, nums: List[int]) -> List[int]:
Code
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/single-number-iii/)

**Comment by aditya113141** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)

**Comment by flick-23** [comment]
Please assign this to me. I will do it!
