### ISSUE TITLE
0122. Best Time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by tejasbirsingh** [vJechsmayr/PythonAlgorithms#650]
## Description of the Problem
Say you have an array prices for which the ith element is the price of a given stock on day i.

Design an algorithm to find the maximum profit. You may complete as many transactions as you like (i.e., buy one and sell one share of the stock multiple times).

Note: You may not engage in multiple transactions at the same time (i.e., you must sell the stock before you buy again).

Example 1:

Input: [7,1,5,3,6,4]
Output: 7
Explanation: Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4.
             Then buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-3 = 3.

## Code
```
    def maxProfit(self, prices: List[int]) -> int:
        
        s =0
        for i in range(1,len(prices)):
            if prices[i]> prices[i-1]:
                s +=prices[i]-prices[i-1]
        return s
```

## Link To The LeetCode Problem
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/

I would like to contribute well commented and explained code for this problem. Thanks

**Comment by goodgodth** [comment]
Please assign this issue to me

**Comment by vJechsmayr** [comment]
@tejasbirsingh Waiting for your PR 😸
