### ISSUE TITLE
1299 - Replace Elements with Greatest Element on Right Side

### ISSUE THREAD

**Issue by sethitushar** [vJechsmayr/PythonAlgorithms#652]
## Description of the Problem
Given an array arr, replace every element in that array with the greatest element among the elements to its right, and replace the last element with -1.

After doing so, return the array.

Constraints:

1 <= arr.length <= 10^4
1 <= arr[i] <= 10^5

## Code
class Solution(object):
    def replaceElements(self, arr):

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/replace-elements-with-greatest-element-on-right-side/)

**Comment by sethitushar** [comment]
I want to work on this issue. Please assign it to me. Thanks!

**Comment by vJechsmayr** [comment]
Problem already solved
