### ISSUE TITLE
0127 - Word Ladder

### ISSUE THREAD

**Issue by dongwon900** [vJechsmayr/PythonAlgorithms#653]
## Description of the Problem
Given two words (beginWord and endWord), and a dictionary's word list, find the length of shortest transformation sequence from beginWord to endWord, such that:
1. Only one letter can be changed at a time.
2. Each transformed word must exist in the word list.

Note:
- Return 0 if there is no such transformation sequence.
- All words have the same length.
- All words contain only lowercase alphabetic characters.
- You may assume no duplicates in the word list.
- You may assume beginWord and endWord are non-empty and are not the same.

## Code
```
class Solution(object):
    def ladderLength(self, beginWord, endWord, wordList):
        """
        :type beginWord: str
        :type endWord: str
        :type wordList: List[str]
        :rtype: int
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/word-ladder/)

**Comment by dongwon900** [comment]
I would like to be assigned to this issue. Thanks!

**Comment by vJechsmayr** [comment]
@dongwon900 
Waiting for your PR 😸
