### ISSUE TITLE
0014 - Longest Common Prefix

### ISSUE THREAD

**Issue by grpnpraveen** [vJechsmayr/PythonAlgorithms#660]
## Description of the Problem
Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

## Code
```
class Solution:
    def longestCommonPrefix(self, strs):
        """
        :type strs: List[str]
        :rtype: str
        """
        if len(strs) == 0:
            return '' 
        res = ''
        strs = sorted(strs)
        for i in strs[0]:
            if strs[-1].startswith(res+i):
                res += i
            else:
                break
        return res
Code
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/longest-common-prefix/)

**Comment by Famosi** [comment]
@grpnpraveen  Would like to work on this!

**Comment by grpnpraveen** [comment]
Actually its done but say if there is any mistake pls

**Comment by Famosi** [comment]
The related PR is #433.
However, #433 is closed since it doesn't respect contributing guidelines.
Let me know if I can work on this issue by assigning me to the issue. 
Thanks :)

**Comment by grpnpraveen** [comment]
oh sry but i  included two py files  in this pull request

**Comment by Famosi** [comment]
Hi @grpnpraveen! So, can I work on this or not?
