### ISSUE TITLE
1436 - Destination City

### ISSUE THREAD

**Issue by sethitushar** [vJechsmayr/PythonAlgorithms#664]
## Description of the Problem
You are given the array paths, where paths[i] = [cityAi, cityBi] means there exists a direct path going from cityAi to cityBi. Return the destination city, that is, the city without any path outgoing to another city.

It is guaranteed that the graph of paths forms a line without any loop, therefore, there will be exactly one destination city.

## Code
```
class Solution(object):
    def destCity(self, paths):
        """
        :type paths: List[List[str]]
        :rtype: str
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/destination-city/)

**Comment by sethitushar** [comment]
I would to like to solve this problem. Please assign this to me. Thanks

**Comment by PraneshUlleri** [comment]
I would like to solve this issue

**Comment by vJechsmayr** [comment]
Problem solved
