### ISSUE TITLE
0032 - Longest Valid Parentheses

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#67]
## Description of the Problem
Given a string containing just the characters `'('` and `')'`, find the length of the longest valid (well-formed) parentheses substring.

**Example 1:**
```
Input: "(()"
Output: 2
Explanation: The longest valid parentheses substring is "()"
```

**Example 2:**
```
Input: ")()())"
Output: 4
Explanation: The longest valid parentheses substring is "()()"
```

## Code
```
class Solution:
    def longestValidParentheses(self, s: str) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/longest-valid-parentheses/)

**Comment by aewens** [comment]
I'll give this one a try.
