### ISSUE TITLE
1424 - Diagonal Traverse II

### ISSUE THREAD

**Issue by Vinit-Dantkale** [vJechsmayr/PythonAlgorithms#672]
## Description of the Problem
Given a list of lists of integers, `nums`, return all elements of `nums` in diagonal order as shown in the below images.

## Code
```
class Solution:
    def findDiagonalOrder(self, nums: List[List[int]]) -> List[int]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/diagonal-traverse-ii/)

**Comment by Vinit-Dantkale** [comment]
I want to work on this

**Comment by vJechsmayr** [comment]
@Vinit-Dantkale 
Waiting for your PR 😸

**Comment by Vinit-Dantkale** [comment]
Hey @vJechsmayr , I might be unavailable. Please feel free to close or assign someone else (or put an **Available** tag so someone else can take it).
Thanks 👍
