### ISSUE TITLE
0783 - Minimum Distance Between BST Nodes

### ISSUE THREAD

**Issue by sj538** [vJechsmayr/PythonAlgorithms#675]
## Description of the Problem
Minimum Distance Between BST Nodes

## Code
Given a Binary Search Tree (BST) with the root node root, return the minimum difference between the values of any two different nodes in the tree.

Example :

Input: root = [4,2,6,1,3,null,null]
Output: 1
Explanation:
Note that root is a TreeNode object, not an array.

The given tree [4,2,6,1,3,null,null] is represented by the following diagram:

          4
        /   \
      2      6
     / \    
    1   3  

while the minimum difference in this tree is 1, it occurs between node 1 and node 2, also between node 3 and node 2.
Code
```

## Link To The LeetCode Problem
https://leetcode.com/problems/minimum-distance-between-bst-nodes/

**Comment by sj538** [comment]
Please assign me this  issue

**Comment by vJechsmayr** [comment]
Problem already solved

**Comment by vJechsmayr** [comment]
@jindalsachin 
Waiting for your PR 😸
