### ISSUE TITLE
0744 -  Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by sj538** [vJechsmayr/PythonAlgorithms#676]
## Description of the Problem
 Find Smallest Letter Greater Than Target

## Code
Given a list of sorted characters letters containing only lowercase letters, and given a target letter target, find the smallest element in the list that is larger than the given target.

Letters also wrap around. For example, if the target is target = 'z' and letters = ['a', 'b'], the answer is 'a'.

Examples:
Input:
letters = ["c", "f", "j"]
target = "a"
Output: "c"

Input:
letters = ["c", "f", "j"]
target = "c"
Output: "f"
Code
```

## Link To The LeetCode Problem
https://leetcode.com/problems/find-smallest-letter-greater-than-target/

**Comment by sj538** [comment]
Please assign me this issue

**Comment by vJechsmayr** [comment]
@jindalsachin 
Waiting for your PR 😸
