### ISSUE TITLE
0205 - Isomorphic Strings

### ISSUE THREAD

**Issue by Vinit-Dantkale** [vJechsmayr/PythonAlgorithms#679]
## Description of the Problem
Given two strings s and t, determine if they are isomorphic.

Two strings are isomorphic if the characters in s can be replaced to get t.

All occurrences of a character must be replaced with another character while preserving the order of characters. No two characters may map to the same character but a character may map to itself.

## Code
```
class Solution:
    def isIsomorphic(self, s: str, t: str) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/isomorphic-strings/)

**Comment by Vinit-Dantkale** [comment]
I want to work on this

**Comment by vJechsmayr** [comment]
@Vinit-Dantkale 
Waiting for your PR 😸

**Comment by Vinit-Dantkale** [comment]
Hey @vJechsmayr , I might be unavailable. Please feel free to close or assign someone else (or put an **Available** tag so someone else can take it).
Thanks 👍
