### ISSUE TITLE
0942 - DI String Match

### ISSUE THREAD

**Issue by wafemand** [vJechsmayr/PythonAlgorithms#680]
## Description of the Problem
Given a string S that only contains "I" (increase) or "D" (decrease), let `N = S.length`.

Return any permutation `A` of `[0, 1, ..., N]` such that for all `i = 0, ..., N-1`:

If `S[i] == "I"`, then `A[i] < A[i+1]`
If `S[i] == "D"`, then `A[i] > A[i+1]`

## Code
```
class Solution:
    def diStringMatch(self, S: str) -> List[int]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/di-string-match/)

**Comment by andjelatodorovic** [comment]
I will do this problem. Please assign me to avoid conflicts.

**Comment by wafemand** [comment]
> I will do this problem. Please assign me to avoid conflicts.

Sorry, but the problem already solved. See pull request above. I'm just waiting for merge.
