### ISSUE TITLE
0067 - Add Binary  

### ISSUE THREAD

**Issue by grpnpraveen** [vJechsmayr/PythonAlgorithms#682]
## Description of the Problem
Given two binary strings, return their sum (also a binary string).

The input strings are both non-empty and contains only characters 1 or 0.

## Code
```
class Solution:
    def addBinary(self, a: str, b: str) -> str:
        sum = int(a,2) + int(b,2)
        return bin(sum)[2:]

Code
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/add-binary/)

**Comment by Sounakde** [comment]
I would like to be assigned to this issue.

**Comment by grpnpraveen** [comment]
sry but this is solved

**Comment by vJechsmayr** [comment]
Problem already solved
