### ISSUE TITLE
0167 - Two Sum II - Input array is sorted

### ISSUE THREAD

**Issue by krypticmouse** [vJechsmayr/PythonAlgorithms#689]
## Description of the Problem
Given an array of integers that is already sorted in ascending order, find two numbers such that they add up to a specific target number.
The function twoSum should return indices of the two numbers such that they add up to the target, where index1 must be less than index2.

## Code
```python
class Solution:
    def twoSum(self, numbers: List[int], target: int) -> List[int]:
        for x in numbers:
            if x > target:
                break
            else:
                if target - x == x:
                    return (numbers.index(x)+1,numbers.index(x)+2)
                else:
                    if target - x in numbers:
                        return(numbers.index(x)+1,numbers.index(target - x)+1)
```
## Link To The LeetCode Problem
https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/

**Comment by TheFenrisLycaon** [comment]
I can do this. Assign to me
