### ISSUE TITLE
0746 - Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by spoorgholi74** [vJechsmayr/PythonAlgorithms#694]
## Description of the Problem
On a staircase, the i-th step has some non-negative cost cost[i] assigned (0 indexed).

Once you pay the cost, you can either climb one or two steps. You need to find minimum cost to reach the top of the floor, and you can either start from the step with index 0, or the step with index 1.

## Code
```
class Solution:
    def minCostClimbingStairs(self, cost: List[int]) -> int:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/min-cost-climbing-stairs/)

**Comment by spoorgholi74** [comment]
Please assign this to me.

Cheers

**Comment by ankitsri98** [comment]
Please Assign this Doubt To me i will try To Response as soon as Possible.
Thank You

**Comment by vJechsmayr** [comment]
Problem already solved
