### ISSUE TITLE
0371 - Sum of Two Integers

### ISSUE THREAD

**Issue by spoorgholi74** [vJechsmayr/PythonAlgorithms#695]
## Description of the Problem
Calculate the sum of two integers a and b, but you are not allowed to use the operator + and -.

## Code
```
class Solution:
    def getSum(self, a: int, b: int) -> int:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/sum-of-two-integers/)

**Comment by spoorgholi74** [comment]
Please assign this to me.

**Comment by ankitsri98** [comment]
Please Assign this Problem To me i am sure i can do it.
thank you.

**Comment by eg180** [comment]
Interested in trying. Thank you.

**Comment by flick-23** [comment]
Please assign this problem to me.

**Comment by vJechsmayr** [comment]
@spoorgholi74 Waiting for your PR 😸
