### ISSUE TITLE
0168 - Excel Sheet Column Title

### ISSUE THREAD

**Issue by poojan-dalal** [vJechsmayr/PythonAlgorithms#697]
## Description of the Problem
Given a positive integer, return its corresponding column title as appear in an Excel sheet.

For example:
    1 -> A
    2 -> B
    3 -> C
    ...
    26 -> Z
    27 -> AA
    28 -> AB 
    ...

Example 1:

Input: 1
Output: "A"
Example 2:

Input: 28
Output: "AB"
Example 3:

Input: 701
Output: "ZY"

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/excel-sheet-column-title/)

@vJechsmayr Please assign this to me. Will send the PR.

**Comment by poojan-dalal** [comment]
@vJechsmayr Please assign this to me.

**Comment by flick-23** [comment]
Please assign this to me. I will do it!

**Comment by vJechsmayr** [comment]
@poojan-dalal Waiting for your PR 😸
