### ISSUE TITLE
0543 - Diameter of Binary Tree

### ISSUE THREAD

**Issue by Vinit-Dantkale** [vJechsmayr/PythonAlgorithms#698]
## Description of the Problem
Given a binary tree, you need to compute the length of the diameter of the tree. The diameter of a binary tree is the length of the longest path between any two nodes in a tree. This path may or may not pass through the root.

## Code
```
class Solution:
    def diameterOfBinaryTree(self, root: TreeNode) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/diameter-of-binary-tree/)

**Comment by Vinit-Dantkale** [comment]
I wish to work on this

**Comment by vJechsmayr** [comment]
@Vinit-Dantkale Waiting for your PR 😸

**Comment by Vinit-Dantkale** [comment]
Hey @vJechsmayr , I might be unavailable. Please feel free to close or assign someone else (or put an **Available** tag so someone else can take it).
Thanks 👍
