### ISSUE TITLE
0223 - Rectangle Area

### ISSUE THREAD

**Issue by poojan-dalal** [vJechsmayr/PythonAlgorithms#699]
## Description of the Problem
Find the total area covered by two rectilinear rectangles in a 2D plane.

Each rectangle is defined by its bottom left corner and top right corner as shown in the figure.
[Image here](https://assets.leetcode.com/uploads/2018/10/22/rectangle_area.png)

Example:

Input: A = -3, B = 0, C = 3, D = 4, E = 0, F = -1, G = 9, H = 2
Output: 45

Note:

Assume that the total area is never beyond the maximum possible value of int.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/)

@vJechsmayr Please assign me this.

**Comment by poojan-dalal** [comment]
@vJechsmayr Please assign me this.

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)

**Comment by vJechsmayr** [comment]
@poojan-dalal Waiting for your PR 😸
