### ISSUE TITLE
0389 - Find The Difference

### ISSUE THREAD

**Issue by Sounakde** [vJechsmayr/PythonAlgorithms#702]
## Description of the Problem
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
 
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Example 3:
Input: s = "a", t = "aa"
Output: "a"

Example 4:
Input: s = "ae", t = "aea"
Output: "a"
 
Constraints:

- 0 <= s.length <= 1000
- t.length == s.length + 1
- s and t consist of lower-case English letters.

Code
```
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
```
## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/find-the-difference/)

**Comment by Sounakde** [comment]
@vJechsmayr Can you please assign this issue to me?

**Comment by prkhrv** [comment]
@vJechsmayr  I would Love to work on this

**Comment by Deepak2417** [comment]
I want to contribute.

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)

**Comment by vJechsmayr** [comment]
@Sounakde Waiting for your PR 😸

**Comment by Sounakde** [comment]
@vJechsmayr Can you help me with PR build issue. The PR no is #799  .
