### ISSUE TITLE
0334 - Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by deekal7** [vJechsmayr/PythonAlgorithms#704]
## Description of the Problem
Given an unsorted array return whether an increasing subsequence of length 3 exists or not in the array.

Formally the function should:

Return true if there exists i, j, k
such that arr[i] < arr[j] < arr[k] given 0 ≤ i < j < k ≤ n-1 else return false.
Note: Your algorithm should run in O(n) time complexity and O(1) space complexity.

Example 1:

Input: [1,2,3,4,5]
Output: true

Example 2:

Input: [5,4,3,2,1]
Output: false

## Code
```
class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        first = second = float('inf')
        for n in nums:
            if n <= first:
                first = n
            elif n <= second:
                second = n
            else:
                return True
        return False        
```

## Link To The LeetCode Problem
[Increasing Triplet Subsequence](https://leetcode.com/problems/increasing-triplet-subsequence/)

**Comment by deekal7** [comment]
Please assign this to me

**Comment by vJechsmayr** [comment]
@deekal7 Waiting for your PR 😸
