### ISSUE TITLE
0034 - Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#71]
## Description of the Problem
Given an array of integers `nums `sorted in ascending order, find the starting and ending position of a given `target `value.

Your algorithm's runtime complexity must be in the order of O(log n).

If the target is not found in the array, return `[-1, -1]`.

**Example 1:**
```
Input: nums = [5,7,7,8,8,10], target = 8
Output: [3,4]
```

**Example 2:**
```
Input: nums = [5,7,7,8,8,10], target = 6
Output: [-1,-1]
```
 
**Constraints:**

- `0 <= nums.length <= 10^5`
- `-10^9 <= nums[i] <= 10^9`
- `nums `is a non decreasing array.
- `-10^9 <= target <= 10^9`

## Code
```
class Solution:
    def searchRange(self, nums: List[int], target: int) -> List[int]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/)

**Comment by araut1** [comment]
Can I help with this one?

**Comment by megabyte98** [comment]
you can use binary search for this problem

**Comment by megabyte98** [comment]
can I help you with this issue?
