### ISSUE TITLE
00## - Check if a number is prime

### ISSUE THREAD

**Issue by morenocl** [vJechsmayr/PythonAlgorithms#710]
## Description of the Problem
Check that a number is prime

## Code
```
Input: 7
Output: 7 is  a prime number

Input: 8
Output: 8 is not a prime number
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/playground/U27rDXz6)

**Comment by ankitsri1998** [comment]
Please Assign this to me, I can do this efficiently.
Thank You.

**Comment by sumitmohite0501** [comment]
I have solve this problem . #738

**Comment by vJechsmayr** [comment]
Closed - Does not match Contribution Guidelines! Only LeetCode Problem accepted!
