### ISSUE TITLE
0316 - Remove Duplicate Letters

### ISSUE THREAD

**Issue by Shreejichandra** [vJechsmayr/PythonAlgorithms#711]
## Description of the Problem
Given a string s, remove duplicate letters so that every letter appears once and only once. You must make sure your result is the smallest in lexicographical order among all possible results.

## Example 1:
```
Input: s = "bcabc"
Output: "abc"
```
## Example 2:
```
Input: s = "cbacdcbc"
Output: "acdb"
 ```

## Constraints:
```
1 <= s.length <= 104
s consists of lowercase English letters.
```
## Code
```
class Solution:
    def removeDuplicateLetters(self, s: str) -> str:
   
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/remove-duplicate-letters/)

**Comment by ankitsri1998** [comment]
Please Assign this to me, I can do this efficiently.
Thank You.

**Comment by Shreejichandra** [comment]
I want to do this myself. Please assign it to me.
Thank you!

**Comment by vJechsmayr** [comment]
@Shreejichandra Waiting for your PR 😸
