### ISSUE TITLE
1661 - Check if a number is prime

### ISSUE THREAD

**Issue by morenocl** [vJechsmayr/PythonAlgorithms#713]
## Code
```
Input: 7
Output: 7 is  a prime number

Input: 8
Output: 8 is not a prime number
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/playground/U27rDXz6)

**Comment by ankitsri1998** [comment]
Please Assign this to me, I can do this efficiently.
Thank You.

**Comment by zer0link** [comment]
Hi, this seems like an interesting challenge, I like to be assigned for this task

**Comment by anikk7** [comment]
Hey! I am new to opensource so I could really use this opportunity well. I request you to assign this task to me!
I will include brief explanations if required

**Comment by princekhj555** [comment]
please assign this to me i'll do it.

**Comment by vJechsmayr** [comment]
Issue does not follow Contribution Guidelines - closed

Please make sure to only sumbit Issues from the [https://leetcode.com/problemset/all/](https://leetcode.com/problemset/all) list
