### ISSUE TITLE
0110 - Balanced Binary Tree

### ISSUE THREAD

**Issue by princesinghtomar** [vJechsmayr/PythonAlgorithms#720]
## Description of the Problem
Given a binary tree, determine if it is height-balanced.

For this problem, a height-balanced binary tree is defined as:

    a binary tree in which the left and right subtrees of every node differ in height by no more than 1.

 

Example 1:
Input: root = [3,9,20,null,null,15,7]
Output: true

Example 2:
Input: root = [1,2,2,3,3,null,null,4,4]
Output: false

Example 3:

Input: root = []
Output: true

 

Constraints:

    The number of nodes in the tree is in the range [0, 5000].
    -104 <= Node.val <= 104

## Code
```
# Definition for a binary tree node.
# class TreeNode(object):
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution(object):
    def isBalanced(self, root):
        """
        :type root: TreeNode
        :rtype: bool
        """
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/balanced-binary-tree/)

**Comment by princesinghtomar** [comment]
may i have this one

**Comment by vrbro** [comment]
Can I be assigned this issue?

**Comment by vJechsmayr** [comment]
@princesinghtomar Waiting for your PR 😸
