### ISSUE TITLE
0119 - Pascal's Triangle II

### ISSUE THREAD

**Issue by princesinghtomar** [vJechsmayr/PythonAlgorithms#721]
## Description of the Problem
Given an integer rowIndex, return the rowIndex_^{th} row of the Pascal's triangle.

Notice that the row index starts from 0.

In Pascal's triangle, each number is the sum of the two numbers directly above it.

Follow up:

Could you optimize your algorithm to use only O(k) extra space?

 

Example 1:

Input: rowIndex = 3
Output: [1,3,3,1]

Example 2:

Input: rowIndex = 0
Output: [1]

Example 3:

Input: rowIndex = 1
Output: [1,1]

 
Constraints:

    0 <= rowIndex <= 40

## Code
```
class Solution(object):
    def getRow(self, rowIndex):
        """
        :type rowIndex: int
        :rtype: List[int]
        """
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/pascals-triangle-ii/)

**Comment by princesinghtomar** [comment]
i want to do this one

**Comment by princesinghtomar** [comment]
please assgn this to me

**Comment by chiragbansal-45** [comment]
I would like to solve this issue

**Comment by AbhishekTiwari07** [comment]
#742

**Comment by AbhishekTiwari07** [comment]
#742
