### ISSUE TITLE
0144 - Binary Tree Preorder Traversal

### ISSUE THREAD

**Issue by princesinghtomar** [vJechsmayr/PythonAlgorithms#723]
## Description of the Problem
Given the root of a binary tree, return the preorder traversal of its nodes' values.

 

Example 1:

1 - 2 - 3

Input: root = [1,null,2,3]
Output: [1,2,3]

Example 2:
Input: root = []
Output: []

Example 3:
Input: root = [1]
Output: [1]

Example 4:

2 - 1

Input: root = [1,2]
Output: [1,2]

Example 5:

1 - 2

Input: root = [1,null,2]
Output: [1,2]

 

Constraints:

    The number of nodes in the tree is in the range [0, 100].
    -100 <= Node.val <= 100

## Code
```
# Definition for a binary tree node.
# class TreeNode(object):
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution(object):
    def preorderTraversal(self, root):
        """
        :type root: TreeNode
        :rtype: List[int]
        """
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/binary-tree-preorder-traversal/)

**Comment by princesinghtomar** [comment]
please assgn this issue to me

**Comment by Bhairavi-shah** [comment]
I would like to work on this. Please assign this to me.
