### ISSUE TITLE
1518 - Water Bottles

### ISSUE THREAD

**Issue by javmarina** [vJechsmayr/PythonAlgorithms#746]
## Description of the Problem

Given `numBottles` full water bottles, you can exchange `numExchange` empty water bottles for one full water bottle.

The operation of drinking a full water bottle turns it into an empty bottle.

Return the maximum number of water bottles you can drink.

## Code
```
class Solution(object):
    def numWaterBottles(self, numBottles, numExchange):
        """
        :type numBottles: int
        :type numExchange: int
        :rtype: int
        """
        full = numBottles
        empty = 0
        drank = 0
        
        while True:
            # 1. Drink
            empty += full
            drank += full
            full = 0
            
            # 2. Exchange
            while empty >= numExchange:
                empty -= numExchange
                full += 1
            
            if not full:
                break
        
        return drank
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/water-bottles/)

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before. I have solved this problem.
Hope to here you from soon :)

**Comment by javmarina** [comment]
I already proposed a solution
