### ISSUE TITLE
0212 - Word Search II

### ISSUE THREAD

**Issue by mkiglics** [vJechsmayr/PythonAlgorithms#749]
## Description of the Problem
Given a 2D board and a list of words from the dictionary, find all words in the board.

Each word must be constructed from letters of sequentially adjacent cell, where "adjacent" cells are those horizontally or vertically neighboring. The same letter cell may not be used more than once in a word.
__Example:__
```
Input: 
board = [
  ['o','a','a','n'],
  ['e','t','a','e'],
  ['i','h','k','r'],
  ['i','f','l','v']
]
words = ["oath","pea","eat","rain"]

Output: ["eat","oath"]
```
__Note:__

All inputs are consist of lowercase letters ```a-z```.
The values of ```words``` are distinct.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/word-search-ii/)

**Comment by mkiglics** [comment]
I would like to solve this

**Comment by reach-the-sky** [comment]
I would like to solve it please assign it to me.

**Comment by vJechsmayr** [comment]
@mkiglics Waiting for your PR 😸
