### ISSUE TITLE
0807 -  Max Increase to Keep City Skyline

### ISSUE THREAD

**Issue by aroradhruv2308** [vJechsmayr/PythonAlgorithms#752]
## Description of the Problem
In a 2 dimensional array grid, each value grid[i][j] represents the height of a building located there. We are allowed to increase the height of any number of buildings, by any amount (the amounts can be different for different buildings). Height 0 is considered to be a building as well. 

At the end, the "skyline" when viewed from all four directions of the grid, i.e. top, bottom, left, and right, must be the same as the skyline of the original grid. A city's skyline is the outer contour of the rectangles formed by all the buildings when viewed from a distance. See the following example.

What is the maximum total sum that the height of the buildings can be increased?

## Code
```
class Solution:
    def maxIncreaseKeepingSkyline(self, grid: List[List[int]]) -> int:
        maxInRows = [0] * len(grid)
        maxInColumns = [0] * len(grid)
       
        res = 0
    
        for indexRow in range(len(grid)):
            for indexColumn in range(len(grid)):
                if grid[indexRow][indexColumn] > maxInRows[indexRow]:
                    maxInRows[indexRow] = grid[indexRow][indexColumn]
                if grid[indexRow][indexColumn] > maxInColumns[indexColumn]:
                    maxInColumns[indexColumn] = grid[indexRow][indexColumn]
                    
        for indexRow in range(len(grid)):
            for indexColumn in range(len(grid)):
                toAdd = min(maxInColumns[indexColumn], maxInRows[indexRow]) - grid[indexRow][indexColumn] 
                if toAdd > 0:
                    res += toAdd
                    
        return res  
```

## Link To The LeetCode Problem
[LeetCode] https://leetcode.com/problems/max-increase-to-keep-city-skyline/

**Comment by aroradhruv2308** [comment]
pls assign this issue to me

**Comment by vJechsmayr** [comment]
@aroradhruv2308 Waiting for your PR 😸
