### ISSUE TITLE
0869 - Reordered Power of 2

### ISSUE THREAD

**Issue by conradojordan** [vJechsmayr/PythonAlgorithms#753]
## Description of the Problem
Starting with a positive integer N, we reorder the digits in any order (including the original order) such that the leading digit is not zero.

Return true if and only if we can do this in a way such that the resulting number is a power of 2.

## Code
```
class Solution:
    def reorderedPowerOf2(self, N: int) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/reordered-power-of-2/)

**Comment by conradojordan** [comment]
I would like to be assigned this issue, if possible

**Comment by vJechsmayr** [comment]
@conradojordan Waiting for your PR 😸
