### ISSUE TITLE
0035 - Search Insert Position

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#76]
## Description of the Problem
Given a sorted array and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You may assume no duplicates in the array.

**Example 1:**
```
Input: [1,3,5,6], 5
Output: 2
```

**Example 2:**
```
Input: [1,3,5,6], 2
Output: 1
```

**Example 3:**
```
Input: [1,3,5,6], 7
Output: 4
```

**Example 4:**
```
Input: [1,3,5,6], 0
Output: 0
```

## Code
```
class Solution:
    def searchInsert(self, nums: List[int], target: int) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/search-insert-position/)

**Comment by shubham2704** [comment]
@vJechsmayr i would like to work on this, please assign me this issue.
