### ISSUE TITLE
0859 - Buddy Strings

### ISSUE THREAD

**Issue by Shreejichandra** [vJechsmayr/PythonAlgorithms#762]
## Description of the Problem
Given two strings A and B of lowercase letters, return true if you can swap two letters in A so the result is equal to B, otherwise, return false.

Swapping letters is defined as taking two indices i and j (0-indexed) such that i != j and swapping the characters at A[i] and A[j]. For example, swapping at indices 0 and 2 in "abcd" results in "cbad".

 

## Example 1:
```
Input: A = "ab", B = "ba"
Output: true
Explanation: You can swap A[0] = 'a' and A[1] = 'b' to get "ba", which is equal to B.
```
## Example 2:
```
Input: A = "ab", B = "ab"
Output: false
Explanation: The only letters you can swap are A[0] = 'a' and A[1] = 'b', which results in "ba" != B.
```
## Example 3:
```
Input: A = "aa", B = "aa"
Output: true
Explanation: You can swap A[0] = 'a' and A[1] = 'a' to get "aa", which is equal to B.
```
## Example 4:
```
Input: A = "aaaaaaabc", B = "aaaaaaacb"
Output: true
```
## Example 5:
```
Input: A = "", B = "aa"
Output: false
 ```

## Constraints:
```
0 <= A.length <= 20000
0 <= B.length <= 20000
A and B consist of lowercase letters.
```

## Code
```
class Solution:
    def buddyStrings(self, A: str, B: str) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/buddy-strings/)

**Comment by IsuruAriyarathne** [comment]
can you please assign this to me.

**Comment by Shreejichandra** [comment]
I want to work on this myself. Please assign it to me.
Thank you!

**Comment by vJechsmayr** [comment]
@Shreejichandra Waiting for your PR 😸

**Comment by barrotsteindev** [comment]
Can you please assign it to me? @vJechsmayr
