### ISSUE TITLE
1284- Minimum Number of Flips to Convert Binary Matrix to Zero Matrix

### ISSUE THREAD

**Issue by suman2826** [vJechsmayr/PythonAlgorithms#768]
## Description of the Problem
Given a m x n binary matrix mat. In one step, you can choose one cell and flip it and all the four neighbours of it if they exist (Flip is changing 1 to 0 and 0 to 1). A pair of cells are called neighboors if they share one edge.

Return the minimum number of steps required to convert mat to a zero matrix or -1 if you cannot.

Binary matrix is a matrix with all cells equal to 0 or 1 only.

Zero matrix is a matrix with all cells equal to 0.

Example 1:
Input: mat = [[0,0],[0,1]]
Output: 3

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/minimum-number-of-flips-to-convert-binary-matrix-to-zero-matrix/)

**Comment by suman2826** [comment]
I would like to be assigned to this issue, Thank you!

**Comment by vJechsmayr** [comment]
@suman2826 Waiting for your PR 😸
