### ISSUE TITLE
0344 - Reverse String

### ISSUE THREAD

**Issue by IsuruAriyarathne** [vJechsmayr/PythonAlgorithms#773]
## Description of the Problem
Write a function that reverses a string. The input string is given as an array of characters char[].

Do not allocate extra space for another array, you must do this by modifying the input array in-place with O(1) extra memory.

You may assume all the characters consist of printable ascii characters.

Example 1:

Input: ["h","e","l","l","o"]
Output: ["o","l","l","e","h"]
Example 2:

Input: ["H","a","n","n","a","h"]
Output: ["h","a","n","n","a","H"]

## Code
class Solution:
    def reverseString(self, s: List[str]) -> None:
        """
        Do not return anything, modify s in-place instead.
        """

## Link To The LeetCode Problem
https://leetcode.com/problems/reverse-string/

**Comment by IsuruAriyarathne** [comment]
can you please assign this to me.

**Comment by Rahul171201** [comment]
can I take this up in C++?

**Comment by vJechsmayr** [comment]
@IsuruAriyarathne Waiting for your PR 😸

**Comment by vJechsmayr** [comment]
@Rahul171201 No only Python. And it's already assigned to Issue-Creator. So not your Issue :) Look for another

> can I take this up in C++?
