### ISSUE TITLE
0084 - Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by UdeshAthukorala** [vJechsmayr/PythonAlgorithms#776]
## Description of the Problem
Given n non-negative integers representing the histogram's bar height where the width of each bar is 1, find the area of largest rectangle in the histogram.

![image](https://user-images.githubusercontent.com/36252606/95841776-60175f80-0d63-11eb-9942-d49167b977e5.png)
_Above is a histogram where width of each bar is 1, given height = `[2,1,5,6,2,3]`._

![image](https://user-images.githubusercontent.com/36252606/95841924-8dfca400-0d63-11eb-93de-4cc00bf8e087.png)
_The largest rectangle is shown in the shaded area, which has area = `10` unit._

**Example:**

```
Input: [2,1,5,6,2,3]
Output: 10
```

## Code
```
class Solution:
    def largestRectangleArea(self, heights: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/largest-rectangle-in-histogram/)

**Comment by UdeshAthukorala** [comment]
@vJechsmayr Hey, I'd like to work on this problem. Can you please assign it to me?

**Comment by vJechsmayr** [comment]
@UdeshAthukorala Waiting for your PR 😸
