### ISSUE TITLE
0234 - Palindrome Linked List

### ISSUE THREAD

**Issue by flick-23** [vJechsmayr/PythonAlgorithms#789]
## Description of the Problem
Given a singly linked list, determine if it is a palindrome.

## Code

class Solution(object):
    
    def reverse(self, head):
        p = head.next
        while p and p.next:
            tmp = p.next
            p.next = p.next.next
            tmp.next = head.next
            head.next = tmp
            
    def isPalindrome(self, head):
        """
        :type head: ListNode
        :rtype: bool
        """
        
        #get middle pointer
        p1 = ListNode(0)
        p1.next = head
        p2 = p1
        while p2 and p2.next:
            p1 = p1.next
            p2 = p2.next.next
        
        # reverse second half of list
        self.reverse(p1)
        
        # check palindrome
        p1 = p1.next
        p2 = head
        while p1:
            if p1.val != p2.val:
                return False
            p1 = p1.next
            p2 = p2.next
        return True

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/palindrome-linked-list/)

**Comment by flick-23** [comment]
@vJechsmayr  Please assign me this problem

**Comment by vJechsmayr** [comment]
@flick-23 Waiting for your PR 😸

**Comment by flick-23** [comment]
> @flick-23 Waiting for y
