### ISSUE TITLE
0599 - Minimum Index Sum of Two Lists

### ISSUE THREAD

**Issue by chw9** [vJechsmayr/PythonAlgorithms#800]
## Description of the Problem
Suppose Andy and Doris want to choose a restaurant for dinner, and they both have a list of favorite restaurants represented by strings.

You need to help them find out their common interest with the least list index sum. If there is a choice tie between answers, output all of them with no order requirement. You could assume there always exists an answer.

## Code
```
class Solution(object):
    def findRestaurant(self, list1, list2):
        """
        :type list1: List[str]
        :type list2: List[str]
        :rtype: List[str]
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/minimum-index-sum-of-two-lists/submissions/)

**Comment by chw9** [comment]
Please assign me to this issue

**Comment by vJechsmayr** [comment]
@chw9 Waiting for your PR 😸
