### ISSUE TITLE
0217 - Contains Duplicate

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#84]
## Description of the Problem
Given an array of integers, find if the array contains any duplicates.

Your function should return true if any value appears at least twice in the array, and it should return false if every element is distinct.

**Example 1:**
```
Input: [1,2,3,1]
Output: true
```

**Example 2:**
```
Input: [1,2,3,4]
Output: false
```

**Example 3:**
```
Input: [1,1,1,3,3,4,3,2,4,2]
Output: true
```

## Code
```
class Solution:
    def containsDuplicate(self, nums: List[int]) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/contains-duplicate/)

**Comment by sarthak55k** [comment]
May i do it??

**Comment by rcchan** [comment]
I'd like to work on this

**Comment by saigunavanth** [comment]
@vJechsmayr I would like to work on this issue. Please assign me.

**Comment by Mayank662** [comment]
@vJechsmayr Sir, may I do this task in Python?

**Comment by sarthak55k** [comment]
Sir shall i do it in python or  some other language?
