### ISSUE TITLE
0219 - Contains Duplicate II

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#85]
## Description of the Problem
Given an array of integers and an integer k, find out whether there are two distinct indices i and j in the array such that **nums[i] = nums[j]** and the **absolute** difference between i and j is at most k.

**Example 1:**
```
Input: nums = [1,2,3,1], k = 3
Output: true
```

**Example 2:**
```
Input: nums = [1,0,1,1], k = 1
Output: true
```

**Example 3:**
```
Input: nums = [1,2,3,1,2,3], k = 2
Output: false
```

## Code
```
class Solution:
    def containsNearbyDuplicate(self, nums: List[int], k: int) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/contains-duplicate-ii/)

**Comment by rcchan** [comment]
I'd like to work on this

**Comment by saigunavanth** [comment]
@vJechsmayr I would like to work on this issue. Please assign me.

**Comment by Coolchirutha** [comment]
@vJechsmayr  I would like to work on this issue. I have worked on python and am currently learning advanced algorithms too.
