### ISSUE TITLE
0220 - Contains Duplicate III

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#86]
## Description of the Problem
Given an array of integers, find out whether there are two distinct indices i and j in the array such that the **absolute** difference between **nums[i]** and **nums[j]** is at most t and the **absolute** difference between i and j is at most k.

**Example 1:**
```
Input: nums = [1,2,3,1], k = 3, t = 0
Output: true
```

**Example 2:**
```
Input: nums = [1,0,1,1], k = 1, t = 2
Output: true
```

**Example 3:**
```
Input: nums = [1,5,9,1,5,9], k = 2, t = 3
Output: false
```
 
**Constraints:**
- `0 <= nums.length <= 2 * 104`
- `-231 <= nums[i] <= 231 - 1`
- `0 <= k <= 104`
- `0 <= t <= 231 - 1`

## Code
```
class Solution:
    def containsNearbyAlmostDuplicate(self, nums: List[int], k: int, t: int) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/contains-duplicate-iii/)

**Comment by kamil200** [comment]
I would like to solve this issue please assign me
