### ISSUE TITLE
0050 - Pow(x, n)

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#88]
## Description of the Problem
Implement _pow(x, n)_, which calculates x raised to the power n (i.e. xn).

**Example 1:**
```
Input: x = 2.00000, n = 10
Output: 1024.00000
```

**Example 2:**
```
Input: x = 2.10000, n = 3
Output: 9.26100
```

**Example 3:**
```
Input: x = 2.00000, n = -2
Output: 0.25000
Explanation: 2-2 = 1/22 = 1/4 = 0.25
```
 
**Constraints:**
- `-100.0 < x < 100.0`
- `-231 <= n <= 231-1`
- `-104 <= xn <= 104`

## Code
```
class Solution:
    def myPow(self, x: float, n: int) -> float:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/powx-n/)

**Comment by sarthak55k** [comment]
@vJechsmayr can i do this?
