### ISSUE TITLE
0014 - Longest Common Prefix

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/PythonAlgorithms#9]
Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

**Example 1:**
```
Input: ["flower","flow","flight"]
Output: "fl"
```

**Example 2:**
```
Input: ["dog","racecar","car"]
Output: ""
Explanation: There is no common prefix among the input strings.
```

**Note:**
All given inputs are in lowercase letters a-z.

**Comment by VaibhaveS** [comment]
Hey can you assign me this issue?
I have good experience with competitive programming as well [ rated 1900+ on codechef ]

**Comment by vJechsmayr** [comment]
@VaibhaveS Do you still working on this, or can I unassign you?

**Comment by VaibhaveS** [comment]
@vJechsmayr Yes, I will work on this when i get free time.

**Comment by prackode** [comment]
Please assign it to me. I have a ready to go solution..

**Comment by bhartish** [comment]
@vJechsmayr please assign this problem to me. I have a solution.

**Comment by tegamax** [comment]
please assign this to me, I have already committed the solution . 14, Longest Common Prefix #477

**Comment by vJechsmayr** [comment]
> please assign this to me, I have already committed the solution . 14, Longest Common Prefix #477

@tegamax Sorry you are not assigned - @VaibhaveS will upload as soon as possible
